### ISSUE TITLE
Blizzard Arcade Collection not found with Battle.net import

### ISSUE THREAD

**Issue by Vic502** [JosefNemec/PlayniteExtensions#10]
The new Blizzard Arcade Collection, which include The Lost Vikings and Blackthorne, is not imported when updating the Battle.net game library.  I'm using the new, redesigned Battle.net application (version 1.31.3.12685) and Playnite 8.11 on Windows 10 Pro ver 20H2.

**Comment by JosefNemec** [comment]
Fixed in 8.13
