### ISSUE TITLE
GOG-provided links aren't properly added (auto-download)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/PlayniteExtensions#100]
Minor issue, but when a GOG game is detected for the first time, only one link is automatically added : 

![Sans titre-10](https://user-images.githubusercontent.com/38838369/59231996-f45b3a80-8be2-11e9-9bf5-be613ed1d1eb.jpg)

Manual metadata query fixes it : (GOG games generally have three store provided links, sometimes two)

![Sans titre-11](https://user-images.githubusercontent.com/38838369/59232019-0dfc8200-8be3-11e9-8855-0515adf3b07f.jpg)

**Comment by JosefNemec** [comment]
This was an issue in Playnite that should be fixed now.

**Comment by ClearStrelok** [comment]
I'm temporarily re-opening this issue as I've now noticed that this is still consistently happening on my end (only the store link is initially added, with no translation, and a re-import in the game details is necessary to get the proper links). Could anyone check if they are able to reproduce the issue ?

**Comment by JosefNemec** [comment]
Fixed in 2.10 GOG plugin update
