### ISSUE TITLE
Steam sometimes tracks open state of Playnite application instead of Steam games

### ISSUE THREAD

**Issue by Razukin** [JosefNemec/PlayniteExtensions#103]
**Check for existing issue**
I have not seen this issue reported yet.

**Describe the bug**
Steam sometimes seems to track the state of the Playnite application instead of the underlying game that gets started, and it says the game(s) are still running until I fully close Playnite.

**To Reproduce**
I'm not sure what actually causes this. It does not happen all the time. I ran Slay the Spire about three times, but after I had played it for a couple hours the fourth time, the next day when I tried to run it, Steam said that the app was already running.

So the only steps to reproduce I have are:

1. Run game from Playnite, not directly from Steam
2. Play it for at least an hour or so? Maybe two hours?
3. Close the game through the game's own menus.
4. At some point later, try to run it again.

I expect it to run, but instead Steam says it's already running.

Workaround: Close Playnite and open it again. Steam will detect that the game has closed. Obviously, restarting the computer also works.

This happened with the games Terraria and Slay the Spire.

**Screenshots**
I can take a screenshot of the Steam error I get if it happens again and if you don't know what I mean.

**Diagnostics ID**
N/A

**Comment by JosefNemec** [comment]
I'm closing this since I was not able to reproduce this with any game I tried. And even if I did, there's no way how to "fix" it. We have no control over how Steam detects if a game is running and we launch games standard way that Steam itself directly supports (steam:// uri). So it must be an issue in Steam.
