### ISSUE TITLE
Amazon Games authentication not working

### ISSUE THREAD

**Issue by loficat** [JosefNemec/PlayniteExtensions#11]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by ignishikari** [comment]
Just to report again, I tried to log in today once more and it finally let me in. It asked me for my user and password twice (the second time, I had to fill in a security captcha in addition to my user and password). I copypasted the same password both times. On the second attempt, it finally triggered my 2FA and let me in. This was before updating to 8.12, so it might not be a bug anymore? Currently on 8.12 now and syncing my Amazon library at the moment.

Thanks for your hard work!

**Comment by JosefNemec** [comment]
I will be changing http user agent in Playnite 9, which should hopefully make this more reliable (it at least seems to fix issues with Google sign-in).

**Comment by loficat** [comment]
Thanks. I apologize for not following up sooner. I wasn't able to find this thread (or one other) prior to receiving an e-mail today. Hopefully, the HTTP update corrects the issue, as I've been unable to authenticate my Amazon account since originally posting.

I'm not receiving the error that the other two individuals are.  When I attempt to authenticate via Playnite, I log into the account, which then has me verify my credentials twice, with the addition of a CAPTCHA code (letters and numbers). It then loads the Amazon website homepage into the modal window.

**Comment by ignishikari** [comment]
@loficat it did that with mine, too - it eventually closed on its own and let me in.

**Comment by loficat** [comment]
> @loficat it did that with mine, too - it eventually closed on its own and let me in.

I just tried it again. I went through the two logins and then the homepage loads... Unfortunately, it remains. I've had it open for over 10 minutes. I don't think it's going to work for me. I'm glad it did for you. It has only authenticated the first time, during which I only had to enter my credentials once and then the modal window closed.

**Comment by JosefNemec** [comment]
Please reproduce the issue again with [this build](https://github.com/JosefNemec/PlayniteExtensions/files/6221370/AmazonDebug.zip) of Amazon plugin and generate diag. package that was originally requested in issue template.

Replace files from the archive in `<playnite install dir>\Extensions\AmazonGamesLibrary\`.

**Comment by loficat** [comment]
Thank you for the new files. Unfortunately, they didn't work (for me). Something has changed, as the process only requires two login attempts (one without and one with the CAPTCHA). The Amazon homepage then loads (logged out). I also attempted the authentication after logging into Amazon via Edge prior to authenticating via Playnite with no success. 

Normally, after going through the two (or three) logins, Amazon will send a notification to my phone, which I then have to authorize. Honestly, while I appreciate security, it's a pain. It's not something I opted in for.

If there's anything else I can do to help with this, please let me know. I appreciate your assistance.

**Comment by JosefNemec** [comment]
I have not made any changes in that debug build, only added new debug messages into logs. If you don't send me diagnostics package generated with that special build, then I can't help you.

**Comment by loficat** [comment]
Here you are: 

f3b76748-ce71-4f5d-ac3e-eea89ec90fb9

**Comment by JosefNemec** [comment]
Can you make a video of the issue? It should definitely work according to logs, I can see that authentication worked and redirection url was called with access token (which is the moment when the login window should automatically close).

**Comment by JosefNemec** [comment]
Also, try updating to 8.12 to see if it helps. It has newer version of web view component we use for authentication dialogs.
