### ISSUE TITLE
Rework Steam library import

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/PlayniteExtensions#114]
**Check for existing issue**
Could not find this issue in the ticket system.

**Describe the bug**
Steam version of these games are not imported:
- Alone in the Dark 1
- Alone in the Dark 2
- Alone in the Dark 3

These games gave errors on import, but they are in the library?
- Yume Nikki
- Velvet Assassin
- XCOM: Enemy Unknown
- Mordheim: City of the damned
- Sword Coast Legends
- Orcs Must Die! Unchained ( this f2p game was removed and not playable anymore, this is ok)
- Trillion
- The Walking Dead: A New Frontier

**To Reproduce**
- activate Steam Library Importer.
- Steam Library Options: (x) import installed games, (x) connect account, (x) import uninstalled games, authenticate user, (x) provide API key for "private account"
- update game library -> Steam
Steam games will be imported, but at least not Alone in the Dark 1, 2, 3 

**Screenshots**
Steam versions of  Alone in the Dark in Playnite
https://s1.imagebanana.com/file/200511/BslUXHWu.PNG

Alone in the Dark in my Steam client
https://s1.imagebanana.com/file/200511/UBNveZW0.PNG

**Diagnostics ID**
2020-05-11 08:34:04.5872|INFO:Importing games from Steam plugin.
2020-05-11 08:34:04.5872|INFO:Steam game Das Geisterschiff Remixed is not properly installed or it's a soundtrack, skipping.
2020-05-11 08:34:04.5872|INFO:Steam game Enderal - Forgotten Stories OST is not properly installed or it's a soundtrack, skipping.
...  other soundtrack skipping removed ...
**2020-05-11 08:34:04.5983|INFO:Steam game Velvet Assassin is not properly installed or it's a soundtrack, skipping.**
**2020-05-11 08:34:04.5983|INFO:Steam game XCOM: Enemy Unknown is not properly installed or it's a soundtrack, skipping.**
**2020-05-11 08:34:04.6223|INFO:Steam game Mordheim: City of the Damned is not properly installed or it's a soundtrack, skipping.**
**2020-05-11 08:34:04.6323|INFO:Steam game Sword Coast Legends is not properly installed or it's a soundtrack, skipping.**
**2020-05-11 08:34:04.6464|INFO:Steam game Orcs Must Die! Unchained is not properly installed or it's a soundtrack, skipping.**
**2020-05-11 08:34:04.6584|INFO:Steam game Trillion is not properly installed or it's a soundtrack, skipping.**
**2020-05-11 08:34:04.6584|INFO:Steam game The Walking Dead: A New Frontier is not properly installed or it's a soundtrack, skipping.**
**2020-05-11 08:34:04.6835|INFO:Steam game Yume Nikki is not properly installed or it's a soundtrack, skipping.**
....
2020-05-11 08:34:04.7075|DEBUG:Found 457 installed Steam games.
2020-05-11 08:34:04.7075|DEBUG:Downloading string content from https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=redacted&include_appinfo=1&include_played_free_games=1&format=json&steamid=76561198055778112 using System.Text.UTF8Encoding encoding.
2020-05-11 08:34:06.1173|DEBUG:Found 6631 library Steam games.

It is funny that my Steam client says that I have 7255 games (see https://s1.imagebanana.com/file/200511/UBNveZW0.PNG), Playnite finds 6631/6680 games (see https://s2.imagebanana.com/file/200511/06oL0YkF.PNG ) and my online profile states that I have licensed 4622 games (https://steamcommunity.com/id/shakeyourbunny). I also checked the latter games tab where it could not locate the three Alone in the Dark games I do have.

Alone in the Dark 1: appid 548090 https://s1.imagebanana.com/file/200511/nXUvl9Wg.PNG
Alone in the Dark 2: appid 548890 https://s1.imagebanana.com/file/200511/ehWueJaU.PNG
Alone in the Dark 3: appid 548900 https://s2.imagebanana.com/file/200511/PtvbNEo9.PNG

SteamDB entry for the series: https://steamdb.info/search/?a=app&q=Alone+in+the+Dark&type=1&category=0

**Comment by JosefNemec** [comment]
Closing since most issue here have been fixed on Steam's side (like feature limited games) and the rest is imo too niche to be worth redoing the whole auth, but more importantly not worth not using official API anymore, which gives us more stability in long term.

There's always a workaround where you can temporarily install a game, let it import and then uninstall it, which will leave it imported in Playnite.
