### ISSUE TITLE
Add support for importing vertical GOG Galaxy 2.0 Covers

### ISSUE THREAD

**Issue by awbooze** [JosefNemec/PlayniteExtensions#115]
This is similar to JosefNemec/Playnite#1455, but for GOG. It would be nice to be able to have the option to import the vertical covers that GOG Galaxy 2.0 uses as opposed to the horizontal ones that are imported by default. It seems like some of the covers might be from IDGB (like _Beneath a Steel Sky (1994)_), but others are not, such as their covers for the _Master of Orion_ series or _Stargunner (1996)_. Also, I completely understand if they're just not returned by whatever API you're using right now.

Edit: This also might apply to backgrounds, but I don't think they have any differences between what's imported and what's displayed.

**Comment by JosefNemec** [comment]
Closing, I had a brief look into this and it looks like pain to implement. There are other metadata sources that already provide vertical covers which can be used as alternatives.
