### ISSUE TITLE
Playnite not tracking time for epic games started through Playnite

### ISSUE THREAD

**Issue by shivam13juna** [JosefNemec/PlayniteExtensions#118]
I'm trying to start GTA 5 through playnite, it just doesn't track time. Perhaps coz playnitetriggers game through the epic link which redirects to rockstar launcher and then they authenticate, and somewhere in between playnite loses track of game, and doesn't track time. It does start the game but doesn't track time. 

I'm not even sure how something like this can be fixed...

**Comment by JosefNemec** [comment]
Caused by #7
