### ISSUE TITLE
Rework IGDB search

### ISSUE THREAD

**Issue by Overload86** [JosefNemec/PlayniteExtensions#119]
**Describe the bug**
I tried searching for [The Company Man](https://www.igdb.com/games/the-company-man) without any luck. Tried "Company Man" "The Company Man" "Company Man Game" "Company". Last search obviously had some results, but not the right one.
Pasting the whole URL from above into the search box gave me the result I was looking for, but interestingly it showed only the name without the release year in parentheses below it, like it normally does. It does not yet have a score, it _does_ however have a release date, so I am not sure what could be the problem with parsing this particular game.

**To Reproduce**
Search for "Company Man" via IGDB. I suspect it is not a singular problem, but have no other examples at this point.

**Comment by JosefNemec** [comment]
done
