### ISSUE TITLE
Start Warzone/ColdWare - battlenet fail

### ISSUE THREAD

**Issue by GitWatin** [JosefNemec/PlayniteExtensions#12]
**Description**
When I launch blizzard games, 
it often happens (70% of the time) that the launcher battlenet starts but waits for you to click on "Play".
The problem often occurs when the launcher service is not yet started on the computer.
My friend also has the same problem.

**To Reproduce**
start warzone/coldwar in playnite

**screenshot**
https://www.youtube.com/watch?v=-6yXOk-P6vw

**Diagnostics ID**
Playnite Version : 8.11
Battlenet launcher : 1.31.2.12679
Windows 10 Pro 1909 ( Build 18363.1979 )

I see this issue seem to be fixed : https://github.com/JosefNemec/Playnite/issues/692

**Comment by JosefNemec** [comment]
Closing since this is not issue on our side.
