### ISSUE TITLE
Playnite doesn't see my steam games

### ISSUE THREAD

**Issue by chaud-froid** [JosefNemec/PlayniteExtensions#122]
Hello, I have a problem, Playnite doesn't see my steam games (with the extension "steam library integration"). Steam is installed in C: drive but the games are in a E: drive. I think playnite looks in C: but not in E:. How can I fix that ?

I have the 9.6 version. I create this issue because darklinkpower on discord told me to.
diagnostics package : 57d78b6c-51bb-446c-9304-2d1cbeb40b94

**Comment by JosefNemec** [comment]
Try reinstalling Steam, that usually fixes it.

**Comment by JosefNemec** [comment]
Ignore my last comment, it's because you don't have import of Steam games enabled. Go to add-ons menu and enable it in Steam's integration settings.

**Comment by chaud-froid** [comment]
no. it's enabled and it's the same problem
![Capture d’écran (37)](https://user-images.githubusercontent.com/47120813/139598353-78b43453-040e-4fe5-b60a-5ee35d47798a.png)
.

**Comment by JosefNemec** [comment]
You need to go extension settings section.
![image](https://user-images.githubusercontent.com/3874087/139598554-683df901-e3b1-4602-b2fa-f62a78949393.png)

**Comment by chaud-froid** [comment]
hoo I'm an idiot.... Thanks soo much and sorry for being a noob :(
