### ISSUE TITLE
Allow import of multiple Origin accounts

### ISSUE THREAD

**Issue by Logerfo** [JosefNemec/PlayniteExtensions#123]
Similar to #21, but for Origin.
I quote myself on https://github.com/JosefNemec/Playnite/issues/2624#issue-1041702183:
> I think that the main issue here would be the client integration, since only the current logged in account would be able to launch games. But maybe Playnite could specify that the said game is linked to another account than the current one, and which one (so users don't need to remember which account has each game).
Having multiple accounts on the same service can happen in some scenarios, like:
> - Losing access and recovering it later, after creating another account.
> - Getting temporarily banned.
> - Region related matters.
> - etc.

**Comment by JosefNemec** [comment]
This is not possible because of how we import Origin games. Only one account can be linked at a time. You can use workaround by linking one account, importing games, linking different one, importing games again. We never remove games automatically so you will end up with games from both accounts.

**Comment by darklinkpower** [comment]
As an alternative/workaround and what I did once for a similar purpose was have two Playnite portable installations, each with their own logged accounts that used the same database. Then when I wanted to import the games from one account I just booted the other Playnite installation, imported the games and switched back to my other Playnite install.
