### ISSUE TITLE
[Steam integration] Slow launch speed for games imported from Steam library 

### ISSUE THREAD

**Issue by lqa-gh** [JosefNemec/PlayniteExtensions#126]
**Describe the bug**
Games imported using the steam integration extension launch really slowly if they are launched from Playnite. If I double click on the entry on Playnite, it would take about 10 seconds before the Steam client starts to respond (despite the fact that I got the client already opened and running in the background). In contrast, if I launch directly from the Steam client (pressing the green 'play button'), the games started immediately. So it's unlikely a problem on the side of Steam, I even re-installed Steam. 

**To Reproduce**
1. Use the steam library integration extension to import games. 
2. Launch those games from Playnite.

**Comment by JosefNemec** [comment]
Can't reproduce.

Please make sure this is not caused by some other 3rd party extension. Steam integration just opens specific steam:// URI when starting a game and can't take so long.

**Comment by lqa-gh** [comment]
Hmm you are right, I just created a desktop shortcut from Steam, and launched the games that way. The problem is reproduced. So the problem has nothing to do with Playnite after all. Must be a problem with how my computer handles steam's internet shortucts.
