### ISSUE TITLE
GOG and EPIC downgrade to v1.0

### ISSUE THREAD

**Issue by Idecman** [JosefNemec/PlayniteExtensions#127]
GOG (v2.5) and Epic (v2.6) library integration (both from the last update yesterday) downgrade to v 1.0 . I try to upgrade repeatedly, and I can't, after restart Playnite, the version remains 1.0. 
I have uninstalled both, and now directly, it cannot be installed. The installation process works fine (it seems), but when Playnite restarts, it are't installed.

9d5557ee-8ad1-428b-9bf5-f53c87d8925d

Thanks you so much.

**Comment by JosefNemec** [comment]
I don't know how you did it, but you have weird miss match of old (Playnite 8 versions) and new extensions installed. Were you doing something manually with extension installations?

Either way, got to `%appdata%\playnite\extensions\` and `%localappdata%\playnite\extensions\`, delete everything there and reinstall extensions from add-on browser.

**Comment by Idecman** [comment]
I have remembered that I have a backup from November 20. I have done what you have told me, delete the contents of both folders, and I have put the backup copy. I don't know what could have happened, I haven't been doing anything weird. Now everything seems to work fine. Thank you very much for your help.
