### ISSUE TITLE
New Behavior Possible - Launch Origin/EA Desktop Games directly from Playnite

### ISSUE THREAD

**Issue by LordMethenor** [JosefNemec/PlayniteExtensions#128]
Note: I use EA Desktop because of Xbox Game Pass Compatibility, but the Origin plugin detects my games anyways. From what I read here, that is expected behavior.

Currently, the default play action for the Origin library plugin opens the game page in EA Desktop but requires the user to open the game. This means an extra click and makes it difficult to launch the game solely with a controller. 

Recently, EA Desktop enabled launching games from shortcuts or the game's own executable. Doing this will open the launcher, open the game, and minimize the launcher. Could the library plugin be updated to launch games directly with the play action?

I tried to accomplish this with a custom play action directing to the game executable (starwarsbattlefrontii.exe), and the game launches, but Playnite's tracking fails, and I don't know how to customize it to work.

**Comment by JosefNemec** [comment]
Any integration with EA Desktop right now is problematic because the launcher is not finished yet and it's missing basic features like an ability to launch games externally.

**Comment by JosefNemec** [comment]
Will be done when possible via #13

**Comment by LordMethenor** [comment]
That's what I'm saying. That ability has been added.



Have a nice day,
Lee Seelig



-------- Original message --------
From: Josef Nemec ***@***.***>
Date: 12/27/21 5:46 AM (GMT-05:00)
To: JosefNemec/PlayniteExtensions ***@***.***>
Cc: Adonnen ***@***.***>, Author ***@***.***>
Subject: Re: [JosefNemec/PlayniteExtensions] New Behavior Possible - Launch Origin/EA Desktop Games directly from Playnite (Issue #128)


Any integration with EA Desktop right now is problematic because the launcher is not finished yet and it's missing basic features like an ability to launch games externally.

**Comment by JosefNemec** [comment]
That's not what I meant. Origin has a way where we can tell it to launch a game and it doesn't matter where the game is installed or what its executable is. EA Desktop doesn't have anything like that yet, as far as I know. Detecting game's executable and then trying to launch that would not be reliable (we used to do that with Origin).

**Comment by LordMethenor** [comment]
Ah. Ok. Thank you.


-------- Original message --------
From: Josef Nemec ***@***.***>
Date: 12/27/21 6:11 AM (GMT-05:00)
To: JosefNemec/PlayniteExtensions ***@***.***>
Cc: Adonnen ***@***.***>, Author ***@***.***>
Subject: Re: [JosefNemec/PlayniteExtensions] New Behavior Possible - Launch Origin/EA Desktop Games directly from Playnite (Issue #128)


That's not what I meant. Origin has a way where we can tell it to launch a game and it doesn't matter where the game is installed or what its executable is. EA Desktop doesn't have anything like that yet, as far as I know. Detecting game's executable and then trying to launch that would not be reliable (we used to do that with Origin).
