### ISSUE TITLE
Owned Steam game soundtracks are not displayed correctly in Playnite

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/PlayniteExtensions#130]
According to Steam I own 29 game soundtracks.

Although Playnite seemingly lists all my 4205 games/soundtracks, when I search for "soundtrack" Playnite returns only 1 entry.
On it's turn this entry isn't listed as a soundtrack in Steam. It's probably wrongfully tagged as a game (or app).

When I search for "soundtrack" in an exported database .csv (which contains 4205 lines) it returns only that one entry.
There are no other entries that contain the word "soundtrack".

![2021-12-05 14_35_35-Steam](https://user-images.githubusercontent.com/16439116/144749935-81e2ae4e-6fee-4a9a-a80d-8ffd6fc801a5.png)

I can't seem to figure out which are the 29 lines that contain the soundtracks. The exported .csv contains 4205 lines, but not the 29 soundtracks. So where are they?

Surely there is a problem displaying soundtracks and with there presence in the database.

**Comment by JosefNemec** [comment]
We only import (and can import) items that Steam API reports as part of your library, if some items are missing, then I'm afraid there's nothing we can do about it.

I am considering doing some rework of how Steam import works (in #114), but I'm not sure it would fix this anyways, we simply depend on what data Steam gives us.
