### ISSUE TITLE
Steam game uses japanese name instead of english title

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/PlayniteExtensions#131]
**Describe the bug**
Steam library

Game uses japanese name instead of english title and the one used in the store and client

**To Reproduce**
Happens with game [Fuga: Melodies of Steel](https://store.steampowered.com/app/1357860/Fuga_Melodies_of_Steel/)

**Screenshots**
Playnite after import: 戦場のフーガ

![image](https://user-images.githubusercontent.com/1389286/147397943-78f8bb10-27bb-4859-9b39-2fde93c9a206.png)

Client and store: Fuga: Melodies of Steel

![image](https://user-images.githubusercontent.com/1389286/147397944-69396b82-6deb-477e-b185-6e0542b055a4.png)

![image](https://user-images.githubusercontent.com/1389286/147397950-c7c0e87c-919f-48c3-87fe-a033149eeb61.png)

Appdetails api also reports this same title https://store.steampowered.com/api/appdetails?appids=1357860

**Diagnostics ID**
48918cbf-1d63-4729-9262-b51c41c68186

**Comment by JosefNemec** [comment]
It's what Steam itself returns as a name, you can see that SteamDB lists it under the same name: https://steamdb.info/app/1357860/

I could in theory switch it to use store's name, but I don't know if it's not going to break some other things. I don't remember why we prefer name from Steam API instead of Store API.

**Comment by JosefNemec** [comment]
I just found that there's `name_localized` property that Steam API returns. I'll add check for that if it returns English variant and use that instead.

![image](https://user-images.githubusercontent.com/3874087/147464159-27eaa072-8b68-4ef3-a9ce-18d2d9bd21c9.png)

**Comment by JosefNemec** [comment]
Fixed in 2.4
