### ISSUE TITLE
Error importing Epic

### ISSUE THREAD

**Issue by rentela** [JosefNemec/PlayniteExtensions#132]
**Describe the bug**
When importing Epic games it gives the following error:
"Failed to import games from Epic. Unexpected character encountered while parsing value: <. Path ", line 0, position 0."

**To Reproduce**
Just update Epic games library

**Diagnostics ID**
2b734c2f-56e2-4b49-9385-c2a9ac6a8436

**Comment by JosefNemec** [comment]
It's an issue on Epic's side: https://status.epicgames.com/
