### ISSUE TITLE
Failed to Import Epic Games

### ISSUE THREAD

**Issue by shangles** [JosefNemec/PlayniteExtensions#133]
**Check for existing issue**
Not found

**Describe the bug**
I'm unsure if this is related to the current Epic Games issues or not (https://twitter.com/EpicGames/status/1476231639428739087) but figured it was worth posting.

I just updated Playnite to the latest version and re-authenticated my Epic account and tried to sync Epic Games after claiming today's free game and got this error message in Playnite:

`Failed to import games from Epic. Unexpected character encountered while parsing value: <. Path ", line 0, position 0`

**To Reproduce**

-     Update Playnite
-     Authenticate with Epic Games
-     Update Epic library

**Screenshots**
N/A

**Diagnostics ID**
5eb8ec6e-5011-4979-8ba6-e4343d9d18e2

**Comment by JosefNemec** [comment]
Duplicate #132
