### ISSUE TITLE
EPIC: Unexpected character error when importing a game from a backlogged order

### ISSUE THREAD

**Issue by CyberScooby** [JosefNemec/PlayniteExtensions#134]
For the holidays, Epic has been giving away one or more games every day. This has been especially popular which has been swamping out their servers at times ... especially today with three Tomb Raider games.

What I have encountered is the following situation:

1. Order your free game on Epic
2. It says that the order processing has completed
3. Try to import it into Playnite only to receive the following error message:
             **Failed to import linked account Epic games details.
             Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.**
4. If you try to order the free game on Epic again it will state that you already own the game or it is still processing
5. Eventually the issue will resolve itself.

So essentially, the games can be partially processed and get backlogged before completion. It would be helpful if the Epic extension could detect this situation and provide an appropriate message that the game being processed into your account.

To reproduce this, you need to order a game during a busy period. Most likely time is at 11 AM EST when new free games go live.

Diagnostic ID --> 9d1e3603-7f22-4711-98ca-e35e971e9e0b

**Comment by JosefNemec** [comment]
It has nothing to do with games being processed. It happens when Epic's servers have issues: #132 and https://status.epicgames.com/

**Comment by CyberScooby** [comment]
Thanks @JosefNemec.

Sorry for creating the duplicate. I had encountered this issue a day or two ago and couldn't find this reported. It happened again today so I created this bug. Guess I should have redone my search first.

Closing this case in favour of the original reported "issue".

**Comment by JosefNemec** [comment]
I'll leave this open and improve the error message to something better.

**Comment by JosefNemec** [comment]
Done in the latest update.
