### ISSUE TITLE
Battle.net: Blizzard Arcade Collection - installed & ownership status desyncs

### ISSUE THREAD

**Issue by ghost** [JosefNemec/PlayniteExtensions#137]
**Check for existing issue**
Checked everything, found only closed #10 .

**Describe the bug**
1. Purchased but not installed Blizzard Arcade Collection is not appearing amonng owned games on library import.
2. Import ran during game install marks it as Installed.
3. Uninstalling the game through Battle.net launcher then running library update does not mark the game as uninstalled.

Can't be 100% sure about 2nd issue, but 1st and 3rd are not reproducible with Starcraft and Diablo III.

Started happening somewhere around month ago. Maybe earlier. At least I believe that I did seen itin my library at around December 25th, 2021...

The game is still available at battlenet store. Due for removal at February 20, 2022  currently.

**To Reproduce**
Own the game, get the plugin, run the import...

**Screenshots**
![Снимок](https://user-images.githubusercontent.com/81986452/147944772-8792850e-c0da-462d-a262-84875350e1bc.PNG)

**Diagnostics ID**
2181645c-2b26-458b-9396-133bd80c4e16

**Comment by JosefNemec** [comment]
Please do following:
1) Log into battle.net account in a browser
2) Navigate to https://account.battle.net/overview
3) Navigate to https://account.battle.net/api/games-and-subs and upload page content you'll receive

**Comment by DrinkFromTheCup** [comment]
Here, please:
[games-and-subs.txt](https://github.com/JosefNemec/PlayniteExtensions/files/7802742/games-and-subs.txt)
Double-checked, it's indeed the output from the account I use with Playnite.

Looks like they krangled their API so I probably have to go make some hustle at their Customer Support, right?

**Comment by JosefNemec** [comment]
I doubt that their support will be willing to help with issues from 3rd party apps they don't support (they obviously don't use that API endpoint internally in bnet client itself).

I'll try to check if there's some other place we can check for Arcade Collection ownership, but I don't actually own it so most likely somebody else will have to look into it.

**Comment by DrinkFromTheCup** [comment]
Well, man can hope - and it was statistically probable that their quality of service have increased since my last contact attempt.
So I tried - and failed, support bot is not even trying to pass as real person and refuses to call real person in.
I've seen that there are chances to catch them in live chat - will try. Free exercise in English, at Blizzard's expence, is better than nothing at all...

**Comment by JosefNemec** [comment]
Closing as I don't have a way how to properly debug this any further since I don't own these games. Somebody else will have to look into it, pull requests are welcome.
