### ISSUE TITLE
Wrong game gets added if IGDB is selected

### ISSUE THREAD

**Issue by PowerShell2020** [JosefNemec/PlayniteExtensions#138]
**Check for existing issue**
Nothing found

**Describe the bug**
I own "Nioh: The Complete Edition" in the epic game store.
If IGDB is selected at metadata then the wrong game "Nioh 2: The Complete Edition" gets added from my epic game store account.
If IGDB is deselected then the right game "Nioh: The Complete Edition" gets added from my epic game store account.  

**To Reproduce**
Select IGDB at metadata and import epic game store games.
Deselect IGDB at metadata and import epic game store games.

**Screenshots**
![image](https://user-images.githubusercontent.com/64898836/148127520-5f8a1ee5-932e-4bfc-9909-a69d2c87c516.png)

**Diagnostics ID**
9f717a63-5f50-4064-bce0-0e395ba9d32e

**Comment by JosefNemec** [comment]
Metadata plugins don't affect what game is being added. Only what metadata are applied, so it's still the correct game, just with wrong name for some reason.

**Comment by PowerShell2020** [comment]
Thank you for your fast response. :)
Yeah I worded it wrong. It's only the metadata that's wrong. The game-id is the right one.
Just wanted to let you know.
I don't know if you can do something about it or if that's just a IGDB thing.
You can close it if there's nothing you can do.
