### ISSUE TITLE
Xbox app not tracked the right way

### ISSUE THREAD

**Issue by Pierre-G** [JosefNemec/PlayniteExtensions#143]
When I quit Xbox app, launched through Playnite, Playnite continues to display "Xbox is running". Of course, I've unchecked the Xbox app's setting to keep the app running in the background when I close it.
So Playnite doesn’t track this particular Microsoft store app the right way. And sadly I didn’t find any workaround.

**Comment by JosefNemec** [comment]
It probably means that it's still running in the background. UWP apps do that sometimes.
