### ISSUE TITLE
Planescape: Torment: Enhanced Edition (GOG) fails to launch from Playnite but launches from Windows

### ISSUE THREAD

**Issue by CalAlaera** [JosefNemec/PlayniteExtensions#15]
**Describe the bug**
I purchased Planescape: Torment: Enhanced Edition from GOG. I installed it using the offline installer, and Playnite correctly picked it up and added it to my library. It launches fine from the "installation finished" screen and from Windows Explorer, but when I run the same commandline from Playnite I see an error message.

**To Reproduce**
1. Install Planescape: Torment: Enhanced Edition from GOG.
2. Update Game Library > GOG
3. Run Planescape: Torment: Enhanced Edition.

**Screenshots**
![image](https://user-images.githubusercontent.com/59891537/112713809-ef0dd380-8ece-11eb-83d8-c5052f9087a6.png)

**Diagnostics ID**
db214d95-de75-4c09-a762-e6d013d616bf

**Comment by JosefNemec** [comment]
There should `goggame-<some number>.info` file inside of installation directory, can you please upload that?

It's most likely that Playnite wrongly auto-detected what exe/arguments to use to launch the game (from that file). Until this is fixed, you can manually change target executable by editing game's play action (and disabling `managed by the library plugin` option) and setting it to correct one.

**Comment by CalAlaera** [comment]
As requested: [Planescape Torment - Enhanced Edition.zip](https://github.com/JosefNemec/PlayniteExtensions/files/6215367/Planescape.Torment.-.Enhanced.Edition.zip)

Playnite detected the exe correctly, and correctly added no arguments. GOG dropped a shortcut in the folder which just links to "D:\GOG\Planescape Torment - Enhanced Edition\Torment.exe". Running Torment.exe from Windows works fine. 
![image](https://user-images.githubusercontent.com/59891537/112714953-fdf78480-8ed4-11eb-812b-3ec8a60f203c.png)

**Comment by JosefNemec** [comment]
That's weird. Try changing `Path` to full path (`d:\etc...\torment.exe`) and leave working directory empty.

**Comment by CalAlaera** [comment]
> That's weird. Try changing `Path` to full path (`d:\etc...\torment.exe`) and leave working directory empty.

Yes! That works, and I have no idea why, but I'll take it! Thanks :)

**Comment by JosefNemec** [comment]
Fixed in master.
