### ISSUE TITLE
GOG: games installed with stand-alone installers are failing to appear

### ISSUE THREAD

**Issue by DrinkFromTheCup** [JosefNemec/PlayniteExtensions#150]
**Check for existing issue**
Checked, it may or may not be a #73 relapse.

**Describe the bug**
Recently, some games installed with stand-alone installers started failing to appear in GOG integration.

Offending titles noticed so far:
- Vampire: The Masquerade - Redemption
- S2: Silent Storm Gold Edition

Both were detected by previous versions of GOG integrations - both are not currently.

Other games are being detected just fine, including ones with quite... antique installers like Titus the Fox and VTM Bloodlines.

**To Reproduce**
Preconditions:
- (might be irrelevant) GOG Galaxy was installed at some point but is NOT present in the system.
- latest public versions of Playnite (9.16) and GOG integration.

Steps:
1. Initiate Install for offending game through Playnite
2. Download the installer from opened https://www.gog.com/account page
3. Run the installer (even at default location)
4. Wait for the game to appear in Playnite

ER
As up until recent, the game appears with all relevant intel being correct.

AR
The game hangs in Installing state. Restarting Playnite and initiating manual sync does not help.

**Diagnostics ID**
dec2203b-e8ce-47d9-b01e-43dced6dff78

**Comment by JosefNemec** [comment]
Registry information GOG integration uses to detect installed games point to this folder for Vampire: `C:\Program Files (x86)\GOG Galaxy\Games\Vampire The Masquerade - Redemption\`, is that correct?

There's no information about S2 installation at all. Which means that those offline installers didn't create necessary registry keys or they created them badly. It's the same exact issue as #73, nothing I can do about it, sadly.

**Comment by JosefNemec** [comment]
>  in legacy installers for old games, which are still around

What do you mean by this? Did you try using installers that you can actually download from GOG as of today?

**Comment by DrinkFromTheCup** [comment]
All installers I used were downloaded from scratch. Not kept since uncertain times. Smol HDD, all space in cloud storage is occupied :|
By 'legacy installers' I mean ones which were made available at https://www.gog.com/account way before Galaxy 2.0 and never updated since then.
These differ a little with modern installers feature-wise (some don't offer setup wizard language choice, some always have 'Create desktop shortcuts' pre-selected, some... I believe, have fewer ads built-in AND better unpacking scripts, thus work way faster).
Said Unreal Gold never received any updates - and its installer is so old so it even doesn't have a version number in its card at games shelf:
![Снимок](https://user-images.githubusercontent.com/81986452/155923072-308e06dc-611b-4397-ae51-614bfa91f8dd.PNG)

**Comment by JosefNemec** [comment]
I checked import code and it looks like we explicitly ignore games installed with these very old installers. I don't remember why, there might have been some issues with their startup or something like that.

**Comment by JosefNemec** [comment]
So I looked at possible workaround I haven't found a reliable way how to import these games. These legacy installers don't even include config files that have information about how to start a game, without those Playnite wouldn't be able to launch these games anyways.

I'm afraid the only way is to somehow convince GOG to update these installers.
