### ISSUE TITLE
No settings available

### ISSUE THREAD

**Issue by xCeeTee** [JosefNemec/PlayniteExtensions#152]
I have reinstalled the integration multiple times. I have tried on several different days across this last week and it's given me the same problem each time. [Here's a screenshot of the settings.](https://i.imgur.com/h5txB0C.png) The message about restarting is about another extension I was tweaking before taking this screenshot.

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

25bfff10-bb06-49b8-825d-ca1c939f0111

**Comment by JosefNemec** [comment]
Rockstar integration doesn't have any settings.
