### ISSUE TITLE
"Start Xbox Pass app instead of Microsoft Store when opening client" option does not work

### ISSUE THREAD

**Issue by nicksundermeyer** [JosefNemec/PlayniteExtensions#155]
**Describe the bug**
The "Start Xbox Pass app instead of Microsoft Store when opening client" option in the Xbox addon settings does not work. I have it checked, but it still opens the Microsoft Store when trying to install Xbox games.

**To Reproduce**
Check the option in addon settings, and then try to install a game. It will launch the Microsoft Store instead of the Xbox app.

**Diagnostics ID**
c4d53c36-72fa-43f1-9e4f-b441d79690ef

**Comment by JosefNemec** [comment]
Done in the latest update.
