### ISSUE TITLE
Option to change and prioritize IGDB search parameter

### ISSUE THREAD

**Issue by Bolthier** [JosefNemec/PlayniteExtensions#157]
### Feature description

Right now there seem to be two different behaviors while using the IGDB metadata addon.
1. While using the bulk editor "Library" > "Download Metadata" the application searches for the Source Name.
2. Using the "Edit" function directly for a game uses the Display Name of the game.

It would be great to have an option to change and prioritize the search parameter when downloading metadata through the IDGB addon. Both while editing a single game and bulk editing.

For example (sorted by my personal priority):

- IGDB ID*
- Original Name*
- Name (Display Name)
- Source Name

If a parameter is absent it would use the next one.

Parameters with * not available right now.

IGDB ID
https://github.com/JosefNemec/Playnite/issues/595

Additional name fields (Original Name and Source Name)
https://github.com/JosefNemec/Playnite/issues/2814
https://github.com/JosefNemec/Playnite/issues/2859

### Screenshots

Screenshot
Bulk editing of metadata
![image](https://user-images.githubusercontent.com/42382626/159909844-5a01f75c-8823-4688-8a37-0de12be5a550.png)

Directly editing of metadata
![image](https://user-images.githubusercontent.com/42382626/159910070-973845cb-7519-4573-b352-0b9d761f7011.png)

**Comment by JosefNemec** [comment]
This doesn't make sense because Playnite stores only one name, which is what IGDB then uses. Your issue is mostly caused by unreadable search on IGDB API's side (for example #119 is affected by the same thing). I am slowly rewriting IGDB search to custom search, but it's not finished yet.
