### ISSUE TITLE
Crash Bandicoot 4 doesn't import (Battle.net)

### ISSUE THREAD

**Issue by teconmoon** [JosefNemec/PlayniteExtensions#16]
Currently with the Battle.net extension, Crash Bandicoot 4 does not import.

Creating a manual entry pointing to the game EXE is not sufficient as the game then fails the Battle.net online check, though pointing to battle.net.exe with the parameters --exec="launch WLBY" can at least launch the game.

**Comment by JosefNemec** [comment]
Fixed in 8.13
