### ISSUE TITLE
 Itch.io: old collections are imported instead of latest collections.

### ISSUE THREAD

**Issue by ryouma-aurora** [JosefNemec/PlayniteExtensions#160]
**Describe the bug**
After modified collections, Itch.io integration imoports  old collections  instead of latest collections.

**To Reproduce**
Set Itch.io integraion to import collections, and import collections.

Create new collections and/or add games to collections at itch.io web. Try import latest collections.
Itch.io integration imoports old collections.
After reloading collections by using itch.io client, Itch.io integration imoports latest collections.

**Comment by ryouma-aurora** [comment]
I'm sorry, I made a pull request for a fix before reporting this isuue.

**Comment by JosefNemec** [comment]
Fixed in 2.4
