### ISSUE TITLE
Itch.io Library Plugin unsets installed status on manually configured entries

### ISSUE THREAD

**Issue by Mellified** [JosefNemec/PlayniteExtensions#163]
Itch.io games create a somewhat unique problem in Playnite. It's possible to have free and purchased games from Itch which cannot be installed via the Itch client. These are larger games, which are hosted on third party sites. When manually installing these games the Playnite user has a couple of choices:

1. Add the game as a separate entry in Playnite. This means manually entering all the metadata, finding images, and tracking where the game was originally obtained.
2. Configure the existing Itch.io Playnite game entry manually to point to the installed game. This is accomplished by unchecking "Include library integration play actions" and setting the installation folder and marking the game as installed.

Many games on Itch only exist on Itch. Itch can't be referenced as a metadata source for games which didn't originate in Itch. There's little or no metadata available from Playnite's other sources. So using the Itch.io entry is the only automated way to get metadata for these games. As a result the second option is preferred for Itch.

Unfortunately, when Playnite scans the Itch library it deletes the "installation directory" and marks these manually configured games as "not installed". I believe this is a bug - not a feature request - because it ignores the user's expressed intent to have the game marked installed. It's probably not worth having Playnite track whether a plugin or the user marked a game as installed. Instead, I propose that any game with manually defined Play actions have its installed state ignored by the library plugin.

To Reproduce
Add a free game from Itch which requires downloading from a third party site to a collection.
Enable "Import free games from collections" setting in the Itch library plugin settings.
Select "Update Game Library -> Itch" to trigger Playnite to add the Itch game to Playnite.
Configure a play action and mark the game as installed.
Select "Update Game Library -> Itch" to trigger Playnite to add the Itch game to Playnite.
Observe the game is no longer installed.

**Comment by JosefNemec** [comment]
Please give some examples of games that are affected by this.

I think it will require implementation of some blacklist to ignore install state that we get from itch service for specified games, because itch plugin sets installation status based on what itch tells it is.

**Comment by Mellified** [comment]
Here are three examples. I have 61 Itch.io games which are marked "not installed" in my library, but have manual installations configured. Some of these I have Playnite importing using Itch collections, others are paid Itch titles.

Given the volume I don't know that a blacklist is practical. I've also had games that were distributed via Itch switch because their game hits the size limit. That's why I suggested the library plugin needs to check for a manual Play Action before wiping the installed flag and installation directory.

https://hopesgaming.itch.io/the-deluca-family
https://sinappeal.itch.io/wings-of-silicon
https://antidotelab.itch.io/nerverbackdown

**Comment by JosefNemec** [comment]
I thought about it and it would make the most sense to add installation status overwrite option to Playnite for games imported by library integration plugins. It will still require some support from plugins that use custom import mechanism (itch is not one of those), but it's probably the most universal way how we can approach this.

I'll add it in [P10](https://github.com/JosefNemec/Playnite/issues/2879).
