### ISSUE TITLE
Battle.net play action does not launch the game, if the launcher is not started first. Gets stuck in "Launching" state.

### ISSUE THREAD

**Issue by Overload86** [JosefNemec/PlayniteExtensions#168]
Launching Starcraft 2 via Playnite only works, if battle.net launcher is already running. Else it starts the launcher and the play button has the label "Launching", but nothing happens.

A quick glance over the code did not show why this happens (at least not for a noob like myself). From what I can gather, the plugin should indeed start the launcher, wait for three instances of the process (checked in task manager, there are indeed at least 3) and then start the game.

The log file also shows this is indeed firing. But the game never launches. Only if I click the "Launching" button, tell it to stop monitoring and then click Play again (this time with the launcher open).

```
14-04 06:02:34.500	INFO	BattleNetLibrary#BnetPlayController:Battle.net is not running, starting it first.
14-04 06:02:34.500	DEBUG	BattleNetLibrary#ProcessStarter:Starting process: C:\Games\Battle.net\Battle.net.exe, , , False
14-04 06:02:37.163	DEBUG	BattleNetLibrary#ProcessStarter:Starting process: C:\Games\Battle.net\Battle.net.exe, --exec="launch S2", , False
14-04 06:02:37.172	DEBUG	BattleNetLibrary#ProcessMonitor:Watching dir processes G:\Games\StarCraft II, False, False
```

**Comment by JosefNemec** [comment]
Done in the latest update.

**Comment by Overload86** [comment]
And how do I get this update? Playnite does not show any new updates and the Github release is still the old one.

**Comment by JosefNemec** [comment]
main menu -> add-ons
