### ISSUE TITLE
Can't authenticate with Epic Games

### ISSUE THREAD

**Issue by manther02** [JosefNemec/PlayniteExtensions#17]
When trying to authenticate Epic Games with email and password I am redirected to the account settings and can't authenticate.

![step1](https://user-images.githubusercontent.com/11697273/113206346-43b2a500-9267-11eb-8f70-4d75af552cf1.PNG)

![step2](https://user-images.githubusercontent.com/11697273/113206347-444b3b80-9267-11eb-829b-e96db9a160be.PNG)

![step3](https://user-images.githubusercontent.com/11697273/113206349-444b3b80-9267-11eb-86d7-f0bd8fdc7a75.PNG)

I am getting stuck in the last step... :(

**Comment by zany130** [comment]
same issue here

**Comment by JosefNemec** [comment]
Are you using 8.12 update?

**Comment by Droppisalt** [comment]
Just an FYI I had this issue yesterday, then upgrade to 8.12 and it's now fixed for me.
