### ISSUE TITLE
No detection of playtime for Anno 1800

### ISSUE THREAD

**Issue by Kinc4id** [JosefNemec/PlayniteExtensions#172]
Pretty much the same issue as [here](https://github.com/JosefNemec/PlayniteExtensions/issues/42) but with Anno 1800. Playnite minimizes, launcher starts, launcher closes, playnite maximizes, game starts, only a minute is recorded. The strange thing is just now I started the game to check if ubisoftgamelauncher.exe is running (it is) and this time I didn't see the launcher popping up, launching the game took longer than usual but the time was recorded. 

I have uplay_r1_loader64.dll and uplay_r2_loader64.dll in the games /bin/win64 directory.

**Comment by Kinc4id** [comment]
Looks like this is only happening the first time I start the game after booting the PC. When I close the game and start it again it works as expected. Maybe that's because the second time I boot the game the launcher is already running?

**Comment by JosefNemec** [comment]
There have been some minor fixes for time tracking of Ubisoft games, but not much more I can do about it. Some Ubisoft games simply have stupid startup procedure and it's a nightmare to track them properly. It would basically require fine tuning tracking functionality per game and I just don't want to do that.

The other game having similar issue that Anno 1800 has is R6 Siege.
