### ISSUE TITLE
Not seen as running after launching exe files of EA's games

### ISSUE THREAD

**Issue by Bonk-Choy** [JosefNemec/PlayniteExtensions#173]
I understand that EA launcher is not supported for now, so I set the play action as just the exe file. But Playnite sees the game as already closed 1 second after launching.

This causes the scripts to run all at once, even though some are supposed to run after exiting the game.

Thanks

**Comment by JosefNemec** [comment]
It's because the original exe can sometimes shutdown and start different instance again depending on a game, nothing you can do about it. You can try switching different tracking mode, but that's about it.
