### ISSUE TITLE
GTA V on Epic keeps getting flagged as uninstalled, while it isn't.

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/PlayniteExtensions#182]
Extension name
Epic Store

Bug Description
GTA V on Epic keeps getting flagged as uninstalled, while it isn't.

To Reproduce
Install GTA V on Epic.
Updating the Epic game library causes GTA V to be marked as uninstalled.

Extensions log
I:\EPIC is my default install location for the Epic Launcher
GTA V is in stalled in I:\EPIC\GTAV
Extensions.log contains a path to P:\EPIC\GTAV (I use Playnite portable on drive P:)
I think I used to install Epic games in the P:\EPIC\ folder, but I changed that.

![image](https://user-images.githubusercontent.com/16439116/167707198-8eca2ef0-3cb8-496e-a43f-7e45620af143.png)

**Comment by JosefNemec** [comment]
This means that the path is wrong in Epic's config files.
- try reinstalling the game
- did you originally install the game there or moved it manually after initial install?

**Comment by woutercools** [comment]
> * did you originally install the game there or moved it manually after initial install?

I think so, yes!

What should I do?

**Comment by JosefNemec** [comment]
Fix those paths in `c:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests\`

**Comment by JosefNemec** [comment]
There are .item files in that folder, you need to figure out which one is GTA's and fix all paths in that file.

**Comment by woutercools** [comment]
> There are .item files in that folder, you need to figure out which one is GTA's and fix all paths in that file.

There was a second .item file for GTA V with the wrong path.
I deleted that file and it's fixed now.

Thanks!
