### ISSUE TITLE
Metadata sources / IGDB: show the number of reviews that the review score is based on

### ISSUE THREAD

**Issue by andrasfuchs** [JosefNemec/PlayniteExtensions#185]
**Describe the solution you'd like**
It is very useful already that we have the community and critic scores, but it would be even better to have the number of reviewers also displayed next to the actual number. Sometimes, if the number of reviews is low, the review score isn't really reliable.

IGDB has the number of reviewers on their website, so it's probably returned by their API as well. Ideally the community and critic score columns in Playnite would include the reviewer number too like "80 (316)".

It would be also great to have a filter for the reviewer number, so that games that have for example less than 100 reviews wouldn't be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/910321/170890226-de45b7f1-6707-4dfd-9f28-6ac1be10ed51.png)

**Comment by JosefNemec** [comment]
Not possible because Playnite doesn't provide field where IGDB plugin could store and display number of reviews.
