### ISSUE TITLE
Add new metadata source based on steamdb.info

### ISSUE THREAD

**Issue by andrasfuchs** [JosefNemec/PlayniteExtensions#186]
**Describe the solution you'd like**
It would be great to have steamdb.info as another metadata source, especially because they have a customized score for most of the games based on Steam reviews, the number of positive and negative reviews, and even the current number of players that are playing.

**Screenshots**
![image](https://user-images.githubusercontent.com/910321/170890479-8b8efeff-dce0-4459-b5a1-513b686503bd.png)

**Comment by JosefNemec** [comment]
1) Steam library plugin and Universal Steam metadata plugins already use their custom algorithm to calculate score.
2) It's not possible to show number of reviews because Playnite doesn't support that info as a game field.
