### ISSUE TITLE
Automatically update libraries

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/PlayniteExtensions#187]
Related to https://github.com/JosefNemec/Playnite/issues/2948
It would be nice if library integrations, where possible, would monitor the files that indicate which games are installed/uninstalled, like the manifest files in the Epic Games Launcher, and trigger library updates accordingly. This way, the installation status in Playnite gets updated while it is running, even if the game is (un)installed via the respective launcher directly (not via Playnite).

**Comment by JosefNemec** [comment]
The whole idea behind Playnite is that you will be using it as your main front end, including starting installations, so this is not necessary, in my opinion.

Plus running all these checks constantly is just a waste of resources, since 99% of the time you are not installing any games.

**Comment by felixkmh** [comment]
The use case I have in mind is that you buy a game through some launcher, install it directly in that launcher. In that case I wouldn't go to Playnite, update the library and then install it via Playnite. It would just be nice if Playnite picked up on that instantly (and I know pressing F5 is not a lot of work, but that updates all libraries, and is still an extra step). And do FileWatchers really use a lot of resources? I thought they were fairly efficient.

**Comment by JosefNemec** [comment]
It's not just file system events. Some plugins use registry data and events for those are only available via WMI, as far as know, and those require elevated rights. Plus some plugins need to fetch additional info from service API to detect what games are installed.

**Comment by felixkmh** [comment]
So for those that only rely on file system events, this would be feasable, right? And I don't mean that you need to watch for specific games to be installed or uninstalled, but if possible, just watch for changes that indicate that a game might be installed/uninstalled, and just trigger the affected library to update, just like it would if you triggered the update manually. Of course there would need to be some mechanism so that it isn't triggered over and over in a very short timespan.
