### ISSUE TITLE
Can't downlaod add-ons

### ISSUE THREAD

**Issue by 244671360** [JosefNemec/PlayniteExtensions#188]
**Describe the bug**
Once I download the add-ons, It shows "Failed to download add-on installation manifest. I reinstall the playnite but it still can't download.

**Screenshots**

![Snipaste_2022-06-11_14-35-36](https://user-images.githubusercontent.com/36124979/173176465-8037060a-24f8-42fa-9815-1a9ad5a5838d.png)

**Diagnostics ID**
c785c462-f0b5-4d38-b935-e74af3ab4756

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/PlayniteExtensions/issues/188

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/issues/2952
