### ISSUE TITLE
Links Opening in Library (i.e. Steam, Origin, etc.)

### ISSUE THREAD

**Issue by Droppisalt** [JosefNemec/PlayniteExtensions#19]
**Check for existing issue**
Haven't seen it discussed.

**Describe the solution you'd like**
I'm not sure if this would be possible to every available library, but I manually added "steam://openurl/" in front of my Steam links so that they open in my Steam app instead of the browser version. It would be great if this can be added automatically when a new game is imported. I imagine this can be done for the other stores as well but I'm not sure.

**Screenshots**
![image](https://user-images.githubusercontent.com/67336980/113481542-20a31380-9468-11eb-9045-eca201c84a13.png)

**Comment by JosefNemec** [comment]
I personally don't see how this is more useful then opening it in a browser. Especially since you can have extensions like Augmented Steam installed in a browser.

**Comment by Droppisalt** [comment]
I've never heard of Augmented Steam. Just had a look and it seems great. Might not need this with the extension installed. Thanks for the suggestion!
