### ISSUE TITLE
Steam library doesn't catch uninstalls of demos

### ISSUE THREAD

**Issue by jhallbachner** [JosefNemec/PlayniteExtensions#191]
**Describe the bug**
In the Steam library plugin, installed demos will be added to the library as locally-installed games. When they are uninstalled, the plugin will not update their status after explicitly calling a library refresh.

**To Reproduce**
1. Install a demo from Steam.
2. Trigger a Steam library update in Playnite. The demo will be added to the library and marked as installed.
3. Uninstall the demo using Steam.
4. Trigger another Steam library update.
5. The demo will still show as installed even though its local files have been removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/910695/174348283-4afaaff8-5f9c-4257-88fa-16c551651ebb.png)
![image](https://user-images.githubusercontent.com/910695/174348291-7279f5ae-38d5-4ed3-a055-a4a30130c2ef.png)
![image](https://user-images.githubusercontent.com/910695/174348270-6d5a5fb9-166b-4217-aed1-185a2c2e78df.png)
![image](https://user-images.githubusercontent.com/910695/174348404-60a8f02f-4f41-4bd2-bf2d-052a158364bb.png)
![image](https://user-images.githubusercontent.com/910695/174348445-7d700296-95ed-4f90-9f1b-b21bf927a0f3.png)

**Diagnostics ID**
bd6828bd-3f70-46a8-b821-0d74e9532376

**Comment by JosefNemec** [comment]
Demos are technically not part of your library once you install them so plugin can't set install type for them. And checking if an entry is a demo would slow down import process a lot.

**Comment by JosefNemec** [comment]
Closing per my comment here: https://github.com/JosefNemec/PlayniteExtensions/issues/200#issuecomment-1192341663
