### ISSUE TITLE
'bAllowMultipleInstances' error disallowing library import for Epic

### ISSUE THREAD

**Issue by ChillyEmber** [JosefNemec/PlayniteExtensions#192]
**Describe the bug**
_After attempting to refresh my library with the Epic Launcher installed, I noticed it errored out, however, after successfully authenticating, it still sends the error, however can and will pop my games up, however mark them as "uninstalled."_

**Screenshots**
![image](https://user-images.githubusercontent.com/25883402/174685184-b638752b-d898-4c7f-8b38-6c9fb8d0b44c.png)

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
_48bfda22-c389-4bb7-83c6-af6167208003_

**Comment by JosefNemec** [comment]
One or more files in `c:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests\` is damaged. Did you modify them manually by any chance?

I can only point specifically to an entry for `For The King` game, it has `,` missing on line 15. Which looks to me like something or somebody modified that file improperly.
