### ISSUE TITLE
Xbox Library not updating tracking time

### ISSUE THREAD

**Issue by ariesps** [JosefNemec/PlayniteExtensions#194]
**Describe the bug**
Once time is tracked, playing time is not updated. If you set playtime manually to zero, and force a update on Xbox Library it gets updated successfully.

**Comment by ariesps** [comment]
Diagnosis package id : 97e343f6-edaa-4e24-ac29-2b06ffcd592a

**Comment by JosefNemec** [comment]
You need to have an option to force play time sync enabled in Playnite's general settings. If some time is already present, Playnite by default doesn't download play time and relies on internal tracking instead.

**Comment by ariesps** [comment]
Sorry! My bad, didn't even know that option was there. Thanks!
