### ISSUE TITLE
Cannot authenticate with Amazon Games Extension from Canada region

### ISSUE THREAD

**Issue by aaronaheck** [JosefNemec/PlayniteExtensions#197]
Attempting to Authenticate with the Amazon Games extension.  Will not accept my Amazon Canada account [amazon.ca as opposed to amazon.com]. 

Login page URL used in the Amazon Games extension appears to be:
https://www.amazon.com/ap/signin?openid.ns=http://specs.openid.net/auth/2.0&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.oa2.scope=device_auth_access&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.response_type=token&openid.oa2.client_id=device:[REDACTED]&language=en_US&marketPlaceId=[REDACTED]&openid.return_to=https://www.amazon.com&openid.pape.max_auth_age=0&openid.assoc_handle=amzn_sonic_games_launcher&pageId=amzn_sonic_games_launcher

If at all helpful, when I open an incognito browser and click the Sign-In button on the Amazon Games URL at:
https://gaming.amazon.com

I am then taken to the following URL for login:
https://www.amazon.ca/ap/signin?openid.pape.max_auth_age=3600&openid.return_to=https%3A%2F%2Fgaming.amazon.ca%2Fprime%2Fusamazonlogin%2Fca%3Fconfirm%3DALWAYS%26returnUri%3Dhttps%253A%252F%252Famazon.com%252Fap%252Fsignin%253Fopenid.pape.max_auth_age%253D3600%2526openid.return_to%253Dhttps%25253A%25252F%25252Fgaming.amazon.com%25252F%25253FsignedIn%25253Dtrue%2526openid.identity%253Dhttp%25253A%25252F%25252Fspecs.openid.net%25252Fauth%25252F2.0%25252Fidentifier_select%2526openid.assoc_handle%253Damzn_respawn_desktop_us%2526openid.mode%253Dcheckid_setup%2526openid.claimed_id%253Dhttp%25253A%25252F%25252Fspecs.openid.net%25252Fauth%25252F2.0%25252Fidentifier_select%2526openid.ns%253Dhttp%25253A%25252F%25252Fspecs.openid.net%25252Fauth%25252F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_respawn_desktop_ca&openid.mode=checkid_setup&language=en_US&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_gaming_prime&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&ssoResponse=[REDACTED]

This occurs in an incognito window, so it appears that Amazon is doing a region check and then directing me to the Canada sign-in page.

**Comment by SemperRoto** [comment]
I have the same problem with my German Amazon account. After the login I just get sent to the amazon landing page and my account isn't authenticated.
