### ISSUE TITLE
Automate Steam game installation

### ISSUE THREAD

**Issue by ozboss** [JosefNemec/PlayniteExtensions#199]
**Check for existing issue**
Nothing found.

**Describe the solution you'd like**
Currently when installing a Steam game through Playnite it launches Steams installation dialog, which breaks gamepad support. Through [SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD) it is possible to automate this process. It also reports back the status, so it would be possible to display the current progress in Playnite. This could be integrated into the UI so that it can be controlled with a gamepad.

**Screenshots**
![image](https://user-images.githubusercontent.com/32305849/179342119-cd9468c0-490f-451d-a789-fb09afd66cc6.png)

**Comment by JosefNemec** [comment]
As stated on the wiki:
>  Its primary use is to install and update various dedicated servers available on Steam using a command-line interface.

So not really designed for end user game installations, therefore closing.
