### ISSUE TITLE
Xbox (console) Library does not allow updates to 1) installation path & 2) installed flag

### ISSUE THREAD

**Issue by dannongruver** [JosefNemec/PlayniteExtensions#201]
I'd like to be able to click on "Play" action from xbox games but since it's always "uninstalled", Playnite expects installation first. The problem is that marking xbox games installed.
 
After editing an Xbox console game's installation path/flag, the path and flag are reset to blank/false again. I've reproduced this manually and programmatically. I've gone as far as creating a powershell extension to update the game paths which works for other game libraries but not Xbox. 

I'm on windows 11 and there seems to be code in xbox extension that depends on windows "10" but I'm not sure that's related.

**Comment by JosefNemec** [comment]
Playnite 10 will add an option to overwrite installation status set by library plugins.
