### ISSUE TITLE
Library Addons with Multiple accounts: Save the origin of library to help track whose account the game belongs to

### ISSUE THREAD

**Issue by kongomongo** [JosefNemec/PlayniteExtensions#203]
**Check for existing issue**
nothing found.

**Describe the solution you'd like**
Now with https://github.com/JosefNemec/PlayniteExtensions/issues/21 implemented I tried it out and it worked nicely. The only problem I know have is that Playnite does not seem to track which account the imported game belongs to. Would it make sense to save that in a db field so it would be easier for the end user to find out which account to use to be able to play the game? I would suggest a field that can be shown in the main ui table. Could even make it into scripts to launch/login the appropriate user account before launching the game.

**Screenshots**
None.

**Comment by kongomongo** [comment]
After having a quick glimpse at the source code it seems that currently only the sourceId is saved for each game and this seems to be one id per Library Addon. So all Steam API keys get lumped together into one sourceId. Is that assumption correct?

I haven't dived deeper in, but I think there is another location within the Steam Library Addon that differentiates between the Accounts and displays the human readable account names.

**Comment by JosefNemec** [comment]
Will be done via  #291
