### ISSUE TITLE
"Start Xbox Pass app instead of Microsoft Store when opening client" option not working

### ISSUE THREAD

**Issue by dGstone18** [JosefNemec/PlayniteExtensions#204]
**Check for existing issue**
Previously closed issue here: https://github.com/JosefNemec/PlayniteExtensions/issues/155

**Describe the bug**
The Microsoft store opens after the "Start Xbox Pass app instead of Microsoft Store when opening client" option is enabled rather than the Xbox app.

**To Reproduce**
Enable the option, attempt to install game pass game.

**Diagnostics ID**
0e60cf20-eabc-442b-ab68-fa9e96b99fcb

**Comment by JosefNemec** [comment]
This is only for when you open the client via tray icon or main menu. Installing will always use MS Store, because it's currently not possible to start install directly in Xbox App.
