### ISSUE TITLE
"Failed To Authenticate User" (Epic Games)

### ISSUE THREAD

**Issue by samkitty** [JosefNemec/PlayniteExtensions#207]
I know this is a duplicate issue, but the fix for the previous ones has always been an update to Playnite and I'm on latest version.

The app is unable to authenticate user with the Epic Games integration plugin. the login process looks normal, I only get the error "Failed To Authenticate User" as soon as login is successful. (no delay, so not timing out.)

I tried on two separate PCs and Epic accounts with the same problem (both on the same network, although firewall and antivirus are fully disabled.)

Downgrading to older builds of Playnite didn't fix the issue.

Here's my diag-pack ID: 56ae7a37-0282-4b2b-9bf1-2c41d82a8948

**Comment by XenorPLxx** [comment]
Seems to be affecting more people https://www.reddit.com/r/playnite/comments/x2ex2j/unable_to_authenticate_epic_games/ with some logs pasted here: https://www.reddit.com/r/playnite/comments/x2ex2j/comment/imk3i1j/?utm_source=share&utm_medium=web2x&context=3.

**Comment by radioBrando** [comment]
Based on my Log file, it looks like the coding is referencing a directory I do not have mapped on my machine (E:).
However, this could just be how the dev writes the debug line to the console.
Only person who can verify this is the Dev themselves.

From my Log:
"31-08 14:23:01.727|DEBUG|EpicLibrary#EpicLibrary:Found 13 installed Epic games.
31-08 14:23:01.838|ERROR|EpicLibrary#EpicLibrary:Failed to import linked account Epic games details.
System.Exception: User is not authenticated.
   at EpicLibrary.Services.EpicAccountClient.GetAssets() in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\Services\EpicAccountClient.cs:line 194
   at EpicLibrary.EpicLibrary.GetLibraryGames(CancellationToken cancelToken) in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\EpicLibrary.cs:line 94
   at EpicLibrary.EpicLibrary.GetGames(LibraryGetGamesArgs args) in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\EpicLibrary.cs:line 160"

**Comment by KrisEnigma** [comment]
Same problem here.

**Comment by JosefNemec** [comment]
Epic changed something and authentication process needs to be updated.

**Comment by fthdgn** [comment]
https://github.com/JosefNemec/PlayniteExtensions/blob/master/source/Libraries/EpicLibrary/Services/EpicAccountClient.cs#L354

On my case, after login, the request on this line fails. 
The response is
{"errorCode":"errors.com.epicgames.unauthorized","message":"You are not authenticated. Please authenticate.","correlationId": <some uuid strign>}

**Comment by TinyHero13** [comment]
I'm having the same problem.

**Comment by itguy327** [comment]
same issue

**Comment by WingedAsarath** [comment]
I'm having the same issue here with a brand new Epic account. I tried email and password (as that's how I made the account) plus I went and linked it to my Xbox account and tried to authenticate that way. Every time I get "Failed to authenticate user". Can confirm the password etc. is correct as I'm pulling it directly from my password manager. Screenshot attached.

![image](https://user-images.githubusercontent.com/61755582/188270189-efafa58d-b9c8-4b73-b7ac-5e78d5721e14.png)

**Comment by luxzg** [comment]
Same issue. Updated Playnite, updated add-ons, updated Epic client, I can login successfully with same login data in Epic app, and through web browser, but not through Playnite add-on. Tried multiple times and so on. Like others said, login process seems ok inside the browser pop-up window, but once that closes we get the error as above.

From extensions.log

`03-09 16:37:53.702|ERROR|EpicLibrary#EpicLibrarySettingsViewModel:Failed to authenticate user.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EpicLibrary.Services.EpicAccountClient.getExcahngeToken(String sid) in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\Services\EpicAccountClient.cs:line 356
   at EpicLibrary.Services.EpicAccountClient.Login() in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\Services\EpicAccountClient.cs:line 128
   at EpicLibrary.EpicLibrarySettingsViewModel.Login() in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\EpicLibrarySettingsViewModel.cs:line 73
`

**Comment by JosefNemec** [comment]
Fixed in 2.12
