### ISSUE TITLE
Epic & IGDB metadata mismatch

### ISSUE THREAD

**Issue by liranbr** [JosefNemec/PlayniteExtensions#209]
In some games from the Epic integration, there are metadata mismatches, both in fields that I have set to IGDB, and in those set to Official Store,IGDB

For example, [in these two the name is correct](https://imgur.com/a/YSWiqdD), the rest is entirely or partially mismatched

When using Download Metadata from Epic, it fixes some fields, but seems to lack other fields, and those others are still mismatched.
If I Download Metadata from IGDB, and select the edition, everything is correct. None of the editions in IGDB return the mismatched Batman media, so I don't know where it actually came from

Diagnostics ID: db6a3410-88ce-41ab-b6c6-aa0983e4da72

**Comment by darktorres** [comment]
I have the same problem but not only with Epic. Disabling the "IGDB metadata provider" plugin makes the match work.
I enabled trace log option in the files below. I can provide other logs if needed.


![before_after](https://user-images.githubusercontent.com/5768540/202307386-8beb4c84-1c87-4b96-a08b-58859cb73a55.png)

[playnite.log](https://github.com/JosefNemec/PlayniteExtensions/files/10026153/playnite.log)

[extensions.log](https://github.com/JosefNemec/PlayniteExtensions/files/10026150/extensions.log)

**Comment by JosefNemec** [comment]
Fixed on the backend.
