### ISSUE TITLE
steam extension error

### ISSUE THREAD

**Issue by freesoftwarerocks** [JosefNemec/PlayniteExtensions#211]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

![image](https://user-images.githubusercontent.com/114490042/192523446-97804dd7-be05-4c0e-8a6a-abf9d0d3aabd.png)

[serr.zip](https://github.com/JosefNemec/PlayniteExtensions/files/9655642/serr.zip)

**Comment by JosefNemec** [comment]
It's the issue with your Steam install. I made a change that will prevent Playnite from crashing completely, but Steam friends window will not open anyways because system can't find Steam executable when opening `steam://open/friends`.
