### ISSUE TITLE
Do not include hidden games on Steam #214

### ISSUE THREAD

**Issue by elyashivhazan** [JosefNemec/PlayniteExtensions#215]
Hi, I have some games son Steam that I made hidden (e.g gta v and nms) because I have them on Rockstar and GOG. Is it manageable to do it like the GOG extinction?

**Comment by JosefNemec** [comment]
Open Steam integration settings, go to Advanced tab and use "Import Steam categories", it imports hidden status as well.

Alternatively you can remove these games completely manually and add them to ignore list if you don't want them in Playnite at all.
