### ISSUE TITLE
Issue with ubisoft connect

### ISSUE THREAD

**Issue by Nightchanger** [JosefNemec/PlayniteExtensions#216]
This comes out when updating my ubisoft connect with playnite. Trying to know what's going on.
![image](https://user-images.githubusercontent.com/45158783/195451433-c8f501a0-06ae-4c81-83f3-5ba4080cdc8c.png)

**Comment by JosefNemec** [comment]
Please attach diagnostics ID requested in issue template.

**Comment by Nightchanger** [comment]
e3afcb47-6762-4b72-8dea-5446b5fb211d

**Comment by JosefNemec** [comment]
Thank you, can you please attach `c:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\cache\configuration\configurations` file?

**Comment by Nightchanger** [comment]
Changed the file type to .txt due to github not letting it upload. It's in a portable HDD, just letting you know.
[configurations.txt](https://github.com/JosefNemec/PlayniteExtensions/files/9769258/configurations.txt)

**Comment by JosefNemec** [comment]
The file you attached is completely empty. So either Ubisoft Connect failed to put account information there or something else went wrong. I'll add a check for this case so we don't show current cryptic error message, but the root cause is not in Ubisoft plugin.

**Comment by Nightchanger** [comment]
I run a `sfc /scannow` in the command prompt and restarted. Seems to have done the trick.
If there's a way to take out a log file from the issue I'd like to know.
