### ISSUE TITLE
Playnite does not detect Final Fantasy 14 Free Trial on Steam

### ISSUE THREAD

**Issue by Prelaps** [JosefNemec/PlayniteExtensions#218]
### Bug Description

As the title states, Playnite imported all my installed games except for FF14 Trial version.

It was previously working until I reinstalled windows and on my new setup it no longer imports FF14 into my playnite library.

### To Reproduce

1. Download the FF14 free trial [here](https://store.steampowered.com/agecheck/app/312060/)
2. Connect steam account to playnite
3. Import games

### Diagnostics ID

ac038ae5-ebce-4408-8041-21407cc3f903

### Screenshots

![image](https://user-images.githubusercontent.com/17280314/195717641-0aa8d6df-d0f5-467d-b5bf-8693b54ca43b.png)
****
![image](https://user-images.githubusercontent.com/17280314/195717706-5fa00f07-206b-4c38-8334-91969c0b5cdb.png)

**Comment by cheble** [comment]
The workaround described here fixed this for me: https://github.com/JosefNemec/PlayniteExtensions/issues/200#issuecomment-1192341663

It did add two entries to my library though (`FINAL FANTASY XIV Online` and `FINAL FANTASY XIV Online Free Trial`).

**Comment by Prelaps** [comment]
Sweet, that seems to have worked and it added both entries for me as well. Doesn't seem like the ideal solution for those that don't want games from other accounts but also want these entries to show up but it'll do for now.

**Comment by JosefNemec** [comment]
Closing per my comment here: https://github.com/JosefNemec/PlayniteExtensions/issues/200#issuecomment-1192341663
