### ISSUE TITLE
Say no to an update to avoid startup harassment

### ISSUE THREAD

**Issue by VirgileVILE** [JosefNemec/PlayniteExtensions#219]
This seems obvious to me since in cases like the upgrade from Origin to EA, which I refuse every time because I stay on the origin client, while playnite pesters me with the notification of this update at every startup...

**Comment by JosefNemec** [comment]
settings -> updating -> change update check frequency

**Comment by VirgileVILE** [comment]
> settings -> updating -> change update check frequency
Hmm ... Temporary solution, knowing that it penalizes any type of update.
