### ISSUE TITLE
The game Grim Dawn (GOG edition) fails to load when launched from Playnite; it does however run fine if the executable is ran directly & Playnite is still running.

### ISSUE THREAD

**Issue by JunglePredator** [JosefNemec/PlayniteExtensions#220]
**Check for existing issue**
Key words Grim Dawn not found.

**Describe the bug**
Grim Dawn (GOG edition) fails to launch when attempting to run it from Playnite. 
Reply from Crow on discord:
"It's controlled by GOG integration plugin, not by Playnite itself. "

GOG info files were requested but Github kept erroring so below are the files inline:

-----------------------------------------------------------------------

{
    "buildId": "55560702867701268",
    "clientId": "48642419211000431",
    "gameId": "1449651388",
    "language": "English",
    "languages": [
        "en-US"
    ],
    "name": "Grim Dawn",
    "osBitness": [
        "64"
    ],
    "playTasks": [
        {
            "category": "game",
            "isPrimary": true,
            "languages": [
                "en-US"
            ],
            "name": "Grim Dawn",
            "osBitness": [
                "64"
            ],
            "path": "x64/Grim Dawn.exe",
            "type": "FileTask"
        },
        {
            "category": "game",
            "languages": [
                "en-US"
            ],
            "name": "Grim Dawn 32-bit",
            "osBitness": [
                "64"
            ],
            "path": "Grim Dawn.exe",
            "type": "FileTask"
        }
    ],
    "rootGameId": "1449651388",
    "version": 1
}

-----------------------------------------------------------------------

{
    "clientId": "48642419211000431",
    "gameId": "1457447089",
    "language": "English",
    "languages": [
        "en-US"
    ],
    "name": "Grim Dawn - Patron Package",
    "osBitness": [
        "64"
    ],
    "playTasks": [],
    "rootGameId": "1449651388",
    "version": 1
}

-----------------------------------------------------------------------

{
    "buildId": "53156485360636135",
    "clientId": "48642419211000431",
    "gameId": "1536648751",
    "language": "English",
    "languages": [
        "en-US"
    ],
    "name": "Grim Dawn - Ashes of Malmouth",
    "playTasks": [],
    "rootGameId": "1449651388",
    "version": 1
}

-----------------------------------------------------------------------

{
    "clientId": "48642419211000431",
    "gameId": "1812959072",
    "language": "English",
    "languages": [
        "en-US"
    ],
    "name": "Grim Dawn - Crucible",
    "playTasks": [],
    "rootGameId": "1449651388",
    "version": 1
}

-----------------------------------------------------------------------

{
    "buildId": "53156485360636135",
    "clientId": "48642419211000431",
    "gameId": "2004748256",
    "language": "English",
    "languages": [
        "en-US"
    ],
    "name": "Grim Dawn - Forgotten Gods",
    "playTasks": [],
    "rootGameId": "1449651388",
    "version": 1
}

**Comment by JosefNemec** [comment]
Please go to "About Playnite" menu and generate diagnostics package, thanks.
