### ISSUE TITLE
Option to download highest quality wide banners from GOG

### ISSUE THREAD

**Issue by TheRealFlamepanther** [JosefNemec/PlayniteExtensions#223]
GOG has 1600x740 banners in PNG format for all games. These can be located by taking the URL for any horizontal GOG banner, removing the first underscore and anything after it, and adding ".png" to the end.
E.g.:
https://images.gog-statics.com/86021784ec0e8e811590312c8d1d1d387094ec7b5559262fc3a0621a428efb58_product_tile_extended_432x243_2x.webp
becomes:
https://images.gog-statics.com/86021784ec0e8e811590312c8d1d1d387094ec7b5559262fc3a0621a428efb58.png

In GOG library plugin metadata options, add an setting to use these when downloading horizontal covers. Users can then utilize other existing plugins to resize these, if desired.

**Comment by JosefNemec** [comment]
Not planned since general move is to use vertical ones which was added via c7312af4f1add221853e8339e981e2f41fdc1d5f to be more inline with other metadata sources/stores with mostly use vertical covers.
