### ISSUE TITLE
Xbox authentication not possible

### ISSUE THREAD

**Issue by Quayyy** [JosefNemec/PlayniteExtensions#226]
When clicking the authenticate button in the settings, the window opens up for a split second, but closes right after. It does still say "Requires authentication" after that. RInse and repeat

I did try to clear the data-folder of the plugin, also tried de- and reinstalling it, without any change in behaviour

**Comment by JosefNemec** [comment]
Try going to Playnite's settings -> Advanced section and use `Clear web cache` button.

**Comment by Quayyy** [comment]
Okay, now I can put in my login credentials again. But as soon as I put them in, the window closes (normally) , but it still says "Requires authentication" , and then it goes back to the state before

**Comment by Quayyy** [comment]
It did work today, so I guess that fixed it?
Thanks for the troubleshoot.
