### ISSUE TITLE
[uplay] Allow install/configurations file location override

### ISSUE THREAD

**Issue by Belgabor** [JosefNemec/PlayniteExtensions#227]
The current detection method for the uplay / ubisoft connect app doesn't work for alternate install methods such as scoop. I suggest adding a config option to override / manually set the uplay install location (or the location of the configurations file).

**Comment by JosefNemec** [comment]
The path is taken from registry keys that Ubisoft Connect creates during installation, it is not hard coded. If it doesn't work with scoop, then scoop doesn't install Ubisoft Connect correctly.

**Comment by Belgabor** [comment]
Well, that's a matter of debate. I would argue it's correctly installed as portable, aka without adding it to Windows' installed program list.
The path itself isn't hardcoded, true. I was expressing that incorrectly. What I meant to say is the way to determine the path is hardcoded to it being installed globally.

**Comment by JosefNemec** [comment]
Closing, I don't want to spend time dealing with unofficial launcher installations since they could lead to other issues and I don't want to waste time diagnosing those.

If you want support for this, you will need to make plugin fork.
