### ISSUE TITLE
Uninstalled Epic Games are not showing up in the Libary. 

### ISSUE THREAD

**Issue by spj2401Dev** [JosefNemec/PlayniteExtensions#230]
**Describe the bug**
Games from the Epic Games Launcher that are not installed on my PC, do not show up in my Planite libarry, exept Fornite. I have Linked my Epic account to Playnite and I have refreshed my libarry and checked if I have ignored games. 

**To Reproduce**
Not clear yet.

**Diagnostics ID**
504cb272-1dc8-4430-a2e9-40bee2ad585f
[extensions.log](https://github.com/JosefNemec/PlayniteExtensions/files/9945904/extensions.log)

**Comment by JosefNemec** [comment]
I can't reproduce it and I don't see any errors in logs related to Epic import, so no idea what the issue might be. I see total of 6 games from Epic plugin imported according to logs.
