### ISSUE TITLE
Playtime not being synced from Steam (and maybe other extensions)

### ISSUE THREAD

**Issue by HotWinterDays** [JosefNemec/PlayniteExtensions#231]
**Describe the bug**
I noticed my playtime from Steam was no longer syncing/updating in Playnite.

I have it installed in Portable mode.

I checked all the settings:
- General>Import playtime of games in library = Always
- Made sure my Steam is public
- Used my API Key
- Added my Steam ID and API Key as an "Additional Account" in the integration and checked Import play time
- Steam Library integration>Advanced>Import Steam Last Played says "Import completed successfully" but nothing happens/changes in the Playnite library

I have even fully reinstalled Playnite to test if something was wrong with my existing config.

**To Reproduce**
Play a game through Steam, refresh Playnite, nothing will update.

Play a game through Playnite and it will update and track.

The only way to update a games playtime is to remove a game from Steam and it will add it on next update but will not update playtime beyond that unless you launch exclusively through Playnite.

**Screenshots**
![General>Import playtime of games in library = Always](https://user-images.githubusercontent.com/12052200/201487609-c27df610-4f76-4119-90a7-7e297f6f2888.png)
![image](https://user-images.githubusercontent.com/12052200/201487643-dd63deba-3d08-474f-8279-3b5246218847.png)
![image](https://user-images.githubusercontent.com/12052200/201487592-10e84024-5f4a-4e16-bdb4-645cb9e34db7.png)

**Diagnostics ID**
243caaa1-972c-4ba8-b797-cf784b063fbd

**Comment by JosefNemec** [comment]
It's because you have import of uninstalled games disabled. Play time data are only available in API endpoint we use for import of uninstalled games.

However, we should definitely fetch Playnite if account is connected even if import of uninstalled games is disabled, I'll fix that in the next update.

**Comment by JosefNemec** [comment]
Ignore my previous comment. I retested it and it works properly even with import of uninstalled games disabled, it will just only update play time of games that are currently installed, which makes sense.

Please download [this debug build](http://playnite.link/download/TimeImportTest.zip) of Playnite, replicate the issue with it and then generate new diag. package. Also mention what games you used to test the issue.

**Comment by JosefNemec** [comment]
One last thing since you have additional account specified. If your main linked account and some additional one both contain the same game, play time will be imported from the main account only.

**Comment by HotWinterDays** [comment]
I downloaded the debug build and replicated the issue with Noita and Bloons TD6 as shown in the images below.
Diag: 15c7feef-4cd1-4655-9a83-7bb87a9c7dde

Steam:
![image](https://user-images.githubusercontent.com/12052200/202085774-25bab5ab-8137-42a7-bb84-194706d0d242.png)

Playnite after full library update, restarting, and so on:
![image](https://user-images.githubusercontent.com/12052200/202085816-30bd842b-db2a-4009-bbae-91d35a1b602e.png)

**Comment by JosefNemec** [comment]
Is this issue about last activity sorting and not the actual play time?

**Comment by JosefNemec** [comment]
Last activity is not being updated the same way as play time (for various reasons it's only updated if there's no date set already in Playnite) and from the logs it looks to work correctly, also play time is being update correctly.

**Comment by JosefNemec** [comment]
I'll try to figure out why import of last activity is being treated differently (I vaguely remember some issues with it from the past) and change it to behave the same way as import of play time. But that needs to be done in Playnite itself, not in extensions so I'm closing this.

**Comment by HotWinterDays** [comment]
I see my mistake for conflating to two. Should I open a issue for `Last Played` not being updated?

**Comment by JosefNemec** [comment]
You don't have to.
