### ISSUE TITLE
Epic Games import stopped working?

### ISSUE THREAD

**Issue by lef-est** [JosefNemec/PlayniteExtensions#235]
### Bug Description

0. I had the Epic launcher installed. The Epic plugin in Playnite is updated to the latest version. I am authenticated in this plugin. 
1. I claimed https://store.epicgames.com/en-US/p/star-wars-squadrons today and tried to import it into Playnite. No new game was added after the "Library update finished!" message. 
2. I tried again several hours later and it still did not work.

### Diagnostics ID

3f565ab3-b7c8-4107-b315-56492ceeecd6

### Others
This plugin worked before as shown here:
![image](https://user-images.githubusercontent.com/9643637/204008248-29d0a6ef-745b-4b07-8e57-e2925555fa01.png)

I am confident the imports I tried today did nothing, because I checked to confirm that no copies of "Star Wars: Squadrons" exist in any source or library.

**Comment by JosefNemec** [comment]
I looked into it and realized that this is intentional since the game is registering/launching via Origin/EA app anyways. So it should be imported via Origin/EA plugin (you might just need to launch the game at least once to get it linked to your EA account). The same applies to other EA games on Epic, like Battlefront 2.

**Comment by lef-est** [comment]
I see, thanks!

**Comment by Brandon1212b** [comment]
> I looked into it and realized that this is intentional since the game is registering/launching via Origin/EA app anyways. So it should be imported via Origin/EA plugin (you might just need to launch the game at least once to get it linked to your EA account). The same applies to other EA games on Epic, like Battlefront 2.

Reopening this issue. I read the troubleshoot https://github.com/JosefNemec/PlayniteExtensions/wiki/Epic-Game-Store-troubleshooting and your comment saying you have to start the game at least once to get it linked to your EA account.

This did not work. I tried launching FC24 from both epic and EA launchers but it will not show up on playnite.

1. updating playnite game 
2. library does not work
3. reinstalling the game does not work
4. waiting 24 hours after starting the game for it to show on playnite does not work

**Comment by Brandon1212b** [comment]
@JosefNemec
