### ISSUE TITLE
Epic Plugin - Incorrect Response after Login

### ISSUE THREAD

**Issue by pikachu01** [JosefNemec/PlayniteExtensions#237]
**Check for existing issue**
Only seen this in Discord server, but no resolution:
https://discordapp.com/channels/365863063296933888/808419165311467630/1046183596811096215

**Describe the bug**
After captcha is done, login will respond with "Incorrect Response. Please refresh the page." 

**To Reproduce**
Click Authenticate button, login using correct username and password. Solve captcha.

**Screenshots**
![image](https://user-images.githubusercontent.com/1090194/205541259-d2551caa-f2f4-400b-bef7-ea76cc1651df.png)

**Diagnostics ID**
3117f653-3cd8-4eb8-83ca-14cbf1304a99

**Comment by JosefNemec** [comment]
Can you test it with [this version](https://github.com/JosefNemec/PlayniteExtensions/files/10152817/EpicGamesLibrary_Builtin_2_15.zip) of Epic plugin?

(unzip and then run the pext file to install it)

**Comment by pikachu01** [comment]
It's working! Thank you for the quick resolution. :D
