### ISSUE TITLE
Have Favorites act like a category

### ISSUE THREAD

**Issue by hyoretsu** [JosefNemec/PlayniteExtensions#239]
Reasoning: we can group games by category, but Favorite doesn't get grouped like the rest. And it'd be pointless to simply create a "Favorite" category. (Also it wouldn't be at the top like Steam, but that's a minor priority)
![image](https://user-images.githubusercontent.com/20804322/206203791-7f863523-eeae-4f31-9955-652c50fec238.png)

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/issues/207
