### ISSUE TITLE
Only partial https when GOG (extension) downloads game info (api.gog.com) and pictures (gog-statistics.com)  

### ISSUE THREAD

**Issue by Crwmy** [JosefNemec/PlayniteExtensions#241]
After @JosefNemec closed JosefNemec/Playnite#2901 I looked into my playnite.log and extensions.log just to check if everything is also still working on my new set up PC and there aren't any quirks.

In the playnite.log I found
`Downloader:Downloading data from http://images-1.gog-statics.com/[PictureID].png`
Interestingly only PNGs downloaded via http. JPGs use https. Which is weird. 

In the extensions.log I found 
`GogLibrary#Downloader:Downloading string content from http://api.gog.com/products/[GameID]`
(which probably gets redirected and upgraded to https://www.gog.com/game/ if I interpret the log correctly. I have made a pull request to update the GOG API Base URL to use encryption.

**Comment by JosefNemec** [comment]
Fixed by 5895dad12116b461cb1884a7eed6acf1ceeaad28
