### ISSUE TITLE
Support for more than 1 Account on a Platform

### ISSUE THREAD

**Issue by CoolerWuffi** [JosefNemec/PlayniteExtensions#243]
Hi,
i resently discovert this project and i wanted to ask if you can add support for more than one account on a platform in my case ea (origen) .

I have 2 Ea accouts and on both are games so my idear woud be that you can set it up that one game starts with one ea account and the other with the ohter one. I head the idear of an script that will need your email and password to llog into your account.
I have no idear how to do it with 2fa but i hope anyone has one

**Screenshots**
no avalible

**Comment by dzkm** [comment]
For now, you could use [TcNo Account Switcher](https://github.com/TcNobo/TcNo-Acc-Switcher) for switching between accounts before playing a game. This sadly adds one more step before playing a game, but it is faster than using EA's client to do it. Possibly you could integrate the account switcher to the actions of your games or before execution scripts. 

P.S.: This is a temporary workaround.

**Comment by laurorual** [comment]
> For now, you could use [TcNo Account Switcher](https://github.com/TcNobo/TcNo-Acc-Switcher) for switching between accounts before playing a game. This sadly adds one more step before playing a game, but it is faster than using EA's client to do it. Possibly you could integrate the account switcher to the actions of your games or before execution scripts.
> 
> P.S.: This is a temporary workaround.

how about import games from another account? is there a workaround for that?
i have 2 accounts with Amazon games and i would like to have games from both on Playnite

**Comment by JosefNemec** [comment]
You can import games from one account, then re-authenticate under another one and import games from it. You'll end up with games from both accounts in your library.

I'm going to close this because it's virtually impossible to implement this reliably for majority integrations. Especially when it then comes to launching games under specific account.
