### ISSUE TITLE
Epic Games: Disable Download Metadata > Official Store menu

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/PlayniteExtensions#244]
Currently, the Epic Games metadata download doesn't work (forgot the details). However, 'Official Store' is still available in download metadata menu, leading to a lot of misclicks. 

Is it technically feasible to hide the menu item?

**Comment by JosefNemec** [comment]
We can't hide this from the plugin itself it requires support from Playnite itself. Will be done in Playnite 11.
