### ISSUE TITLE
Steam library integration doesn't import a machine for pigs

### ISSUE THREAD

**Issue by Nightchanger** [JosefNemec/PlayniteExtensions#245]
The game **Amnesia : a machine for pigs** isn't imported to the library from steam.

**Screenshots**
Steam library game missing in playnite
![image](https://user-images.githubusercontent.com/45158783/210158148-a8d85eea-a735-4e6f-8e31-15db205680a5.png)

Available on steam
![image](https://user-images.githubusercontent.com/45158783/210158159-9949d10c-f90d-437c-a7dd-6150c09c14d3.png)

**Comment by JosefNemec** [comment]
Does it happen in safe mode (restart to safe mode from help menu). Is the game hidden by any chance on on import ignore list (can check in settings)? Where is diagnostics package requested in issue template?
