### ISSUE TITLE
itch.io not importing games in bundle now

### ISSUE THREAD

**Issue by EclaTriomphe** [JosefNemec/PlayniteExtensions#246]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

No, there isn't.

**Describe the bug**

If you go to https://itch.io/my-purchases , you can see 3 sections above;[Bought, claimed & gifts](https://itch.io/my-purchases);[Bundles](https://itch.io/my-purchases/bundles);[Donations](https://itch.io/my-purchases/donations) and my bundle games are not being imported now. I think playnite imports only the first one? I think it should be checked !

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

Buy a bundle, maybe? My one is [Bundle for Ukraine](https://itch.io/b/1316/bundle-for-ukraine) but it's not available now so you might find another one...

**Screenshots**

I can't find how to put my photos in this page T.T

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

567d036c-c9a6-49ad-8094-28cf2415b2f2

**Comment by JosefNemec** [comment]
You need to claim games from those bundles first, they are not linked to your account until you do so. It's made that way by design by itch.

**Comment by EclaTriomphe** [comment]
Oh I had to click "download" buttons of each title first and register them in my "LIBRARY" ...
Very confusing system and wording... Why don't they use the term "activate" or "claim" ...
Anyway, thank you JosefNemec. Hope I'd not bothered you too much. Sorry and Thank you!
