### ISSUE TITLE
Keeps showing Uplay games as running when bought in Steam

### ISSUE THREAD

**Issue by ezeholz** [JosefNemec/PlayniteExtensions#251]
**Describe the bug**
After playing a game from Ubisoft but bought in Steam, Playnite keeps stating that you're playing the game. In consequence, the uplay client never closes. Seems to be anything about detections, refering to this issue.
https://github.com/JosefNemec/Playnite/issues/1073#issuecomment-476266552

**To Reproduce**
- Start a game bought in Steam, but that belongs to Ubisoft, I choose Rainbow Six because it's the one making troubles in my use case.
- When arrived to the main menu, close the game.
- Steam it's gonna show that the game it's efectively closed, but Playnite it's gonna still showing the game as Running.

**Screenshots**
![image](https://user-images.githubusercontent.com/30635862/213927943-1702e703-24e1-4e47-a7d3-5071257e54b6.png)

**Diagnostics ID**
86d3cf8c-1766-4b63-ab77-8505e0d11592

**Comment by ezeholz** [comment]
I saw the update released a few hours ago, but in my tests with that version I'm having the exact opposite of what we saw above. When I start the game, playnite shows it as Running for a few seconds, and then inmediately changes to "Play" status.

![image](https://user-images.githubusercontent.com/30635862/223314850-6011069d-b2a2-47cf-9f7a-7bfecccf1abc.png)

Diagnostics ID
9fa360e0-8acd-42bd-91e6-f9cbd7282639

**Comment by JosefNemec** [comment]
The fix was for Ubisoft Connect version, not Steam one (meaning game being launched via Ubisoft integration). Fix for Steam is unlikely going to happen because it would involve making completely custom tracking code just for Siege's Steam version. It's because of how weird Siege's startup procedure is.

I recommend switching to Ubisoft connect version (if it's possible, I haven't checked) if you want tracking to be reliable for this game.

**Comment by JosefNemec** [comment]
Yeah I think the only way would be unlinking Steam account form Ubi launcher, then you should in theory get native Ubi version. But I haven't tried it.

**Comment by JosefNemec** [comment]
Closing, the amount of effort to fix this for one specific game is just not worth it. It would require completely separate tracking implementation just for Siege.
