### ISSUE TITLE
Support for Steam banned games

### ISSUE THREAD

**Issue by r6d2** [JosefNemec/PlayniteExtensions#252]
I've noticed that Playnite does not detect or import Steam banned games, even if they are installed. This may be related to the usage of Steam API (see this [source](https://steam-tracker.com/apps/banned)) as the main origin for owned titles.

GOG Galaxy does not pose this problem. They are probably using some supplementary way to detect owned games, like each user's [Dynamic userdata](https://store.steampowered.com/dynamicstore/userdata/).

I'd like for Playnite to allow for an option in Steam Library plugin that allows importing of banned games and treat them as any other game.

**Comment by JosefNemec** [comment]
Might be fixed in future via #114, this is an issue with Steam API simply not returning some games as part of your library.
