### ISSUE TITLE
[Steam Integration] Clicking cancel on the Startup selection keeps the game at "launching"

### ISSUE THREAD

**Issue by ScottVordem** [JosefNemec/PlayniteExtensions#257]
The startup selection dialog is a very useful feature but pressing "cancel" when the game is launched through Playnite keeps it in the "Launching" state in Playnite rather than putting it back to normal, resulting in needing to manually set the state back to launch it again. I am not sure if this is intended behavior.

To reproduce:
1. Start a Steam game with a startup selection through Playnite.
2. Press Cancel.
3. Launch the same game again through Playnite.

**Comment by JosefNemec** [comment]
Steam's startup selection dialog or Playnite's?

**Comment by ScottVordem** [comment]
Steam's startup Selection, let me try to clarify further:

When a Steam game is launched through Playnite, it changes the game's state in Playnite to "launching" and brings up Steam's startup selection like it should. Pressing cancel on Steam's Startup selection, the game in Playnite will stay at "Launching" and will stay there until the play button for the game in Playnite is pressed to manually reset it back. Steam itself has normal behavior.

This is using the Steam integration play action only, I have no custom play action.

**Comment by JosefNemec** [comment]
We have no way of knowing that you canceled Steam's dialogs. We just tell Steam to launch a game and then it's out of our control what happens next in Steam or what user does next. You will need to simply cancel launching state in Playnite before relaunching the game.
