### ISSUE TITLE
[Universal Steam Metadata]Not all games can be found even it is in steam store.

### ISSUE THREAD

**Issue by armorwei** [JosefNemec/PlayniteExtensions#260]
When searching the games, not all games are supported.
For example: 
[Uncharted Waters IV HD] (https://store.steampowered.com/app/1424800/Uncharted_Waters_IV_HD_Version/)
[Taiko Risshiden V DX ](https://store.steampowered.com/app/1842810/Taiko_Risshiden_V_DX/)

**Comment by JosefNemec** [comment]
We use Steam's own store search, if those games don't show up in the results, it's an issue with Steam store itself.

https://store.steampowered.com/search/?term=Taiko%20Risshiden%20V%20DX&ignore_preferences=1&category1=998

**Comment by armorwei** [comment]
> We use Steam's own store search, if those games don't show up in the results, it's an issue with Steam store itself.
> 
> https://store.steampowered.com/search/?term=Taiko%20Risshiden%20V%20DX&ignore_preferences=1&category1=998

Thank you for getting back to me.  I found that this game is not available in the US/Canadian region but only in Asian Stores.  Is there a way to solve this?

**Comment by JosefNemec** [comment]
There isn't, unless you want to use something like a VPN from a different region.
