### ISSUE TITLE
[Itch.io] Playnite can not detect itch.io app installed via scoop

### ISSUE THREAD

**Issue by Dannykun1089** [JosefNemec/PlayniteExtensions#261]
**Describe the bug**
The itch.io app, when installed by [scoop package manager](https://scoop.sh/), is not recognised. I receive the error message "itch.io app version 25 or newer is not installed."

**To Reproduce**
- Install scoop as per the instructions on [their website](https://scoop.sh/)
- Install the itch.io app using scoop with the command ```scoop install itch```
- Open the itch app to verify the install was successful
- Attempt to authenticate in Playnite

Attempting to authenticate should yield the same error message as I got

**Screenshots**
The error message:
![image](https://user-images.githubusercontent.com/44410306/219979573-59e8adfe-7dfd-4b76-b711-dc649a7f5177.png)

The itch.io app installed by scoop, running:
![image](https://user-images.githubusercontent.com/44410306/219979744-6f3a39d9-e62c-49bd-872b-eca03600802a.png)

**Diagnostics ID**
a6deb989-5381-42c9-ad78-074655597810

**Comment by JosefNemec** [comment]
Registry keys generated by itch app installer that we use to detect itch app's location are presence are not on your system. So it's an issue with scoop.

**Comment by JosefNemec** [comment]
Without those keys we have no way to reliably detect where itch app is installed and adding explicit support for these app installers like scoop or winget to detect possible app locations is just not an option from long term maintenance point of view.
