### ISSUE TITLE
Can't install games from Epic, claims Launcher is not installed

### ISSUE THREAD

**Issue by jojoharry16** [JosefNemec/PlayniteExtensions#265]
# Description
Trying to install games from Epic Games Store doesn't work

# Steps to reproduce
Find game from Epic Games library, click install, profit?

# Screenshots
![image](https://user-images.githubusercontent.com/39400627/222964984-362c1761-9e61-4f11-8c3a-0fefc3d378b2.png)

My software setup is about as scuffed as it gets, since I had to change multiple HDDs without doing a proper reinstall of anything and just hoping everything works; but I was hoping to learn where the extension checks for the Launcher's install and if I can amend it somehow

**Comment by JosefNemec** [comment]
Reinstall Epic client. Epic plugin uses registry keys created by EGS setup to detect where the client is installed.

https://github.com/JosefNemec/PlayniteExtensions/blob/master/source/Libraries/EpicLibrary/EpicLauncher.cs#L42

**Comment by derekhansell** [comment]
This doesn't work.
