### ISSUE TITLE
Launching EA game results in error: Origin Is Not Installed

### ISSUE THREAD

**Issue by sengtsan** [JosefNemec/PlayniteExtensions#266]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**
When attempting to launch Mass Effect Andromeda from Playnite I get a error message: Origin is not installed. I can launch the game from the EA app directly. I have tried to repair the game. 

Similarly for Need for Speed Hot Pursuit Remastered. 

I don't get this issue for Dragon Age Origins however. 

**To Reproduce**
1. Click Launch from Mass effect Andromeda game selection on desktop mode. 
2.  Click Launch from Need for Speed Hot Pursuit Remastered game selection on desktop mode. 

**Screenshots**
Error message For Andromeda
![image](https://user-images.githubusercontent.com/63714826/225096415-af81adc9-e249-4e06-9c5d-813410d11098.png)
process launched that generates error message
![image](https://user-images.githubusercontent.com/63714826/225096700-35d3ae07-3d41-44a7-9d1c-eb98d27c3631.png)
Program responsible for error message
![image](https://user-images.githubusercontent.com/63714826/225096936-13a29f3c-0d1b-48b0-a367-90c69495f7d6.png)
Error Message for Need for speed
![image](https://user-images.githubusercontent.com/63714826/225098175-f64b6659-06e5-45e9-ac79-df92fe6ce25e.png)
![image](https://user-images.githubusercontent.com/63714826/225098260-5b385f42-6907-4cb1-989d-cfb1067dffc4.png)

**Diagnostics ID**
a82718c4-68eb-44a5-af27-281d365d439f

**Comment by JosefNemec** [comment]
The plugin is launching `M:\Program Files (x86)\Origin Games\Mass Effect Andromeda\MassEffectAndromeda.exe`, which should be correct exe. Does the game launch properly when you launch that exe manually?

As far Need for Speed, I don't see any attempts to launch that game in logs.

**Comment by JosefNemec** [comment]
I also see some message from SpecialK plugin interacting with game startup, try disabling that plugin to see if it fixes the issue.

**Comment by sengtsan** [comment]
No. The same error is generated. It only launches through the EA desktop
app.

Apologies, I might have generated the diag before the Need for speed test.
Here is a new one. e3992826-ce43-4912-9bba-9e25a24d6afd

I just tried to run the Need for Speed game from the exe and that also does
not work either, generating the same error. Again, works through the
desktop app.

The Dragon Age Origins exe launches the game.

**Comment by sengtsan** [comment]
I tried disabling the Special plugin but that did not fix the issue.

**Comment by JosefNemec** [comment]
I tried to reproduce it with Hot Pursuit Remaster and the game launches properly for me (launching the same exe that's used on your PC). I suspect it's something borked with EA App or game install. I recommend reinstalling EA App and verifying game install as well.

**Comment by sengtsan** [comment]
Ok, thanks. Will report back once I've done that.

**Comment by sengtsan** [comment]
I uninstalled and reinstalled the EA app and the game (I tested Andromeda)
and it works again. As you predicted it was the EA app that was at fault.
Thanks again for your help.
