### ISSUE TITLE
Newly added games auto-populate Last Played with Date Added.

### ISSUE THREAD

**Issue by hylianux** [JosefNemec/PlayniteExtensions#267]
**Check for existing issue**
Already did, and in fact it was reported before, and ostensibly fixed/closed... But unfortunately the problem still exists, so I'm not sure if it came back, or if it ever actually disappeared.  See #111 

**Describe the bug**
Every time I add a new game, on any storefront (#111 was only limited to steam, I get this problem regardless of storefront, whether it be gog, epic, or steam), the Last Played field is always populated by default with the date I added it to playnite.  This is inaccurate, as there's already a field dedicated for this called "Date Added".

**To Reproduce**
~~Simplest and cheapest way: create an epic games account, if you haven't already, and add a [free game](https://www.epicgames.com/store/en-US/free-games) to your account, then have playnite synchronize itself with your account (either by restarting it or refreshing it).  Be sure to sort your library by last played (descending).  The new game will be added to the top of the list.  You could also test this with any [free gog game](https://www.gog.com/partner/free_games) or the myriads of free steam games.~~ Update: just remove a game and have playnite reimport it... no extra complication needed.

**Screenshots**
No need, honestly the screenshots in #111 illustrate the problem just fine, even if it's a steam-specific example.

**Diagnostics ID**
`3d272a31-a216-4da7-93cb-41bae7e082ec`

**Comment by JosefNemec** [comment]
Can't reproduce, tried with GOG library. I think you are mixing up "Recent Activity" with "Last Played". "Recent activity" is a mix between last played and added date, it will contain value of the most recent one. Which means that if there is no last played date for a game, for example if it's new game added to your library, it will have value of added date.

**Comment by hylianux** [comment]
It's most definitely the last played field... edit >> advanced >> last played, I confirm there's a date of today in the field.  If I grab multiple games on a sale, I have to highlight them all and clear this field specifically.

I'll try it again with safe mode, and if the problem doesn't persist, then I'll track down the offending addon.

Will report back later.

**Comment by hylianux** [comment]
Tried it on safe mode and wasn't able to reproduce the problem.  This is definitely being caused by an addon of some sort.
