### ISSUE TITLE
Steam Game Not Importing (Sam & Max 104)

### ISSUE THREAD

**Issue by Caraamon** [JosefNemec/PlayniteExtensions#269]
**Describe the bug**
So I'm a newcomer and while importing my Steam library I noticed that the game [Sam & Max 104: Abe Lincoln Must Die!](https://steamdb.info/app/8230/info/) is absent, despite [103](https://steamdb.info/app/8220/info/) and [105](https://steamdb.info/app/8240/info/) being imported.

I've tried to search for similar issues, and the only thing that seemed even remotely close was [#910](https://github.com/JosefNemec/Playnite/issues/910) but it says it was fixed in Playnite 9 and none of the solutions linked in that thread connect to anything valid anymore.

**Diagnostics ID**
6506201c-87f0-455a-a52e-7053928eac2b

**Comment by JosefNemec** [comment]
We use Steam's official library web API to fetch your games, so if they are not returning it as part of your library, it's an issue on their side.

You can manually test it via link described [here](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetOwnedGames_.28v0001.29).

**Comment by Caraamon** [comment]
Thank you for showing me that.

I checked and it does seem to be an issue with the API.

**Comment by JosefNemec** [comment]
As a workaround, you can install the game, let Playnite import the game (installed games detection doesn't use that API) and then uninstall it. The game will stay imported as uninstalled.

**Comment by Caraamon** [comment]
That worked, thank you!

I've also contacted Steamworks support, so what comes of that.
