### ISSUE TITLE
GoG won't sync. Installed games won't appear as installed.

### ISSUE THREAD

**Issue by greendabre** [JosefNemec/PlayniteExtensions#27]
GoG games which are installed appear to not be installed in Playnite. Also, GoG fails to sync. Clicking on install on any game that GoG claims to be not installed crashes playnite. 

On trying to sync GoG games, I get this error : Failed to import games from GOG. Unexpected character encountered while parsing value: . Path ", line 0,position 0.

The error happens whether I'm in safemode or not, and whether I've set it to sync only installed games, or both installed and uninstalled games.

Diagnostic ID : 73b93273-3cee-4ea7-93ea-1233d79c10b4
[Playnite812.log](https://github.com/JosefNemec/PlayniteExtensions/files/6527035/Playnite812.log)

**Comment by JosefNemec** [comment]
For installed games not being detected see this: https://github.com/JosefNemec/Playnite/wiki/GOG-troubleshooting

I can't replicate the sync issue, but I've seen it in past if there was some issue on GOG's side (their API having issues). Maybe wait a while or try re-authenticating.

**Comment by greendabre** [comment]
I already looked into the troubleshooting. It didn't do anything.

I even tried manually setting the location of all the games one by one, but the moment playnite is restarted, the games are once again marked not installed and all the location data also gets erased.

This issue has been happening to me for months now.

I already tried re-authenticating multiple times.

At this point, I have only two chances. Either a full reset, which I don't want to do, because I'll lose all my game data, or I remove the GoG extension and setup all the game records manually. =\

**Comment by JosefNemec** [comment]
Try it with [this build of GOG plugin](https://github.com/JosefNemec/PlayniteExtensions/files/6527796/GogDebug.zip). Unpack it to Playnite's install directory under `Extensions\GogLibrary\` directory.

It looks like of installed games has broken manifest and it causes general import failure. So at least on of the games won't be imported, but everything else should work just fine.

**Comment by JosefNemec** [comment]
Fixed in 8.13

**Comment by greendabre** [comment]
Yup. Definitely fixed. Thanks for the message!
