### ISSUE TITLE
Support to launch Epic Games Store and GOG games from Heroic Games Launcher

### ISSUE THREAD

**Issue by FivesBlue** [JosefNemec/PlayniteExtensions#270]
The Epic Games Store launcher is poorly optimised and ridden with bugs, and GOG Galaxy seems to have been somewhat abandoned by it's developers. Of course, for GOG, the option to install games from their installers still remains, but what of Epic Games Store games? Many people have games on this launcher, either due to the fact that Epic have given away a large amount of quality games for free, and because of their exclusives. But many people would prefer not to be stuck with such a poor quality launcher.
This is where Heroic Games Launcher comes in, it's an open source launcher capable of launching games from Epic Games Store and GOG. 
https://heroicgameslauncher.com/
Heroic Games Launcher is better optimised compared to Epic Games Launcher (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki), and I use it to launch my Epic Games games.
However, sadly, Playnite does not have the option to launch games from this launcher, so I propose that optional support for the launcher be added to the Epic Games Store and GOG library plugins, so that people who use this launcher are able use it to launch their games while also enjoying the benefits of Playnite.
Thanks for reading!

**Comment by JosefNemec** [comment]
I don't have time to maintain additional library integrations or alternative launchers (already have plenty to maintain) so this will have to be done by somebody else as a community plugin.
