### ISSUE TITLE
Show uninstalled Rockstar Games Launcher games in Playnite

### ISSUE THREAD

**Issue by Garfieldwxg55** [JosefNemec/PlayniteExtensions#271]
Currently, Rockstar Games Launcher games only show in Playnite when they are installed onto the device, however, displaying uninstalled games should be possible, according to this GOG Galaxy addon:
https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar
Displaying uninstalled Rockstar Games would be a fantastic addition to Playnite and would make importing games from this service significantly more convenient.
Thanks for reading :)

**Comment by JosefNemec** [comment]
Closing as I don't have time to maintain this plugin anymore.
