### ISSUE TITLE
Epic linking problem 

### ISSUE THREAD

**Issue by Connor-the-fur** [JosefNemec/PlayniteExtensions#277]
Hi, 
I'm a bit confused, I installed playnite quite recently and every linking went well until I tried to connect my epic account....
I tested with LAN, wifi and 4g but nothing worked....
Even tested to put the link of the playnite integration into my browser but it didn't worked either....
I hope someone will be able to help me, have a great day !

**Comment by axoroll7** [comment]
Are you using a Playstation account to connect to your Epic Game account ?

[Epic-Game-Store-troubleshooting](https://github.com/JosefNemec/PlayniteExtensions/wiki/Epic-Game-Store-troubleshooting)

"Currently a [known issue](https://github.com/JosefNemec/Playnite/issues/1416) when using 3rd party services (Google for example) to sing in into Epic account. The only solution right now is to [setup a password](https://github.com/JosefNemec/Playnite/issues/1416#issuecomment-534890200) on your Epic account."

**Comment by axoroll7** [comment]
Remove your screenshot if you do not want to show your email account to everyone.

**Comment by axoroll7** [comment]
You can also update Playnite, and all its extensions. If a new update is found by Playnite for one of its extensions, a notification will appear in the notification panel. It solved the problem for me, today, because I often forget to update the extensions.

**Comment by Connor-the-fur** [comment]
Thanks, your firts solution worked !
Although, sorry for the late response, but thanks to you it works now :)
And i'll delete the scren.
Have a nice day !
