### ISSUE TITLE
Rockstar integration not adding games in library

### ISSUE THREAD

**Issue by marianionita-VH** [JosefNemec/PlayniteExtensions#278]
I've installed and logged in Rockstar Game Launcher and I've installed the Playnite Rockstar addon. I understand that this addon doesn't have a settings dialog / window (so I guess it uses the logged in user from Rockstar Game Launcher), but when I update the Rockstar game library in Playnite, no game is added.

Diagnostic package id:
dcf64c1b-0679-4043-8880-f71f6fd03286

**Comment by JosefNemec** [comment]
The plugin only supports import of installed Rockstar games, that's why there are not settings to sign-in with an account.
