### ISSUE TITLE
Kingdom Come Deliverance not starting

### ISSUE THREAD

**Issue by flaggiani** [JosefNemec/PlayniteExtensions#279]
### Bug Description

Kingdom Come Deliverance does not start via Playnite. The splash screen displays but then closes. I have to start the game via GOG Galaxy to play it.

### Diagnostics ID

73494eaf-9f93-4a38-bbe7-91ad5c66e2a8

**Comment by JosefNemec** [comment]
Pretty much confirmed it's game issue according to this post: https://www.gog.com/forum/kingdom_come_deliverance/game_will_not_launch_from_the_exe
