### ISSUE TITLE
Ability to launch Steam client and games in browser-less mode

### ISSUE THREAD

**Issue by dunestorm333** [JosefNemec/PlayniteExtensions#28]
By default Steam launches with a WebKit browser loaded in the background, this has a massive impact on RAM.
It's entirely possible to force both the standalone client and individual games without a browser.

Opening Steam with no browser:
`"C:\Program Files (x86)\Steam\steam.exe" -no-browser +open steam://open/minigameslist`

Running a game via Steam without a browser:
`steam://rungameid/1328670 -no-browser`

Can this be please considered in order to reduce the footprint of running games via Steam?

**Comment by JosefNemec** [comment]
https://playnite.link/forum/thread-659.html

**Comment by dunestorm333** [comment]
Thank you, I wasn't aware of this plugin. Looks like someone has already beat me to it! :)
