### ISSUE TITLE
Itch.io plugin: Certain games are not imported (possible because of special characters)

### ISSUE THREAD

**Issue by stabilergriller** [JosefNemec/PlayniteExtensions#281]
**Describe the bug**

Hello,
The itch plugin doesn't seem able to import every game I own in my library.

Here is an example: https://dereel.itch.io/yahu

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/115423284/eb47e997-6b96-41f3-a947-294443959a9a)

Is also shown as "owned" in the official Itch client:

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/115423284/a5bbc854-edd0-4470-a225-f513874813c5)

But the game is not in my library. Neither "Yahú" nor "Yahu" yields a result.

Maybe the many special characters are a problem?

I also found 2 other games that have the exact same problem:

https://dereel.itch.io/la-machine-a-rever ["La Machine à Rêver" - has also special characters]
https://dereel.itch.io/the-dream-machine [English version of "La Machine à Rêver"]

May be related: Some are imported, but with incorrect special characters:

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/115423284/2fe07dcf-cd0d-430d-9dec-cd1a4e938544)

Correct should be Marche Frontières - https://dereel.itch.io/marche-frontieres

**Diagnostics ID**
e2ea2445-d2a9-4b0b-adc9-b7122c7f3853

**Comment by JosefNemec** [comment]
Can't reproduce. "La Machine à Rêver" imported for me fine (after claiming it to my library) and "Marche Frontières" has correct name encoding:
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/3874087/022f68db-55bd-4d76-92f2-6d41bee55e09)

**Comment by stabilergriller** [comment]
I'm going to close this for now, since I'm guessing this is because it's running in a VM in VirtualBox. If I can ever confirm it occurs on real hardware I will re-open this issue.
