### ISSUE TITLE
Niemożność zalogowania się do Epic mimo dobrze wprowadzonych danych

### ISSUE THREAD

**Issue by Strieloka** [JosefNemec/PlayniteExtensions#282]
Tak jak w temacie, w przeglądarce i w aplikacji epic zalogowałem się bez problemu. Gdzieś przeczytałem, że czeba odczekać .czekałem 8 godz. i nic
![Screenshot_1](https://github.com/JosefNemec/PlayniteExtensions/assets/133788907/0490f282-4864-4d1e-8cf3-0552999629dd)

**Comment by JosefNemec** [comment]
English please (or Czech)

If you are logging via 3rd party service (like Google account), you may need to create normal Epic one: https://github.com/JosefNemec/PlayniteExtensions/wiki/Epic-Game-Store-troubleshooting

**Comment by Strieloka** [comment]
First issue .wants to log in to epic account
Second issue on the other laptop I logged in without any problems
