### ISSUE TITLE
unowned xbox games being imported

### ISSUE THREAD

**Issue by bleything** [JosefNemec/PlayniteExtensions#288]
**Check for existing issue**

I checked but didn't see anything relevant!

**Describe the bug**

At least one game (Wargroove) that I don't own is appearing in my library when I import from Xbox.

I suspect the issue is that I played it when it was on Game Pass and so it's appearing in my history, but it's no longer on Game Pass and I don't own it.

**To Reproduce**

1. enable xbox library plugin
2. check "connect account", "import installed games", "import not installed games"
3. authenticate
4. refresh library

**Screenshots**

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/270/19158275-b37a-4ceb-8a1e-f4f1a00eb8c5)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/270/b704ca9a-e5ad-41fb-b3d5-cadcb7350b9c)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/270/a554e568-e56b-496d-b5e9-ecca31199ed7)

**Diagnostics ID**

9f28bad9-f2e6-4705-8c0a-ae0e00556d1a

**Comment by SoddenCub71** [comment]
The issue's worse than that, I think. Similarly to Gog Galaxy, it specifically imports played games, and not owned ones. I get everything I've ever played through Game Pass or Games with Gold, and every XBLA trial I've played is imported as a full game; but games I've bought and "own" digitally can't be imported until I've played them.

**Comment by shad00m** [comment]
same issue here, every game ever played on xbox (console) is imported even though I disabled "Import Xbox Console Games"

**Comment by JosefNemec** [comment]
Can't fix. The API we are using doesn't allow us to distinguish between played and owned games.
