### ISSUE TITLE
humble not authenticated, gog not authenticated, every day

### ISSUE THREAD

**Issue by triadne** [JosefNemec/PlayniteExtensions#289]
every day I turn my pc on and playnite starts and it gives me two error notifications,
Failed to import games from Humble. User is not authenticated.
Failed to import games from GoG. User is not authenticated.

I have them both authenticated and when i go into the settings, it shows them as authenticated.

**Diagnostics ID**
8f85d6b5-0591-4b15-8550-6462187cf8d7

**Comment by JosefNemec** [comment]
Can't reproduce. Try restarting Playnite in safe mode (from Help menu) to see if it fixes the issue. You have quite a lot of plugins installed so maybe it's some conflict with other plugin.

Auth indicator in plugin settings uses the same code as startup library update, so it would be very weird if you get auth error on startup, but plugin settings shows that you are authenticated.

**Comment by JosefNemec** [comment]
No idea. Probably some issue with your PC not being able to connect on system startup to websites these plugins need to fetch library. I don't think there's anything I can do about this.

I tried it on my dev PC and it seems to generally work fine with GOG and Humble syncing on system boot.
