### ISSUE TITLE
IGDB plugin failing under Windows 7 due to SSL/TLS error

### ISSUE THREAD

**Issue by jellyveggie2** [JosefNemec/PlayniteExtensions#290]
**Describe the bug**

As of version 2.6, the IGDB plugin fails to download game metadata on Windows 7, citing a SSL/TLS error. 
It does search for game titles correctly, it's the metadata fetching step that fails. 
Previous versions of this plugin do not have this issue (tested on v2.4 and v2.5), nor does v2.6 fail if used on Windows 10.
I would assume it's either 809a01e or 09f99d4 that are to blame, as the rest are just localization updates.

**To Reproduce**

1. Ensure you are on Windows 7 and have the latest version of the "IGDB metadata provider" plugin (v2.6 as of writing)
2. Manually add a game. Any game will do, "Splinter Cell" seems to be a decent one
3. Under "Download Metadata", choose IGDB
4. Select any of the "Splinter Cell" games presented
5. The following error message appears: "Failed to download metadata: The request was aborted: Could not create SSL/TLS secure channel."
6. Download a previous version of the plugin, such as [v2.5](https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_5.pext)
7. Drag-and-drop the .pext file onto Playnite. Install and restart
8. Repeat steps 2-4
9. Download succeeds

**Screenshots**

Initial setup:
![Capture0](https://github.com/JosefNemec/PlayniteExtensions/assets/78439377/21104c2d-c9aa-4b4a-96f0-dc1d3c81be97)

Game title search does succeed:
![Capture1](https://github.com/JosefNemec/PlayniteExtensions/assets/78439377/f7b15989-c9ff-4c09-8d96-b585a0bc6d1f)

But here the game's metadata download fails:
![Capture2](https://github.com/JosefNemec/PlayniteExtensions/assets/78439377/aaf2070b-4e18-40ee-8016-8de92376ad0e)

The expected result, as obtained using v2.5:
![Capture3](https://github.com/JosefNemec/PlayniteExtensions/assets/78439377/8c660a92-46bc-4b35-bf14-68af3d38f9d2)

**Diagnostics ID**

d6e5f564-a87b-494f-b0d5-6d8489bd09f4

**Comment by JosefNemec** [comment]
Closing as I don't consider Windows 7 and 8 to be supported anymore.
