### ISSUE TITLE
Wrong metadata for Epic games.

### ISSUE THREAD

**Issue by yo1dog** [JosefNemec/PlayniteExtensions#292]
Diagnostics ID: `15e0152c-e6c2-47b2-9acf-f48b93499aeb`

I noticed the metadata for some Epic games did not belong to the game in the library. Specifically, for the game [Hue](https://store.epicgames.com/en-US/p/hue) it pulled metadata for... uhh... "Sexy Tails - and other puzzlingly attractive furry things"... a "furry" porn game. 😳

I looked through the rest of my Epic games and noticed a few more. All listed bellow. In each case the name was correct but all other metadata was wrong. Redownloading metadata from "Official store" (with override enabled) did not help.

Library Game | Pulled Game | Game Id | Database Id
-------------|-------------|---------|------------
[>observer_ (2017)](https://www.igdb.com/games/observer)                                         | none*                                                                                                   | `Tumeric`                          | `5875b05f-2ac2-4dd9-8be0-801ce4c515e8`
[Control (2019)](https://store.epicgames.com/en-US/p/control)                                    | [The Foundation: Expansion 1 (2020)](https://store.epicgames.com/en-US/p/control--the-foundation)       | `Calluna`                          | `2c31e536-46ae-437a-ba72-a02d80634ded`
[Crying Suns (2021)](https://store.epicgames.com/en-US/p/crying-suns)                            | [Crying Suns Deluxe Edition](https://www.gog.com/game/crying_suns_deluxe_edition)**                     | `18fafa2d70d64831ab500a9d65ba9ab8` | `52244e08-a144-4e5c-a509-9c81fd74a3cf`
[Fall Guys (2020)](https://store.epicgames.com/en-US/p/fall-guys)                                | [Fall Guy (1983)](https://www.igdb.com/games/fall-guy)                                                  | `0a2d9f6403244d12969e11da6713137b` | `a59c2122-43ba-443a-afab-2540203d8241`
[For Honor (2017)](https://store.epicgames.com/en-US/p/for-honor)                                | [For Honor Complete Edition (2020)](https://www.epicgames.com/store/p/for-honor--complete-edition)      | `Sundrop`                          | `a30c1187-d713-4b3d-8430-9e6e7d28f527`
[Hue (2016)](https://store.epicgames.com/en-US/p/hue)                                            | Sexy Tails (porn)                                                                                       | `Herring`                          | `3bdb1549-cdaf-4bdf-af07-70419e4ec598`
[Ghostwire: Tokyo - Prelude (2022)](https://store.epicgames.com/en-US/p/ghostwire-tokyo-prelude) | none                                                                                                    | `90185b9fc481480097f52d86921dc08c` | `cc2eb8a9-45a8-485f-8669-a25837333a64`
[Maneater (2020)](https://store.epicgames.com/en-US/p/maneater)                                  | [Maneater (1975)](https://www.igdb.com/games/maneater--1)                                               | `Turtle`                           | `ce772a3e-ad0c-4901-94fe-51ddcd7e60e8`
[A Plague Tale: Innocence (2011)](https://store.epicgames.com/en-US/p/a-plague-tale-innocence)   | [Batman: Arkham City (2011)](https://www.igdb.com/games/batman-arkham-city)                             | `e0fa47ae79514345823bff209ae29451` | `40c0b9af-1d3c-4187-b2a0-556996de4c13`
[PREY (2017)](https://store.epicgames.com/en-US/p/prey)                                          | [Prey (1993)](https://www.igdb.com/games/prey-an-alien-encounter)                                       | `52d88e9a6df248da913c8e99f1e4c526` | `5725fe67-be6f-4dbe-bf9b-b41561ac9117`
[Q.U.B.E. 2 (2018)](https://store.epicgames.com/en-US/p/q-u-b-e-2)                               | none                                                                                                    | `Auk`                              | `be150274-0da9-45a9-8747-78bd3dd54ab7`
[The Stanley Parable (2013)](https://store.epicgames.com/en-US/p/the-stanley-parable)            | [The Stanley Parable: Ultra Deluxe (2022)](https://www.igdb.com/games/the-stanley-parable-ultra-deluxe) | `Freesia`                          | `be5f20da-d9c8-4ae0-b11e-5b853c9fee13`
[Stick It To The Man! (2013)](https://store.epicgames.com/en-US/p/stick-it-to-the-man)           | [Stick it to the (Stick) Man (2021)](https://www.igdb.com/games/stick-it-to-the-stick-man)              | `Goldfish`                         | `e7234e08-c35a-410f-8adc-20ae99ba9296`
[The Witness (2016)](https://store.epicgames.com/en-US/p/the-witness)                            | [The Witness (1983)](https://www.igdb.com/games/the-witness--1)                                         | `Magnolia`                         | `a75f4fa1-cb2e-4e44-8fbc-7e1f1541003a`

*Was removed from Epic store.
**Has partial metadata and a single GOG link.

**Comment by JosefNemec** [comment]
Epic plugin stopped providing "official store" metadata some time ago so this must be some miss match from IGDB plugin, I'll look into it.

I'll be releasing major IGDB plugin rewrite soon, which will probably fix it.

**Comment by JosefNemec** [comment]
Should be fixed in new IGDB update released today.

**Comment by yo1dog** [comment]
So the Epic plugin just pulls in game names and then uses the name to search IGDB for the metadata?

Thanks for the fix!
