### ISSUE TITLE
XBO/XS Games with Gold importation

### ISSUE THREAD

**Issue by SoddenCub71** [JosefNemec/PlayniteExtensions#296]
Microsoft's "Xbox Live Gold" subscription allows you to claim certain games that can subsequently be played as long as you're still subscribed to Gold. One's collection can be viewed through a hardware Xbox or the Xbox mobile app, and accessing a game's Store page through a browser also indicates when you have it through that service. Playnite only seems to see the games that you've played, though, regardless of ownership status. It'd be nice to be able to import my Games with Gold collection, maybe as a separate "Library" to distinguish them from actually owned games.

**Comment by JosefNemec** [comment]
Not possible with the API we are using.
