### ISSUE TITLE
#IDARB for Xbox imports wrong

### ISSUE THREAD

**Issue by SoddenCub71** [JosefNemec/PlayniteExtensions#297]
I have the game "#IDARB" in my Xbox Games with Gold Collection, but for some reason Playnite imported it as a PC game instead. Oddly, the Xbox mobile app also fails to list it in my collection.

**Comment by SoddenCub71** [comment]
Similar error: Microsoft Minesweeper imports as being for Xbox One and PC (Windows), rather than PC only.

**Comment by JosefNemec** [comment]
Can't fix if you say that not even Xbox mobile app imports it. As far as I know we are using the same API.
