### ISSUE TITLE
Xbox 360 games import with wrong release date

### ISSUE THREAD

**Issue by SoddenCub71** [JosefNemec/PlayniteExtensions#298]
As illustrated here:
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/114965480/656ab68b-9afa-4e20-bbf7-84836e0d6367)
If you look up any of the games' release dates, you can see that they came out earlier than listed. At first I thought that the date might be when the Games on Demand version was released; but it's wrong for Arcade games too. Note that the "Release Date" for Sonic the Hedgehog is after the "Last Played" date.

**Comment by JosefNemec** [comment]
360 game import uses "weird" part of Xbox API that merges GFWL and 360 games under one entry and has some other issues. Not worth my time trying to fix it, in my opinion.
