### ISSUE TITLE
Games for Windows Live games show as Xbox 360 games

### ISSUE THREAD

**Issue by FivesBlue** [JosefNemec/PlayniteExtensions#299]
Hi, I was importing a few older games I had on Games for Windows Live. They imported just fine, however, they showed as being Xbox 360 games, with Xbox 360 banners, having the listed platform of Xbox 360, and only import when the option to import console games is activated. Hopefully this is a fixable bug, thanks for reading!

**Comment by JosefNemec** [comment]
Nothing I can do about it, that's how Xbox API reports those games: https://github.com/JosefNemec/PlayniteExtensions/wiki/Xbox-Library-troubleshooting#gfwl-pc-games-are-imported-as-360-games
