### ISSUE TITLE
RDR2 Launching but Playnite isn't tracking playtime

### ISSUE THREAD

**Issue by codevski** [JosefNemec/PlayniteExtensions#30]
As the title states, Launcher opens but as soon as that happens playnite thinks the game closed so when RDR2 launches playnite thinks the game has closed. Anyway the plugin can know / wait if RDR2.exe is still open?

**Comment by CanRanBan** [comment]
Time tracking of RDR2 works reliably now. Tested for several weeks and there's only a minor difference in comparison to the inbuilt time-tracking of Rockstar's own launcher.

See commit [5d73c89622c54c49b90ae55cbf5ce6f464aa78eb](https://github.com/JosefNemec/PlayniteExtensions/commit/5d73c89622c54c49b90ae55cbf5ce6f464aa78eb).
