### ISSUE TITLE
itch.io: import icons from store page favicons

### ISSUE THREAD

**Issue by brigcam** [JosefNemec/PlayniteExtensions#300]
Many itch games have custom favicons on their store page, would it be possible to import them as icons in Playnite?

**Comment by JosefNemec** [comment]
I already looked into it, it's not worth doing because fav icons are very low resolution usually.

**Comment by brigcam** [comment]
sorry to hear that, I like to have custom icons in the details view, having an endless wall of pink itch logos isn't very appealing, and they wouldn't need to be particularly hires, but thanks anyway for the excellent piece of software!

**Comment by JosefNemec** [comment]
You can give SteamGridDB plugin a try, they provide icons, although probably not for most smaller games that are only on itch.

As far as the size, from what I remember those fav icons were usually 32x32 and lower, which turns into colored blog when resized depending on a theme your are using. But that might be actually preferable to the default itch icon as you mentioned.

I'll leave this open in case anybody would want to implement this, but I can't see doing it myself in near future.

**Comment by brigcam** [comment]
yes, I already use the SteamGridDB plugin, but as you noticed most games on itch.io are small productions that have no entries elsewhere. I use the default theme with the details view and icons are most useful for the list on the left side, where they are small, so even being 32x32 they don't get so blurry, and anyway blurry as they may be, they still provide some at-a-glance diversification between the various items of the list. thanks for keeping this open!

**Comment by Acru** [comment]
I think the 'icon support' added last patch should be optional, as the result is usually bad, thus should be a user choice.

I have Playnite fetching icons from the official store first, as for all other integrations that return an icon the result is good, and those official store icons will never mismatch to the wrong game. Now I have to specifically disable this (or change the provider order) just for itch.io, which is not ideal.

---

Most games on itch.io don't specify custom favicons, so the favicons are automatically generated from the cover, cropped and scaled and nearly always producing a bad result.  If there was a way to detect if the favicon was manually specified or automatically generated, then ideally the plugin would only return the manually specified ones, but if there is no way to determine this then I think there should be an option to not return an icon at all and let the next provider try.

For stats to justify this, my itch.io library is 97 items, of which only 9 did not get icons from other providers, and of those only 2 had a manually specified favicon from the official store.  Fetching icons only from the official store, only 22/97 are manually specified by the developer, or about 23%, where the remaining 77% look like crap.  Moreover, other providers offer better quality icons when a match can be found, which is most of the time for my library at least.

---

Incidentally, a much better source of icons for itch.io games is from the installed exe itself, though fetching the icon from the play action doesn't work currently, and even then there is no way to do this automatically for a whole list of titles.  I was thinking about writing an 'installed exe icon provider' at one point, for the metadata import system, but never had the time.

**Comment by brigcam** [comment]
Hi, since I was the one who asked, I'd like of course to thank the author! Actually I already fixed everything by hand using a plugin with which I manually created the icons one by one using the cover images and cropping and resizing them as needed. But of course I would've liked this to be automated, and I'm glad it is now.

As for the icons not looking good, to me as I said it's a matter of having at least some quick visual indicator to distinguish between the games, rather than a column of default store icons. If it looks good, all the better, if not, it's ok to me.

Of course I understand Acru's POV and I hope that a switch to turn the feature off can be easily implemented too!

**Comment by brigcam** [comment]
I did set the icons manually because there was no other way at the time and it seemed the author wasn't interested in trying the favicon route, otherwise I would've gladly saved the effort. 😅

I have about 7/800 games in my itch.io library and it took quite a lot to fix all of their icons, "luckily" I'm a bit on the OCD side so such things kinda relax me, but installing each one of them and extracting the .ico would've really been too cumbersome.

I hope the author will add a switch to disable the automation, so it'll fit your preferences too!

**Comment by JosefNemec** [comment]
Done in 0ea976179b7099ae17d6cc617988cc22c3d4da75
