### ISSUE TITLE
Failed to import games from Epic Games. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by AnkleScout** [JosefNemec/PlayniteExtensions#303]
Hey, whenever i try to import my Epic games i get the Error Message from the Title.
I have seen this issue discussed on Reddit, but the Links have expired, so im trying my luck here.

**Diagnostics ID**
e15474a8-c138-4a5e-919a-7879173e5a5e

**Comment by JosefNemec** [comment]
Fixed in 2.17 update. The import should no longer fail, but some games might not be imported, in that case you will need to reinstall those games in Epic client.
