### ISSUE TITLE
Not all games from GoG are visible in Playnite

### ISSUE THREAD

**Issue by Niewiemu** [JosefNemec/PlayniteExtensions#305]
**Check for existing issue**
Searched and found similary described issue here
https://github.com/JosefNemec/Playnite/issues/1393

**Describe the bug**
Games that I have on GoG not visible in library in playnite
First screenshot show search on GoG where black mirror is visible as in my library
Second shows search for black in playnite and the game is not visible
Not sure if it is a separate issue or if there are more like that

**Screenshots**
https://cdn.discordapp.com/attachments/753656314693156945/1131633580007759973/image.png
https://cdn.discordapp.com/attachments/753656314693156945/1131633853442830537/image.png

**Diagnostics ID**
505f47df-8032-4f0a-b396-db37c4412a89

**Comment by Niewiemu** [comment]
No it does not seem to be there

**Comment by JosefNemec** [comment]
Then there's not much I can do about it I'm afraid.

**Comment by Niewiemu** [comment]
Ok thank you :)
It is strange as I have it in my profile on GoG - I will just have to remember about it :D
https://cdn.discordapp.com/attachments/753656314693156945/1131653668832297080/image.png
