### ISSUE TITLE
Amazon Games login issue

### ISSUE THREAD

**Issue by Jacob1Tm** [JosefNemec/PlayniteExtensions#308]
**Check for existing issue**
Nothing helpful in any of issues

**Describe the bug**
After logging in to Amazon games it just redirects to Amazon.com

**To Reproduce**
Try to log in

**Screenshots**
![24July2023_2089](https://github.com/JosefNemec/PlayniteExtensions/assets/84023677/05bb5b72-7f5c-496f-91e3-1507c9b73881)

**Diagnostics ID**
cafd4de2-4e5b-4d96-b216-f751294a7a26

**Comment by AndyMG22** [comment]
I am also seeing this - no way to use my default Amazon country to authenticate.

**Comment by ViktorAbrahamsson** [comment]
Same problem for me, however, it closes down a second after the window of the Amazon-store shows.
If I have to guess it might be something with the region that we are trying to log in on. 

Example, I think it is not working for some of us that have our Amazon-accounts on other regions. I'm from Sweden and I've noticed that I still can log into other regions but the account does not have anything on it, for example audiobooks and games.

**Comment by RudyvdLinden** [comment]
I'm having the same issue. My Amazon account is from the Netherlands, but it goes to .com. I see this window, then it disappears and I get the message I'm not verified with Amazon.

I would imagine that the Amazon Games API would be more suitable (if existent?) since there I can log on no trouble.

**Comment by RudyvdLinden** [comment]
To make matters worse, NONE of my accounts can be verified in Playnite, so NONE of my non-installed games show up (from libraries that need verification at least).

**Comment by JosefNemec** [comment]
Closing as I can't replicate the issue myself and fiddling with other people's accounts is a no go for me (I would need to have an access to the account to debug this). Somebody with an account affected by this issue will have to debug and fix it.
