### ISSUE TITLE
[Solved] No 'time played' for GOG games

### ISSUE THREAD

**Issue by SanderBouwhuis** [JosefNemec/PlayniteExtensions#309]
### Bug Description

I am currently playing Xenonauts 1 on GOG. In GOG Galaxy I properly see that I have played 4h19m (over 3 evenings), but in Playnight it states I have never played this game.

### To Reproduce

Play a GOG game. Play time is not shown in Playnight.

### Diagnostics ID

e6311c7c-0813-4a77-86ce-ef01af4ab57f

### Screenshots

![2023-07-26 22-12-56](https://github.com/JosefNemec/Playnite/assets/10495173/8cd1f89d-ce11-4220-9972-81b3064f3c36)

**Comment by JosefNemec** [comment]
Make you have import of play time enabled (general Playnite settings) and make sure you have import of uninstalled GOG games enabled.

**Comment by SanderBouwhuis** [comment]
That was it!

Why on Earth would that option be off/disabled by default? That makes no sense.
Thanks for solving this. Hopefully, the default will switch to on/enabled.

**Comment by JosefNemec** [comment]
The option is not disabled by default. It's set to import play time only for newly added games since then Playnite can take over and use its own internal tracking.
