### ISSUE TITLE
EA Play Games Not Launching

### ISSUE THREAD

**Issue by shangles** [JosefNemec/PlayniteExtensions#311]
**Describe the bug**
I used to be able to select a game in my Playnite library that was on the EA Play platform and launch it.  If EA Play was closed, it would open EA Play and then launch the game.  Now none of this is working.  When I launch an EA Play game (Battlefield 2042, Madden NFL 23) the EA Play app doesn't open and the game doesn't launch.  Even if I launch the EA Play app first and then try to launch the game from Playnite, it still doesn't launch.

**To Reproduce**
Attempt to launch a game part of the EA Play platform from Playnite with or without the EA Play app already running.

**Screenshots**
Attaching screenshots of the EA Play app version, and my Actions tab for both Battlefield 2042 and Madden NFL 23.
![PrtScr capture_3](https://github.com/JosefNemec/PlayniteExtensions/assets/9053908/98cda44a-ff4f-4509-8a57-6d6d902ffc84)
![PrtScr capture_2](https://github.com/JosefNemec/PlayniteExtensions/assets/9053908/1d3129eb-7783-48e3-90b3-f88bae334bfa)
![PrtScr capture](https://github.com/JosefNemec/PlayniteExtensions/assets/9053908/3c32ca8b-34db-4d96-a36c-2e0cf1e762eb)

**Diagnostics ID**
37f0cbc8-62f8-4e20-98c9-c9d45064c61f

**Comment by JosefNemec** [comment]
Looks like EA App or game issue to me. Game exe is being launched properly according to the logs, but game process exits after 1 second.

**Comment by shangles** [comment]
Yeah, it's possible a recent update to EA Play app introduced this bug.  I guess it's out of my (and your) control now at this point?

**Comment by shangles** [comment]
Whatever issue I was having before seems to have corrected itself.  It may have been a local issue.
I just launched Playnite with EA Play app closed and launched Battlefield 2042.  That triggered a launch of EA Play and then the game loaded successfully.

Thinking we can close this one out.
