### ISSUE TITLE
Library File Corruption

### ISSUE THREAD

**Issue by TheBupMasterToad64** [JosefNemec/PlayniteExtensions#314]
**Check for existing issue**
As far as I can tell, this isn't an existing issue.

**Describe the bug**
Anytime I try to do anything like remove a game from my library or add metadata, it crashes. Even launching it in safe mode doesn't do anything. The message box showed it as a "Library File Corruption."

**To Reproduce**
Not sure what this means.

**Screenshots**
![Screenshot 2023-08-16 154005](https://github.com/JosefNemec/PlayniteExtensions/assets/42523150/00720918-b3d7-476a-af72-fd93cc3892cd)

**Diagnostics ID**
d4c3aac0-de66-4ad9-80b4-e4fdba68a6f8

**Comment by JosefNemec** [comment]
Go to `F:\Playnite\library` folder and upload all `games.db` file.

**Comment by TheBupMasterToad64** [comment]
[games.rar.zip](https://github.com/JosefNemec/PlayniteExtensions/files/12363119/games.rar.zip)

I'm kind of new to GitHub, so I don't know if there is a way to upload the file directly without packing it into a Zip but there you go.

**Comment by TheBupMasterToad64** [comment]
I also just realized the awkward name I gave it, sorry ^^;

**Comment by JosefNemec** [comment]
Here's fixed file [games.zip](https://github.com/JosefNemec/PlayniteExtensions/files/12366780/games.zip)

**Comment by TheBupMasterToad64** [comment]
thank you!
