### ISSUE TITLE
Humble library integration 3.7 sometimes downloads data for game TWICE, but not the same data

### ISSUE THREAD

**Issue by ZLoth** [JosefNemec/PlayniteExtensions#315]
**Describe the bug**
When utilizing the Humble library integration, sometimes it shows up twice, but the data is not the same. 

**Screenshots**
Example game entry in list view:
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/6700159/ced4343b-f91e-4572-a767-e1aeeceb5455)

Details of 1st entry:
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/6700159/240d959c-00dd-4e21-b21b-eedb597406f8)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/6700159/b5cd2c3b-d814-47ff-b8e4-5d593aa98557)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/6700159/0ec19ce0-590e-4f7c-a933-ecd0332808db)

Details of 2nd entry:
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/6700159/621b4efe-1cf7-4da7-857e-e42b28f0ebb7)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/6700159/33bdbb5d-745f-4b87-954c-b005523f5a3f)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/6700159/3e28e77c-fc0a-4a16-acbc-b7597302a9b2)

Options in library integration:
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/6700159/f8d5194c-5bd6-4d79-9d79-8e9c3c6e085d)

**Diagnostics ID**
96b6365c-17a7-49d0-a2a0-4c2c672662a7

**Comment by ZLoth** [comment]
I see.... one version is the "Humble Trove" version while the other isn't.

**Comment by JosefNemec** [comment]
Yeah these are two separate games on your account, nothing to fix from our side.
