### ISSUE TITLE
When starting game not through Playnite, play time isn't tracked

### ISSUE THREAD

**Issue by rakleed** [JosefNemec/PlayniteExtensions#316]
**Describe the bug**
When starting the game not through Playnite, the play time is not tracked. For example, through Steam, Xbox app, EA app, Battle.net or directly through the `.exe` file to launch the game. However, only when launched through the Epic Games Launcher, the play time is always correctly tracked.

Is this the expected behavior? Since I could not find information about this in the Wiki, only one mention: https://github.com/Jeshibu/PlayniteExtensionsFeatures/blob/main/libraries.md#user-content-fn-h-e1642277905184e056e9996d65cdc9c1:~:text=Play%20time%20is%20always%20tracked%20when%20launched%20through%20Playnite%20%E2%86%A9

**To Reproduce**
1. Launch Playnite
2. Start any game not through Playnite

**Screenshots**
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/19418601/e862cea3-07a9-45c6-bb8f-590e864d43b6)

**Diagnostics ID**
889d91cc-8ebe-41a4-8b1c-ddb0700d35a6

**Comment by JosefNemec** [comment]
Games have to be started through Playnite for time tracking to work 100% reliably. Alternatively, you have to have time sync set to "always" in general settings (it's set to import time for newly imported games only by default). Also not all integration plugins support play time sync.

**Comment by JosefNemec** [comment]
Also just having Playnite running is not enough, you have to actually start games using it.

**Comment by rakleed** [comment]
Is it even possible to implement the functionality I described?

**Comment by JosefNemec** [comment]
Possible? Yes, but not practical to implement and maintain in long term. If you want Playnite to keep accurate play time tracking, you need to use it to launch games.
