### ISSUE TITLE
Adding steam. Also guide menu 

### ISSUE THREAD

**Issue by Koriebonx98** [JosefNemec/PlayniteExtensions#318]
### Feature description

Where steam has a steamcmd.exe and can run command line.

cant playnite imply this , so as it knows what games not installed when click install it runs steamcmd.exe with the command to downlaod set game to the drive?

this will allow people to download games inside of playnite without steam??

It would be handy to also have the guide button bring up a playnite separate window with some options on it. Like the Xbox menu on Xbox or so menu. So stuff like “close game”, “achievements” “guides” ect

**Comment by JosefNemec** [comment]
steamcmd is designed to deploy server components (like dedicated game servers), not to install normal games. I looked into it in the past and it would be quite a headache to get it working properly including stuff like updates. Right now I have no planning adding it. Somebody else will have to make a plugin supporting this.

**Comment by Koriebonx98** [comment]
If you own a game on steam,  using the steamcmd you can login then install game that way without  steam.

suppose one would have to have a way to add login details to begin with into the command maybe from a txt file?

possible work around atm, is launching setting steam to launch big pic mode to use guide of steam games. 
heroic has a addon, possibly something like that would be ideal but agree updates would be a iffy one to bypass.

possible guide menu inside of playnite might be easier, and a way to add friends (login to multiple systems, steam,epic ect) so then would be easier to see what games they play and there recent games played, online, succes story achievements ect 
For example if I’m logged into steam,epic, gog and have a playnite user name that has all them linked, I can add another friend via playnite and it’ll have there account names for them launchers. This would be easy to add them on all launchers or one by one but have all details in one place
