### ISSUE TITLE
Only installed games from GOG are imported

### ISSUE THREAD

**Issue by JanHBade** [JosefNemec/PlayniteExtensions#324]
**Check for existing issue**
similar https://github.com/JosefNemec/PlayniteExtensions/issues/305#issue-1814444449

**Describe the bug**
only installed game are in the libary, all other not

https://www.gog.com/account/getFilteredProducts?hiddenFlag=0&mediaType=1&page=0&sortBy=title
under that link i see all games

**Screens*
![grafik](https://github.com/JosefNemec/PlayniteExtensions/assets/3524802/f0b00565-baf3-48c9-a33e-ffefe50d4580)

**Diagnostics ID**
edea17b9-2e12-497e-ab70-704f893bef4c

**Comment by JosefNemec** [comment]
You have a filter enabled that only shows installed games.

**Comment by JanHBade** [comment]
damn excuse me my fault
