### ISSUE TITLE
Beta selection for Steam and GOG Integration.

### ISSUE THREAD

**Issue by ScottVordem** [JosefNemec/PlayniteExtensions#328]
**Describe the solution you'd like**
I think it would be nice to have the ability to choose which beta build to use for Steam games. GOG has this ability also, but there isn't a lot of games that use it.

Look at Garry's Mod for example. There are a different builds to choose from. It would be nice to have this ability in Playnite, but I am not sure if it is possible. Some games have private betas only accessible with a code, so not sure how to integrate those.

**Screenshots**
Being able to choose a version from this list from within Playnite, or the ability to open this window from Playnight.

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/107659193/7066b5e1-6f40-40ae-bbb1-57896e496470)

**Comment by JosefNemec** [comment]
Not possible. Steam doesn't expose this externally as far as I know and it requires new download anyways that needs to be performed inside the original client.

**Comment by ScottVordem** [comment]
Tried looking around myself and I may have found a way, although not sure how to integrate it into playnite.

I discovered that the branch information is stored in the `appmanifest_<steam app id>.acf` files located in the steamapps folder **in the library directory the game is installed in.** (If the game is installed in a different location other than the default, it will the steamapps folder in that directory).

Manually changing the `BetaKey` value under the `UserConfig` section in the file and restarting steam, causes Steam to update the game to that branch. Simply setting the value to `none` will go back to the regular branch.

Sometimes that value will need to be added to the file manually, because if the game isn't in a different branch already the `BetaKey` entry isn't there at all.

You can find branch names with [SteamDB](https://steamdb.info/).

If you do find a way to integrate this (if at all), might be best to add an option to hide branches that require a password. I don't how the password system works for steam so I don't know where it goes/where it is stored.
