### ISSUE TITLE
Sync playtime with Rockstar Game Launcher

### ISSUE THREAD

**Issue by alex-quiniou** [JosefNemec/PlayniteExtensions#329]
Hi,

I love playnite to track my playtime.
***Problem : Rockstar plugin does not sync with my account. I know it's not playnite dev's fault. Rockstar is a walled garden.***

Rockstar App report playtime for each game installed (see screenshot)
I guess this info has to be stored somewhere on the computer.

So, I have checked some basic folders to find this playtime.

Here my findings :
```
C:\Users\USERNAME\AppData\Local\Rockstar Games\Launcher\manifest_gta4_dev_425.xml
```
```
C:\Users\USERNAME\Documents\Rockstar Games\GTA IV\Profiles\RANDOMNUMBER\cloudsavedata.dat
```

Maybe the playtime is inside those files. But those files are encrypted. And I don't know how to decrypt them.

![Capture d’écran 2023-10-29 093506](https://github.com/JosefNemec/PlayniteExtensions/assets/34091990/c76c5889-3355-485b-8b61-ecaa3535caea)
![Capture d’écran 2023-10-29 093606](https://github.com/JosefNemec/PlayniteExtensions/assets/34091990/e3085da7-e46c-4bf9-8e7e-eb39ece18f47)

---

**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by alex-quiniou** [comment]
Update : 

I have used OpenIV, a tool to mod and open GTA files. Without success. The save files are still encrypted.

**Comment by JosefNemec** [comment]
I'm sorry to say that I have no plans working any more on Rockstar integration. I simply don't have time with all other integrations I have to maintain plus development on Playnite itself. Somebody will have to fork the plugin and implement it on their own.

**Comment by alex-quiniou** [comment]
Ok 

I will leave my last finding here : 

When GTA4 is played, those files are changed. So playtime has to be inside one of them

### C:\Users\USERNAME\AppData\Local\Rockstar Games\Launcher

1. `manifest_gta5_dev_469.xml` (**_encrypted or binary_**)
2. `dxdiag.txt` (redable, playtime not inside)
3. `settings_user.dat` (**_encrypted or binary_**)
4. `svc_events.json` (redable, there is an interesting string : `"time":133430425638090000`)
5. `service_log.txt` (redable, playtime not inside)

### C:\Users\USERNAME\Documents\Rockstar Games\GTA IV\Profiles\RANDOMNUMBER

1. `501C4FD0.dat` (**_encrypted or binary_**)
2. `SGTA412` (**_encrypted or binary_**, can be opened with **XB36Hazard's Launcher**. This is the save file for _GTA4_, the base game without _TBoGT_. It's not the total playtime. My total playtime is 152h and this file report 33h.)
3. `cloudsavedata.dat` (**_encrypted or binary_**)

### C:\Users\USERNAME\AppData\Local\Rockstar Games\GTA IV\Settings

1. `SETTINGS.CFG` (**_encrypted or binary_**)
