### ISSUE TITLE
Battle.net library integration breaks Playnite

### ISSUE THREAD

**Issue by profucius** [JosefNemec/PlayniteExtensions#331]
Newest version released today 11/13/2023 version 2.15.

After updating only this plugin and restarting Playnite, the UI will load once, then when I minimize or close the UI, it will not restore. It will also not start any games. The Playnite exe cannot be properly killed in task manager either.

Reverting this plugin to the previous version, or removing it entirely from Playnite, fixes this issue. Therefore I've deduced it is this specific plugin version that's the culprit.

**Comment by JosefNemec** [comment]
Can't reproduce. Also the change in this update can't possibly cause crashes to the entire app. If the issue doesn't happen in safe mode (you can restart in safe mode from help menu), then it's some other plugin causing the issue.

**Comment by profucius** [comment]
That is indeed odd. After uninstalling this plugin, I am no longer having the issue, and reinstalling causes it again. I will leave it uninstalled as I cannot continue diagnosis. Either way we can close this. The main idea of creating this ticket was for awareness.
