### ISSUE TITLE
Steam game from other folder than steam install folder not detected has installed

### ISSUE THREAD

**Issue by ovn76** [JosefNemec/PlayniteExtensions#34]
On my installation i have 2 folder for games installation, the default one and a Steam folder on disk g:

All games from G: disk are not detected has installed, i try to reinstall steam and forcve reinstall off game on G: disk samme issue.

Setting default on folder dos not make change.

![Capture](https://user-images.githubusercontent.com/85550053/121150383-c5184c00-c843-11eb-8930-feca05b34a18.PNG)

Diagnostics ID : c1d914ab-0743-4bf3-a2ba-7ea51ad21357

**Comment by JosefNemec** [comment]
Fixed in 8.13
