### ISSUE TITLE
Authentication windows are blank

### ISSUE THREAD

**Issue by Surbee6** [JosefNemec/PlayniteExtensions#341]
**Check for existing issue**
Check done. Similar (but not exact) issue found but closed.

**Describe the bug**
When needing to reauthenticate for any integration (Steam, Epic, Xbox, EA app I have tried), reauthentication window is blank.
UPDATE: This issue is happening after clearing the web cache and a reinstall.

**To Reproduce**
Using any of the integrations mentioned above, Library > Configure integrations > [Integration] > Authenticate (ensure Requires authentication is shown).

**Screenshots**
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/95538575/5194b520-1722-46a8-9e55-a1d1bbfe6cb7)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/95538575/6254b7d4-2da6-4b1e-a051-1e5e9b70b658)

**Diagnostics ID**
5a7792e3-94d3-43ec-b408-ab26e0e204d9

**Comment by JosefNemec** [comment]
Can't reproduce. Try clearing web cache in advanced settings.

**Comment by Surbee6** [comment]
Sorry, I should have included in the description that this is after clearing the web cache and a reinstall. Is there anything else I could try?
