### ISSUE TITLE
Legendary addon but for steam 

### ISSUE THREAD

**Issue by Koriebonx98** [JosefNemec/PlayniteExtensions#344]
So there the addon called “legendary” that adds epic games launcher via playnite and command line.

steam has a steam cmd app that could be used the same, is it possible to make one for steam using steam cmd?

login via the steam lib addon, and then it’ll know what steam games are installed and not,

on “install” click it runs steam cmd using the user login details, steam & game Id
It could have a controller friendly gui that ask what drive to install to? 

It would also be a good option to add a “mange” section to each steam game, that allows you to install/uninstall dlc.

also possibly add a progress bar to the game you clicked install, this will then allow the user to monitor the progress while browsing.

it would also be a good idea to imply steam store webpage as a accessible section in playnite & in full screen mode via controller & xinput, therefore we have steam store built into playnite

**Comment by JosefNemec** [comment]
#199
