### ISSUE TITLE
[Steam] Games from Steam's Family Sharing don't sync playtime in Playnite, even when "import playtimes" is set to always

### ISSUE THREAD

**Issue by HannahBanana1312** [JosefNemec/PlayniteExtensions#346]
> **Check for existing issue**
> Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

Couldn't find a similar issue when searching

> **Describe the bug**
> A clear and concise description of what the bug is.

Any game installed through family sharing gets imported into steam, but the playtime doesn't get synced. "import playtime of games in library" is set to always, and games from my own library sync properly

> **To Reproduce**
> If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

> **Screenshots**
> If applicable, add screenshots to help explain your problem.

![Beat Saber](https://github.com/JosefNemec/PlayniteExtensions/assets/36461227/b31ee3b6-613d-4363-ac66-1814f0a663cb)
![Celeste](https://github.com/JosefNemec/PlayniteExtensions/assets/36461227/c53931ec-38c4-460a-a990-8f77859c9868)

> **Diagnostics ID**
> Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

26e15e13-d7a4-4d2f-8e25-806f49037d3e

**Comment by JosefNemec** [comment]
Can't do anything about this because family shared games are not being reported in Steam's library web API.

**Comment by RichardLuo0** [comment]
Hi someone post this on steam community: https://steamcommunity.com/discussions/forum/10/6733519645848048014/#c6733519645848619684
I didn't test it, could you plz take a look

> Can't do anything about this because family shared games are not being reported in Steam's library web API.
