### ISSUE TITLE
Add private games playtime from steam

### ISSUE THREAD

**Issue by vanchaxy** [JosefNemec/PlayniteExtensions#348]
Steam [recently added a feature](https://store.steampowered.com/news/app/593110/view/3901870709962551195) to make the game private. Private games don't show playtime in Playnite even when an API key is provided. It would be nice to show playtime if it's possible to obtain it from the API.

**Comment by JosefNemec** [comment]
If they don't show up when API key is used then there's nothing we can do about it.

**Comment by vanchaxy** [comment]
@JosefNemec  Please, reopen. It shows up in API, but not in Playnite.

Playnite: 
<img width="257" alt="image" src="https://github.com/JosefNemec/PlayniteExtensions/assets/36510601/e4832e01-26f3-4b05-9155-dc88edba05d3">


GetOwnedGames API call:
<img width="487" alt="image" src="https://github.com/JosefNemec/PlayniteExtensions/assets/36510601/e3ebd56f-4ed9-4c4e-83bc-3508277750cc">

**Comment by vanchaxy** [comment]
@JosefNemec I have import configured and all other games show playtime correctly. E.g. this is a game played today (via Steam directly) and it shows in Playnite. Only two games that are "private" don't show playtime.

<img width="787" alt="image" src="https://github.com/JosefNemec/PlayniteExtensions/assets/36510601/bbc41f06-ea70-4219-8d7c-e37d4829cbc1">
