### ISSUE TITLE
Steam Private API Keys Frequently Requiring Re-Login

### ISSUE THREAD

**Issue by MEDumont** [JosefNemec/PlayniteExtensions#350]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.
I could not find a similar issue.

**Describe the bug**
For the last month, my Steam credentials have been expiring approximately every 48 hours. Whichever extension checks them first (in this case, Steam Wishlist Discount Notifier), will inform me that Steam is not authenticated. I have tried uninstalling that specific extension, but then the next extension that checks informs me of the same issue. This appears to be an issue with the Steam extension, or with the session being invalidated.

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.
1. Sign into Steam via a private account with an API key
3. Close Playnite
4. Wait 48 hours or more
5. Re-open playnite
6. Get a prompt that says authentication required

**Log**
```
15-11 22:00:18.459|DEBUG|SteamWishlistDiscountNotifier#SteamLogin:Steam GetLoggedInSteamId64 not logged. Address: https://store.steampowered.com/login/?redir=account%2F%3Fl%3Denglish&redir_ssl=1

15-11 22:00:18.459|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Started checking for wishlist. Status: AuthRequired, steamId: 

15-11 22:00:18.459|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Finished checking for wishlist

15-11 22:11:19.863|DEBUG|SteamWishlistDiscountNotifier#SteamLogin:Steam GetLoggedInSteamId64 not logged. Address: https://store.steampowered.com/login/?redir=account%2F%3Fl%3Denglish&redir_ssl=1
```

**Comment by JosefNemec** [comment]
Issue in SteamWishlistDiscountNotifier plugin, I'm not its dev you need to report it whoever made it.
