### ISSUE TITLE
Authentication Loop for Amazon Games

### ISSUE THREAD

**Issue by curanderacyber** [JosefNemec/PlayniteExtensions#353]
When attempting to authenticate with Amazon Games, even when entering details correctly, authentication is not received, and it continues to ask for additional authentication. This does not end after multiple attempts and will not authenticate.

Windows like this continue to show up
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/144497127/277e9a6a-8ee9-4575-9bd0-6ba95b0e23e1)

**Diagnostics ID**
4baaa9b4-0c97-42d7-a05b-0e87d7558f37

**Comment by GCTuba** [comment]
I'm now running into this issue too.

**Comment by JosefNemec** [comment]
Closing as I can't replicate the issue myself and fiddling with other people's accounts is a no go for me (I would need to have an access to the account to debug this). Somebody with an account affected by this issue will have to debug and fix it.
