### ISSUE TITLE
Steam extension doesn't authenticate

### ISSUE THREAD

**Issue by cvlnomen** [JosefNemec/PlayniteExtensions#356]
**Describe the bug**
Since today, the Steam extension has been unable to authenticate, resulting in games being unable to be imported. Re-authenticating via the settings menu does not solve the problem.

**To Reproduce**
Launch Playnite and let it import games. After a few seconds the Steam import will be canceled because the user cannot be authenticated.

**Screenshots**
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/54854679/710dcaa7-74fd-4c5d-b794-49cfa3fdba8c)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/54854679/92fe2b07-0fdf-417a-b58f-358797c68324)

**Diagnostics ID**
31568250-f41b-4c57-a15f-38f88dcbdba3

**Comment by JosefNemec** [comment]
Can't reproduce and it's failing on network connection to backed so most likely not extensions issue, see:
https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#general-network-issues

**Comment by cvlnomen** [comment]
The problem is now no longer present. I think the cause was Steam-related, as there were several other people experiencing the problem around the same time as me.
