### ISSUE TITLE
GOG won't let me authenticate.

### ISSUE THREAD

**Issue by GoldenShirt** [JosefNemec/PlayniteExtensions#361]
**Describe the bug**
GOG won't let me authenticate, it says: "Requires authentication" and when I click on authenticate, it shows this:
![image_2024-02-08_220032087](https://github.com/JosefNemec/PlayniteExtensions/assets/56863502/f185a63d-68c0-4232-bbaa-ee8c05af6e85) I tried checking for updates and reopening Playnite.

**To Reproduce**
Open playnite, it shows an error from gog extension 
![image_2024-02-08_220526782](https://github.com/JosefNemec/PlayniteExtensions/assets/56863502/47959fb8-80bc-4e44-89c2-6d415798ba34)
Click on the error.
Click on authenticate.

**Diagnostics ID**
4f5b2abd-8f85-4a5f-9629-20e6984c0578

**Comment by JosefNemec** [comment]
https://support.gog.com/hc/en-us/articles/16623319335197-We-are-undergoing-a-planned-maintenance-services-will-be-back-at-10-PM-UTC?product=gog

**Comment by jarrard** [comment]
This is happening again NOW and I don't think its because their services are down?  The old url people posting to check the API service is not valid.  Either way I just used chrome and logged in fine.

**Comment by JosefNemec** [comment]
Try clearing web cache from advanced settings, waiting if it fixes itself or seeing [this link](https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#general-network-issues).

I can't replicate the issue myself so it's most likely not an issue with the plugin.

**Comment by jarrard** [comment]
Yeah it was some bad webcache. Thanks for the tip.
