### ISSUE TITLE
GOG Library Extension - Unable to Authenticate

### ISSUE THREAD

**Issue by shangles** [JosefNemec/PlayniteExtensions#362]
**Describe the bug**
Playnite alerted me that the GOG extension (Version 2.18) was not authenticated.  When I attempt to view the extension properties and click the Authenticate button nothing happens.

**To Reproduce**
Have Playnite version 10.32 installed and the GOG library add-on installed and attempt to authenticate.

**Screenshots**
![PrtScr capture](https://github.com/JosefNemec/PlayniteExtensions/assets/9053908/23328c98-02b6-40d3-bd28-c7ff8070d556)

**Diagnostics ID**
558cf6e4-2514-4a5a-94cb-85b5126878bd

**Comment by shangles** [comment]
Looks like it's related to [site maintenance](https://support.gog.com/hc/en-us/articles/16623319335197-We-are-undergoing-maintenance-services-will-be-back-at-2-AM-UTC?product=gog).

**Comment by JosefNemec** [comment]
#361
