### ISSUE TITLE
"Import steam categories" button disappeared ?

### ISSUE THREAD

**Issue by JPDelprat** [JosefNemec/PlayniteExtensions#369]
Hello

  Sorry if I just can't find the functionality, or if the functionality has been removed for some reason, but I can't find the "Steam import categories/hidden flag" any more.
  
Thanks in advance

**Comment by JosefNemec** [comment]
It was removed because it no longer worked properly after recent Steam UI rework. It won't be coming back unless Valve add proper API for it.

**Comment by JPDelprat** [comment]
Too bad... Thank you very much for your answer. Regards?
