### ISSUE TITLE
[GOG Library] Pandemonium! not imported

### ISSUE THREAD

**Issue by LutzPS** [JosefNemec/PlayniteExtensions#372]
**Describe the bug**
GOG plugin don't import [Pandemonium!](https://www.gogdb.org/product/1207659054) installation

**To Reproduce**
1. Install [Pandemonium!](https://www.gogdb.org/product/1207659054)
2. Update GOG Library

**Screenshots**
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/47795197/cb8511fa-e7b1-4106-95e7-bd16c841d40f)

**Diagnostics ID**
f9f2855b-530a-4c8e-9599-a5d3970422e2

**Comment by JosefNemec** [comment]
Tested this and it's broken offline installer on GOG's side. Installing the game via Galaxy creates correct registry keys and the game is properly detected as installed by GOG plugin. This installer also doesn't generate .info files we could potentially use as a fallback to detect the game, so this is not fixable on our side.
