### ISSUE TITLE
EA Integration not working

### ISSUE THREAD

**Issue by Wella564** [JosefNemec/PlayniteExtensions#375]
**Describe the bug**
EA App integration isn't working, whenever I try to authenticate the in-app browser opens then randomly crashes so the authentication never happens

**To Reproduce**
Try using latest version of EA plugin 2.12 and authenticate your account

**Comment by JosefNemec** [comment]
Can't reproduce. Is this still an issue or was it some outage on EA's side?

**Comment by Wella564** [comment]
Hello, I fixed the issue by logging in directly with my email and password
instead of through google login
