### ISSUE TITLE
Playtime merge

### ISSUE THREAD

**Issue by iowesty** [JosefNemec/PlayniteExtensions#376]
a playtime merge manual or automatic, eg GTAV for xb1 1084h, GTAV PC 54h, GTAO XSX 163h, i just would like a way to manual put them together, like right click, add to merge then add all the others then merge together, I'm talking about the stats menu not the library 
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/166426517/3b89935d-738d-4b90-84bf-277b0a9093f7)

**Comment by JosefNemec** [comment]
That's up to Playnite, not any extensions.
