### ISSUE TITLE
Add steam family games

### ISSUE THREAD

**Issue by MrArdillo** [JosefNemec/PlayniteExtensions#377]
it is possible to add the option to add your family games on the playnite library? Or do we need the API for each account?

**Comment by JosefNemec** [comment]
Not possible, Steam API doesn't support it.

**Comment by yasathedog123** [comment]
not sure if this is already known BUT...
it does:
[https://steamapi.xpaw.me/#IFamilyGroupsService/GetFamilyGroup](https://steamapi.xpaw.me/#IFamilyGroupsService/GetFamilyGroup) (needed for retrieving the Group ID)
and:
[https://steamapi.xpaw.me/#IFamilyGroupsService/GetSharedLibraryApps](https://steamapi.xpaw.me/#IFamilyGroupsService/GetSharedLibraryApps) (group ID is required even tho the documentation says its not)
