### ISSUE TITLE
Xbox library integration: FallOut 76 not imported

### ISSUE THREAD

**Issue by DreamOfHero** [JosefNemec/PlayniteExtensions#379]
Hi,

I installed XBox Library integration on Playnite.
I own a copy of Fallout 76 on Microsoft Store, gifted from Microsoft some time ago, but the extension don't automatically add the game to the list.
I tried to add the game manually, but Playnite don't allow to install the game through it, so I delete it.

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/PlayniteExtensions/wiki/Xbox-Library-troubleshooting#not-all-games-are-imported
