### ISSUE TITLE
Humble - import fails on certain game (simian.interface++)

### ISSUE THREAD

**Issue by DragRedSim** [JosefNemec/PlayniteExtensions#38]
**Describe the bug**
Humble plugin fails to import games after a game name breaks the regex parsing. Further information is on the forum at https://playnite.link/forum/thread-722.html .

Based on an analysis of the exact reported error, I suspect the failure is caused at https://github.com/JosefNemec/Playnite/blob/master/source/Plugins/HumbleLibrary/HumbleLibrary.cs#L142 - the string is concatenated with a string containing a regex operation, in order to check for key availability; however, since the game title has the plus symbol in it, the regex match interprets this as the operand, and cannot handle the characters in that context. I suspect that the string being passed requires escaping before adding the operation to the end of the string.

**To Reproduce**
1. Have the game simian.interface++ in your Humble account. (Available from https://www.humblebundle.com/store/simianinterface )
2. Import Humble library to Playnite.
3. Await error.

**Screenshots**
https://i.ibb.co/SsFvbpJ/error.png

**Diagnostics ID**
4ca8085c-2bb6-4334-ac32-d9fa918ccf18

**Comment by JosefNemec** [comment]
Fixed in 8.14
