### ISSUE TITLE
Uplay install in another repertory

### ISSUE THREAD

**Issue by PPORCH3bis** [JosefNemec/PlayniteExtensions#380]
**Check for existing issue**
I don't seen the same issue

**Describe the bug**
Playnite can't import game from Ubisoft connect because (I think) I don't had install it in "c:\Program Files (x86)\" but in D: and I think it created the error "Ubisoft Connect client was not initialized". Of course it's open and the config file is present in "c:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\cache\configuration\configurations".

I tried to delete it without success.

**To Reproduce**
Install in another drive.

**Screenshots**
N/A

**Diagnostics ID**
d4ebc446-756d-4f33-bfe3-f891ba24e6e3

**Comment by JosefNemec** [comment]
Install path is taken dynamically from registry keys that Ubisoft Connect installer creates during installation, try reinstalling Ubisoft Connect launcher. If you used some 3d party method to install the launcher, use the standard installer instead.

**Comment by PPORCH3bis** [comment]
Sorry it was just that, thanks

**Comment by PPORCH3bis** [comment]
Sorry it was just that, thanks
