### ISSUE TITLE
Failed to import games from Amazon Games.

### ISSUE THREAD

**Issue by finkleroy** [JosefNemec/PlayniteExtensions#381]
Every time I load Playnite, I get the error "Failed to import games from Amazon Games. An error occurred while sending the request." This has been going on for a couple weeks now. I'm authenticated in the integration. Launching and signing into the Amazon Gaming app and signing in and out of my Amazon account in my browser have no effect. Diagnostic code: 5a353ee0-967e-4b39-8675-dca46a128297

**Comment by finkleroy** [comment]
This issue happened every time I opened Playnite for a week or two before I opened the issue. Since then, it only happens sometimes, but not every time.

**Comment by GCTuba** [comment]
I'm running into this issue as well. I'm also authenticated and it happens every time I open Playnite.
