### ISSUE TITLE
Amazon Games Library imports games without a name

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/PlayniteExtensions#383]
**Describe the bug**
Amazon Games Library imports games without a name. This only affects new installs because older ones will have already imported the games with names correctly.

Some findings:
- This issue is caused by the Amazon API used to obtain entitlements items `product.title` not being included in the response of certain games, therefore being `null`  on import. https://github.com/JosefNemec/PlayniteExtensions/blob/cd4ae8f1f7fe53ea6fd983a606ed58895db68929/source/Libraries/AmazonGamesLibrary/AmazonGamesLibrary.cs#L163-L169
- The affected games are the older ones that use a `Guid` for their `product.id`, e.g. `e3bc3283-5464-4946-80b8-8ac1401f7b16`, `790f3b07-fc9c-4efe-bb66-32bd348a9d23`, `fe19ef5f-a1e0-4caf-96b4-590b2c022b15`.
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/1389286/ec66022a-b033-4b4d-a74d-8eeac509a4fe)

- Newer titles that have the `amzn1.adg.product` prefix are not affected, e.g. `amzn1.adg.product.1e783728-3de2-4114-ae25-2e4dc850d9ff`. Their titles are correctly available in the response.
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/1389286/ae4c5d26-7a6b-4f0b-a31a-6a2d1d2cfde8)

- if I'm not wrong, the affected games were the ones given away from the twitch era, before the service was converted to Prime Gaming. This may indicate some conflict on their side that may or may not be resolved.
- Updating the current request to updated values doesn't fix it, for example, adding missing parameters in the request or updating the `UserAgent`
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/1389286/8dc32dca-ae45-43cf-b4f8-da7aca02f08f)

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/1389286/ee358e4b-f977-4eee-85fd-335c110ad9d0)

---

Considering this, these are the options:

- Wait and see if Amazon fixes this on their end
- Look for a new API endpoint if there is one that gets the game data
 
**To Reproduce**
1. Update your library on a fresh install

**Comment by darklinkpower** [comment]
Considering that this will affect a lot of people as seen on [reddit](https://www.reddit.com/r/playnite/comments/1coi99b/about_half_of_amazon_games_have_no_title_or/), if there is no quick solution, as a temporary measure I may suggest using the sku cleaned up for the name.
```csharp
public List<GameMetadata> GetLibraryGames()
{
    var games = new List<GameMetadata>();
    var client = new AmazonAccountClient(this);
    var entitlements = client.GetAccountEntitlements().GetAwaiter().GetResult();
    const string gameSuffix = "_game";
    const string gamePreffix = "CDG ";
    foreach (var item in entitlements)
    {
        if (item.product.productLine == "Twitch:FuelEntitlement")
        {
            continue;
        }

        var name = item.product.title;
        if (name.IsNullOrEmpty())
        {
            var newName = item.product.sku;
            if (newName.EndsWith(gameSuffix))
            {
                newName = newName.Remove(newName.LastIndexOf(gameSuffix));
            }

            if (newName.StartsWith(gamePreffix))
            {
                newName = newName.Substring(gamePreffix.Length -1);
            }

            name = newName.Replace("_", " ").ToTileCase();
        }

        var game = new GameMetadata()
        {
            Source = new MetadataNameProperty("Amazon"),
            GameId = item.product.id,
            Name = name.RemoveTrademarks(),
            Platforms = new HashSet<MetadataProperty> { new MetadataSpecProperty("pc_windows") }
        };

        games.Add(game);
    }

    return games;
}
```

This change makes most names correct and if if coupled with PR https://github.com/JosefNemec/PlayniteExtensions/pull/382, clicking install could help to know the correct name of the games that still have issues.

**Comment by JosefNemec** [comment]
Not a fan of this workaround. Better check traffic from the plugin to see what new API endpoints they are now using.

**Comment by darklinkpower** [comment]
I just checked and Amazon has fixed this issue in the response.

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/1389286/60a8eb13-43de-4ac4-93aa-9a8354d1b82e)

Closing issue.
