### ISSUE TITLE
EA App games launch, but Playnite thinks they've stopped

### ISSUE THREAD

**Issue by xCeeTee** [JosefNemec/PlayniteExtensions#384]
Every time I try to boot a game up, it launches normally. But Playnite for some reason thinks the game stopped running after a few seconds, and triggers my script. I have to always go back into Playnite and launch a 2nd time, which works as normal.

**Comment by SamDW96** [comment]
+1

**Comment by xCeeTee** [comment]
> +1

I thought of a solution but forgot to update this thread. Go into the game settings and head over to the script tab. You need to add the following script to run when the game is launched, adjust the time for your system. I put 120 seconds but I'm sure 90 and lower would work. Make sure to do it on the middle prompt and it'll suspend Playnite for however many seconds you set. 

`Start-sleep 120`

If you're having trouble with blue screens I also have a script to fix that issue. Works 90% of the time 100% of the time.

**Comment by JosefNemec** [comment]
I increased some timings in tracking code in 2.13 update. That's all I can pretty much do, other than making custom tracking individual for each game, which is not going to happen.

**Comment by xCeeTee** [comment]
> I increased some timings in tracking code in 2.13 update. That's all I can pretty much do, other than making custom tracking individual for each game, which is not going to happen.

I understand you wouldn't prioritise this as I don't think it's been requested before. Would it be possible to have a "tracking delay" in the advanced folder. That way if EA or Epic breaks again in a similar manner you won't ever have to worry about fixing it, we can do it ourselves. Ofc there's the script workaround but I know that intimidates new users who have never used scripts.

**Comment by Brucio84** [comment]
> > +1
> 
> I thought of a solution but forgot to update this thread. Go into the game settings and head over to the script tab. You need to add the following script to run when the game is launched, adjust the time for your system. I put 120 seconds but I'm sure 90 and lower would work. Make sure to do it on the middle prompt and it'll suspend Playnite for however many seconds you set.
> 
> `Start-sleep 120`
> 
> If you're having trouble with blue screens I also have a script to fix that issue. Works 90% of the time 100% of the time.

Hi, i have problems with blue screens, do you have the script to solve the problem? Thanks

**Comment by xCeeTee** [comment]
> > > +1
> > 
> > 
> > I thought of a solution but forgot to update this thread. Go into the game settings and head over to the script tab. You need to add the following script to run when the game is launched, adjust the time for your system. I put 120 seconds but I'm sure 90 and lower would work. Make sure to do it on the middle prompt and it'll suspend Playnite for however many seconds you set.
> > `Start-sleep 120`
> > If you're having trouble with blue screens I also have a script to fix that issue. Works 90% of the time 100% of the time.
> 
> Hi, i have problems with blue screens, do you have the script to solve the problem? Thanks

I found the actual cause of the BSODs. There was a file missing for some reason and I had to download it and place it in the folder. Unfortunately, when the new map launched the game became unplayable for me so I uninstalled it. Could you do me a favour to help you out please? Could you screenshot your Apex folder. Then screenshot any Easy Anti Cheat folders inside the Apex directory. That should be enough to jog my memory what file it was. 

I ended up deleting the script in question. All it did was take a working version of the "EasyAntiCheat_EOS.sys" file and place it in another directory after you verified the game. Then when you shutdown the game it would take the isolated file and paste it into the same file. However, sometimes I still got a BSOD so it wasn't flawless.
