### ISSUE TITLE
Error Authenticating Battle.net Account (Login Window Closes When Security Code is Requested)

### ISSUE THREAD

**Issue by Joselacerdajunior** [JosefNemec/PlayniteExtensions#385]
Hello,

When attempting to authenticate my Battle.net account for game synchronization, I enter my login credentials and press the connect button. At the exact moment the window requesting the two-factor security code is displayed, the login window closes, preventing the correct connection to the account and consequently failing the login.

After the authentication fails, I am returned to this page (all text in the image is in PT_BR):
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/69161529/152a6582-a79f-4ca7-babe-7bd20fa3416e)

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/69161529/ac3a2481-5997-4702-b23f-638ca8804dc6)

**Comment by Joselacerdajunior** [comment]
https://github.com/JosefNemec/PlayniteExtensions/assets/69161529/0c68fc52-34b3-4248-a0b5-5532e7380081

**Comment by JosefNemec** [comment]
Can't reproduce with my account. Probably something specific to PT_BR accounts?

Try clearing web cache from advanced settings to see if it fixes the issue.
