### ISSUE TITLE
[IGDB Metadata] Some games cannot be found

### ISSUE THREAD

**Issue by fm-117** [JosefNemec/PlayniteExtensions#387]
When looking for metadata using the IGDB search dialog, some games don't show up in results, despite being available on IGDB website.

**Examples**
- Quake: Mission Pack 1 - Scourge of Armagon ([15760](https://www.igdb.com/games/quake-mission-pack-1-scourge-of-armagon--1))
- Quake: Mission Pack 2 - Dissolution of Eternity ([15759](https://www.igdb.com/games/quake-mission-pack-2-dissolution-of-eternity--1))
- Aperture Tag: The Paint Gun Testing Initiative ([21897](https://www.igdb.com/games/aperture-tag-the-paint-gun-testing-initiative))
- Penumbra: Requiem ([8945](https://www.igdb.com/games/penumbra-requiem))
- Penumbra: Necrologue ([28487](https://www.igdb.com/games/penumbra-necrologue))

I had the issue on GOG Galaxy too so it is most likely related to the IGDB API, although Playnite finds way more games than GOG.

I don't know what is needed to identify a game and download its metadata from IGDB but if IGDB id is enough, a workaround would be to allow user to input the IGDB id in a field on the search dialog.

**Comment by fm-117** [comment]
Looks like #119 but i'm on latest version.

**Comment by JosefNemec** [comment]
Game mods (and some other "editions" like ports) are currently being excluded from search due to some issues with full text search in DB engine we use. There is a plan to replace it in future and enable mods in search results again.

> would be to allow user to input the IGDB id in a field on the search dialog
You can already do that.

**Comment by fm-117** [comment]
@JosefNemec Thanks for the quick reply.

How to search by id ? Just put the id in the search field ? Cannot test right now but will do later. I'll close the issue if it works.

**Comment by JosefNemec** [comment]
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/3874087/094f6a80-b187-429f-8159-cd1b41ee953b)

**Comment by fm-117** [comment]
All 5 games imported successfully using their id. Closing the issue.
