### ISSUE TITLE
Migrate from deprecated IGDB API collection field

### ISSUE THREAD

**Issue by villecc** [JosefNemec/PlayniteExtensions#389]
To be sunset August 2024, per this announcement from the IGDB Discord[^1]:

> Hello API-user!  We're doing some data cleanup, specifically on Collection, and Follows.  Please read the following as it may affect your implementations:
> 
> **Changes to Collection:**
> As part of our migration from a 1:many to a many:many relationship between games and series (collections), we have migrated the data that used to be in the old `collection` field into the new `collections` field in the games endpoint.  From collections, this can be found through the existing games filed [sic].  For the next 6 months (until August 2024) we will serve the data in both locations, then we will deprecate the collection field in the games endpoint and the games field in the collections endpoint
> 
> Actions required:
> - If you consume series (collection) data at some point in the next six months:
>   - Move from the collection field to the collections field in the games endpoint.
> 
> **Changes to Follows:**
> Furthermore, unrelated with the collections above, the field `follows` in the Game object is now deprecated and will be going away in future relapses.  The main reason is that those data are not maintained anymore and would not produce accurate insights.
> 
> 
> If you are Partnered with IGDB, please email partner@igdb.com and update us with an email address that we can use to contact you for future product and technical updates.

Right now, the IGDB extension fails to find series data for entries only using the new method.  [Example 1](https://www.igdb.com/games/monster-hunter-4-ultimate).  [Example 2](https://www.igdb.com/games/bioshock-2-remastered).  I do not have a setup for the API, but these are distinguishable on the website by the fact they only link the series once under "Information - Series:".  A typical entry that works for now, links it twice.  This is intended behavior on their side for this deprecation period, as per the quote below[^2]:

> We are migrating to a new way of tracking series, so many games will show the same series twice while we track both ways to avoid breakage for our API partners.  The old way of tracking will go away in the coming months and you won't see this any longer.  Thanks!

[^1]: https://discord.com/channels/114736716505546761/548536667884224578/1207258466805358592 (requires joining https://discord.com/invite/igdb to see)

[^2]: https://discord.com/channels/114736716505546761/1231199382087401523/1231234920089653301 (same applies)

**Comment by JosefNemec** [comment]
Done in 2.10
