### ISSUE TITLE
Amazon games library not updating with newly claimed (uninstalled) games anymore 

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/PlayniteExtensions#39]
**Check for existing issue**
none found

**Describe the bug**
Today a new batch of amazon prime games arrived, i claimed them and then went to update my game library in playnite but the newly claimed games are not appearing anymore. from what i can see when debugging only 50 games at once are returned now + a next token to grab the next 50 i guess, i don't know if this was always the case but i don't see in the code this next token being used nor that it grabs more than those 50 games each time i update library

**To Reproduce**
have more than 50 games on amazon and claim a new game but don't install it then update library and the new game(s) will never be added 

**Screenshots**

![image](https://user-images.githubusercontent.com/10714776/124163970-7fe0e600-daa0-11eb-87e6-1b97b207ec50.png)

![image](https://user-images.githubusercontent.com/10714776/124164433-ea922180-daa0-11eb-97f9-3e4be42d1d07.png)

**Comment by JosefNemec** [comment]
Fixed in 8.14
