### ISSUE TITLE
Xbox Game Pass Games not being added

### ISSUE THREAD

**Issue by ItsCinnabar** [JosefNemec/PlayniteExtensions#391]
**Describe the bug**
I am not getting _any_ auto imports of game pass games.

Per the page https://github.com/JosefNemec/PlayniteExtensions/wiki/Xbox-Library-troubleshooting#not-all-games-are-imported I have ensured they should be. Games have been started once. Games are not side loaded, they are installed via direct game pass app. I am on windows 11. They are not a console game, they are a pc game. They are not EA games.

I am able to manually import via add game > microsoft store application.

**To Reproduce**
Open game pass app > install game > run game > close game > open store just to be sure > run game > close game > playnite update all games.

**Screenshots**
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/50111163/df7e0dc8-8cc5-4822-a48c-2414a8ff88fc)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/50111163/d8f03110-c016-4e5e-b5bc-a51703216bcb)

**Diagnostics ID**
104165f8-989a-40bd-9eaa-6274d9943c48

**Comment by JosefNemec** [comment]
You don't have Xbox account connected. You need to connect Xbox account for games to be imported, even just installed ones.

**Comment by ItsCinnabar** [comment]
> You don't have Xbox account connected. You need to connect Xbox account for games to be imported, even just installed ones.

Thanks, works great now!

I want to point out that this is the opposite of the Steam extension - that one does not require an account. All I did was install it and everything worked. Perhaps an addition to the troubleshooting page should be added, a short blurb mentioning that this extension in particular requires you configure it by signing in?

**Comment by JosefNemec** [comment]
That's why settings for Xbox plugin are not the same as in Steam's case and import installed game option is actually disabled if you don't enable "Connect account" option.
