### ISSUE TITLE
Not showing non-installed games from secondary Steam accounts

### ISSUE THREAD

**Issue by KL13NT** [JosefNemec/PlayniteExtensions#398]
**Check for existing issue**
✅

**Describe the bug**
I just authenticated using my main Steam account and tried adding another one. I used a correct steam ID and API Key but it's not showing any of the non-installed games from the 2nd account library. Only installed ones, which I'd like to believe was just based on disk scanning?

I have the following options in settings enabled:
- Import installed games
- Import not installed games
- Import generic free items
- Private Account + Key

![image](https://github.com/user-attachments/assets/3e171c4f-2ef5-43fd-8b6d-85d1cec13ca8)

**To Reproduce**
1. Add steam account
2. Add 2nd steam account using ID and API key
3. Update library
4. Observe all non-installed games from 2nd account not showing

**Diagnostics ID**
66d95584-e339-4452-8244-c19434ca9321

**Comment by JosefNemec** [comment]
Account ID you set for that other account is from your primary account you are logged into, so they both point to the same user.

**Comment by KL13NT** [comment]
Damn, now I feel stupid. 💀 Thanks for the help!
P.S. maybe it's worth adding a check to the UI to flag this issue to other users? Was pretty easy to fall into 😅
