### ISSUE TITLE
Steam/Epic/Others Ability to list all games in library and show installed/not installed games

### ISSUE THREAD

**Issue by MrCaffeen** [JosefNemec/PlayniteExtensions#400]
**Check for existing issue**
Due dilligence done to check for any duplicate request types or issues.

**Describe the solution you'd like**
Would like to list all purchased games to the steam/epic user in their library and list them as either installed or not installed.
Simple first step would be to just have the ability to launch the other game engine to install the game if there is no easy way to request an install

**Screenshots**
Games for Epic/Steam are only listing installed games. can we list all available?

**Comment by JosefNemec** [comment]
This is already supported. Go to plugin settings and enable import of uninstalled games.
