### ISSUE TITLE
Failed to import games from Amazon Games

### ISSUE THREAD

**Issue by GCTuba** [JosefNemec/PlayniteExtensions#404]
Almost every time I start up Playnite, I get this error message that Amazon games were not imported. Clicking on the message opens up the settings menu that tells me user is authenticated so I know it isn't an issue with my account. Here is my diagnostics ID:

54caa8f5-ddf5-463c-9e75-9336cb18583c
![image](https://github.com/user-attachments/assets/a8f43efb-103d-48f4-ac9c-c225f1b680ce)

**Comment by BryanWall** [comment]
Update your add-ons. This has already been fixed.

https://github.com/JosefNemec/PlayniteExtensions/issues/401

**Comment by GCTuba** [comment]
I'm on version 2.8 and Playnite says there are no new add-on updates found.
