### ISSUE TITLE
Error when loading Rockstar plugin

### ISSUE THREAD

**Issue by poneymusical** [JosefNemec/PlayniteExtensions#41]
Hello

I installed the 2.0 version from this repository. Whenever Playnite starts, I have the following errors in playnite.log

18-07 13:06:10.432|ERROR|ExtensionFactory:Plugin doesn't support current version of Playnite SDK, supports 5.6.16.0
18-07 13:06:10.432|ERROR|ExtensionFactory:Plugin dependencices are not compatible: Rockstar Games library integration

Also the plugin doesn't work, obviously :)

Thanks for your help!

**Comment by JosefNemec** [comment]
What Playnite version to you have?

**Comment by JosefNemec** [comment]
I just noticed that you installed version from this repository, which is not supported in currently released Playnite versions. Follow links for official releases.
