### ISSUE TITLE
Only import Family Shareable games with Steam

### ISSUE THREAD

**Issue by swiffyjk** [JosefNemec/PlayniteExtensions#410]
**Check for existing issue**
(Similar to #396 but still requires the API keys of the other users)

**Describe the solution you'd like**
Currently, we can import from Additional Accounts in order to make Steam Family Sharing work. However, not all games from other accounts actually are family shared, yet are still imported.
This includes:
- Free games ([e.g. The Sims 4](https://steamdb.info/app/1222670/))
- Games that withdraw from Family Sharing ([e.g. The Crew 2](https://steamdb.info/app/646910/))
- [Games marked as Private in the Steam library]

I'm not sure how much of this data is readily accessible with the APIs in use, but since websites like SteamDB can detect this, then it'd be a nice solution to make the Steam Families system integrate well enough.

**Screenshots**
It could look something like this:
![image](https://github.com/user-attachments/assets/b895a160-f522-4bb8-ad12-80a6c5fd50e0)

**Comment by JosefNemec** [comment]
I don't know why this is a separate issue where there's already #396 for general family share support.

**Comment by JosefNemec** [comment]
Also detecting if a game is shareable or not is not a solution because it would slow down game import a ton.
