### ISSUE TITLE
Plugin not importing all games in my Humble library

### ISSUE THREAD

**Issue by Jock90** [JosefNemec/PlayniteExtensions#414]
Firstly, huge thanks for doing this and supporting Playnight. Amongst other benefits, these tools are invaluable in preventing us buying the same game multiple times.
I do have an issue with this plugin where it will not import all my games in my Humble library into Playnight - only 2 out of 28 were listed in Playnight. Is there anything I need to do to get the rest imported?

**Comment by JosefNemec** [comment]
If they are games that come as Steam (or other store) key, then the plugin will ignore those, unless you disable this in plugin's options.

**Comment by Jock90** [comment]
Thanks Josef, I didn't think of that. That's true, we don't want the same game counted twice because we purchased it on one platform (Humble) for use on another (Steam). I'll need to look at my other Playnight importer plugins and make sure they correctly only count once for purchases meant for a different store. I'm sure they all do.
