### ISSUE TITLE
Help with finding the correct reference in DetailsViewGameOverview.xaml for Date Added

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/PlayniteExtensions#419]
I'm sorry for posting this here, but I've already tried getting an answer on Reddit and Discord without success.

I want to add the date when a game was added to my database to the DetailsViewGameOverview.xaml, but I can't find the correct resource.

What do I have to put there for the Date Added to show up?

![2024-11-11 14_37_17-Playnite](https://github.com/user-attachments/assets/f3052967-4feb-483a-827a-3903efb2e7c4)

Thanks.

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/blob/master/source/Playnite.DesktopApp/Controls/Views/GameOverview.cs

You can also just check what the default theme uses.

**Comment by woutercools** [comment]
Thank you for replying.
But I can't for the love of G. get it to work.

I'm not an developer or anything, I'm just a tinkerer trying to edit the theme to my liking.
I don't understand enough what's going on.

Just putting "PART_ElemAdded" there isn't enough.
I think there's more to be done.

I would appreciate some help, but I understand your time is limited.
Thanks.

**Comment by woutercools** [comment]
> https://github.com/JosefNemec/Playnite/blob/master/source/Playnite.DesktopApp/Controls/Views/GameOverview.cs
> 
> You can also just check what the default theme uses.

Thank you for replying.
But the default theme doesn't have the "Date Added" entry on the game's detail view.

I can't for the love of G. get it to work.
I'm not an developer or anything, I'm just a tinkerer trying to edit the theme to my liking.
I don't understand enough what's going on.

Just putting "PART_ElemAdded" there isn't enough.
I think there's more to be done.

I would appreciate some help, but I understand your time is limited.
Thanks.

**Comment by JosefNemec** [comment]
There's no `PART_ButtonAddedDate`, see the link I posted. The only supported one is `PART_TextAdded`, so you can set it to TextBlock only. If you want to display on any other control, you will need to manually bind to added date.

https://api.playnite.link/docs/tutorials/themes/various.html#adding-additional-information-to-views

**Comment by woutercools** [comment]
<Label x:Name="PART_ElemAddedDate" Content="{DynamicResource LOCDateAddedLabel}" HorizontalAlignment="Right" />
<TextBlock x:Name="PART_TextAdded" VerticalAlignment="Center" />

This isn't working.
When I try binding, TextAdded isn't in the list.

You must be almost raging from my stupidity by now...
If you want to stop replying, that's ok.

**Comment by woutercools** [comment]
> There's no `PART_ButtonAddedDate`, see the link I posted. The only supported one is `PART_TextAdded`, so you can set it to TextBlock only. If you want to display on any other control, you will need to manually bind to added date.
> 
> https://api.playnite.link/docs/tutorials/themes/various.html#adding-additional-information-to-views

This isn't working.
When I try binding, TextAdded isn't in the list.

You must be almost raging from my stupidity by now...
If you want to stop replying, that's ok.
