### ISSUE TITLE
Ubisoft connect - Playnite thinks game has stopped shortly after launching

### ISSUE THREAD

**Issue by sharkusmanch** [JosefNemec/PlayniteExtensions#42]
**Describe the bug**

- Launch a Ubisoft Connect game via Playnite. Assassin's Creed Valhalla in this case.
- Playnite will minimize to tray and Ubisoft Connect will launch.
- Playnite will successfully launch the game, but will think the game is stopped shortly before the game actually launches.
- Playnite will then reopen and not be aware that the game is actually running. OnGameStop events will trigger, etc.

```
07-08 13:35:33.899|INFO|GamesEditor:Starting Assassin's Creed Valhalla, ca35b832-fbcd-4d54-8742-d3fdbf403fc4, 13504, c2f038e5-8b92-4877-91f1-da9094155fc5
07-08 13:35:33.899|INFO|GamesEditor:Using library plugin to start the game.
07-08 13:35:33.915|DEBUG|ProcessStarter:Opening URL: uplay://launch/13504
07-08 13:35:34.029|DEBUG|ProcessMonitor:Watching dir processes C:\games\Assassin's Creed Valhalla\, False, False
07-08 13:35:36.067|INFO|GamesEditor:Started Assassin's Creed Valhalla game.
07-08 13:35:38.083|INFO|GamesEditor:Game Assassin's Creed Valhalla stopped after 4 seconds.
07-08 13:35:38.108|DEBUG|GamesEditor:Game session was too short for client to be shutdown.
```

**Diagnostics ID**

`d311000b-5f7e-4fd9-906c-61aec26030f0`

**Comment by JosefNemec** [comment]
Can you reproduce it with other Uplay games as well? I don't own Valhalla to test this.

**Comment by sharkusmanch** [comment]
Installed a few other Ubisoft games (Ghost Recon Breakpoint, Immortals Fenyx Rising, Splinter Cell Blacklist) and was not able to reproduce with them, seems like ti might be specific to Assassin's Creed Valhalla.

**Comment by JosefNemec** [comment]
I tried it with Odyssey and it also worked correctly. Can you please check if there's a file in game's installation directory called `uplay_r1_loader64.dll` or similar?

**Comment by sharkusmanch** [comment]
Yea, there's a `upc_r2_loader64.dll`

```
> ls 'C:\games\Assassin''s Creed Valhalla\upc_r2_loader64.dll'


    Directory: C:\games\Assassin's Creed Valhalla


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          8/6/2021  11:02 PM         413336 upc_r2_loader64.dll
```

**Comment by JosefNemec** [comment]
Thanks. They changed the name, which means that Playnite won't trigger correct process tracking method, will be easy to fix.

**Comment by JosefNemec** [comment]
Actually, one more thing, can you please check if `UbisoftGameLauncher.exe` is running if Valhalla is running? Thanks

**Comment by sharkusmanch** [comment]
Nice. Yea `UbisoftGameLauncher.exe` is running while the game is running.

```
> tasklist | findstr Ubisoft
UbisoftGameLauncher.exe      31484 Console                    1     12,008 K
```

**Comment by JosefNemec** [comment]
Fixed in master.
