### ISSUE TITLE
Open Library Integration login pages in system default browser

### ISSUE THREAD

**Issue by ryanpf** [JosefNemec/PlayniteExtensions#420]
Login pages for Library Integrations currently open in a browser within the Playnite app.
![image](https://github.com/user-attachments/assets/8d3cf29d-8bf9-4e4a-8e84-7e9d6455499e)

Opening in the system default browser would allow me to use my browser's password manager to speed up my login.

**Comment by ryanpf** [comment]
It looks like this is not feasible for Epic because they don't offer an official API for reading a user's game library. The current Playnite Epic integration mimics the official Epic Launcher to get an access token and query Epic's internal API. Clever! But it requires Playnite to control the webview where the login occurs.

**Comment by JosefNemec** [comment]
This is not feasible for most integrations, we need stuff like cookies and other sessions data and we would need to harvest that from your browser somehow, which is complicated and not worth the trouble.

**Comment by joosniz** [comment]
Really hope you reconsider this or at least leave the ticket open in case you one day change your mind, threw me off when I realized that you needed to log in to all your accounts in a custom browser.

Epic's launcher used to have it's own custom browser as well but nowadays it opens in the default browser, does that mean that anything could've changed for Playnite in case you're mimicing it?

**Comment by JosefNemec** [comment]
There's nothing to reconsider here, it's simply limitation of not having access to APIs that would allow sign-in via different browser. This is of course integration specific and not blanket statement on all integrations.

**Comment by Anutrix** [comment]
Love this project.

Having this feature would greatly increase trust/security in the project as one would no longer need to worry that the embedded browser could be compromised by external factors.
