### ISSUE TITLE
Epic Games Store library integration importing Unreal Engine plugins

### ISSUE THREAD

**Issue by OneNot** [JosefNemec/PlayniteExtensions#423]
Since Epic changed the Epic Games Launcher's Unreal Engine section to use the Fab library instead of the old "Vault", Playnite has started importing Unreal Engine plugins as games. 
I'm not entirely sure that the Fab update is the change that is causing it, but I only noticed the plugins being added just now, and the Fab update being related to how Epic handles the plugins seems like something that might be the cause.

**To Reproduce**
Not sure if all plugins get added, but at least plugins that get installed to the engine (not the project) do. Meaning plugins of type "Engine Tool".

**Screenshots**
![image](https://github.com/user-attachments/assets/b9dfae94-e14a-4ba5-84fd-ee1aa1e72f2c)

**Diagnostics ID**
_2941a361-d8c5-4d38-a238-e45e8e1c07b0_

**Comment by JosefNemec** [comment]
Please go to `%appdata%\Playnite\ExtensionsData\00000002-dbd1-46c6-b5d0-b1ba559d10e4\catalogcache\` folder (put it exactly as is into a file explorer) and upload all files you see there, thanks.

**Comment by OneNot** [comment]
Here: [catalogcache.zip](https://github.com/user-attachments/files/18197872/catalogcache.zip)

If you want to look at some of the files, I'd suggest the ones last modified on 29.11.
`89efe5924d3d467c839449ab6ab52e7f_7b4fd5f947db4507a1b66f47f10730a2_5.5.0-38370801+++UE5+Dev-Marketplace-Windows.json` is an example of a UE plugin.

Seems like they have a categories array field that includes `{ "path": "plugins" }`. Perhaps that could be used to filter them out? Or maybe better yet, only allow ones with `{ "path": "games" }`? Assuming those are reliable?

**Comment by JosefNemec** [comment]
Did you clear that cache before? I don't see any items like `Quixel Bridge` and others from your screenshot in files you attached. Can you please also attach files from `%programdata%\Epic\EpicGamesLauncher\Data\Manifests\` folder, thanks.

**Comment by OneNot** [comment]
> Did you clear that cache before?

No, I didn't as far as I can remember. Wouldn't clearing the cache remove all the files in there? There appear to be files even from last year in there...

I did remove and add to exclusion list the plugins in that screenshot. Though if doing so causes the corresponding cataloguecache files to be removed, I don't know why _Magic Node_ for example can still be found in those files?

Anyway, here are the Epic [Manifests](https://github.com/user-attachments/files/18203861/Manifests.zip)

**Comment by JosefNemec** [comment]
Thanks for the files. Fixed in 2.23 update
