### ISSUE TITLE
Battle.net integration not importing Diablo 1

### ISSUE THREAD

**Issue by El-Tahur** [JosefNemec/PlayniteExtensions#428]
### Bug Description

The integration correctly imports all of my games, the only one missing is Diablo 1 (it was added to Battle.net not long ago), I have tried everything.

### Diagnostics ID

35fd0781-df31-4fdc-b424-72780d995b4d

**Comment by JosefNemec** [comment]
Can you please test it with with this plugin version? Just download and open to install it.

https://playnite.link/download/BattlenetLibrary_Builtin_2_20_test.pext

**Comment by JosefNemec** [comment]
Support added in 2.21 update
