### ISSUE TITLE
Ubisoft Connect doesn't support non-default install Ubisoft Connect locations for not-installed games.

### ISSUE THREAD

**Issue by thisischrys** [JosefNemec/PlayniteExtensions#429]
My Ubisoft connect is installed to %userprofile%\scoop\apps\ubisoftconnect\current and it's never detected (I keep getting the  "Failed to import games from Ubisoft Connect. Ubisoft Connect client was not initialized, please start the client at least once to generate user library data." message.

Installed games (In non-default install location D:\Games\Ubisoft) are detected fine, but uninstalled games are not.

I also use your Epic Store extension and my Epic store is installed to a similar location, but that one works fine.

**Comment by JosefNemec** [comment]
The path is taken from registry keys that Ubisoft Connect creates during installation. This simply means that scoop doesn't install the client correctly.
