### ISSUE TITLE
Add feature to launch Steam with offline mode on for family shared games

### ISSUE THREAD

**Issue by OsoaGH** [JosefNemec/PlayniteExtensions#44]
**Describe the solution you'd like**
I would like a feature which allows the user to select whether offline mode is automatically turned on when launching Steam for family shared games.
Why? Because with offline mode enabled, family shared games don't automatically close when the owner of the library launches a game.
To go a step further with this feature, it would be great if you could choose which family accounts enable offline mode. This would be good for alt account that aren't ever used, or family members / friends who don't play games but do own accounts.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/33041004/128769885-e80d664b-ca46-4760-b60a-4388211c22e7.png)
Quick mock-up I made of options menu

**Comment by OsoaGitHub** [comment]
Ok it appears I may have been incorrect - the owner of the games must go into offline mode in order for the recipients of the sharing to play for an infinite amount of time.
Maybe an option to pick and choose which games you own that should be put in offline mode and another to automatically put games in offline mode?

**Comment by JosefNemec** [comment]
Closing as it doesn't seem to be possible to launch Steam in offline mode explicitly. There are some hacks available that don't seem to work 100% and `-offline` argument is not supported anymore.
