### ISSUE TITLE
Universal Steam Metadata: Background selection dialogs provides invalid items

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/PlayniteExtensions#46]
**Describe the bug**
Background selection dialogs provides empty items

**To Reproduce**
Reproducible in Monster Hunter World

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/129397668-1f960a02-2c0d-4f65-a629-7bd9e50b2216.png)

This is caused by adding default background items that may be invalid: https://github.com/JosefNemec/PlaynitePlugin-SteamStoreMetadata/blob/master/source/UniversalSteamMetadata/UniversalSteamMetadataProvider.cs#L114-L117

![image](https://user-images.githubusercontent.com/1389286/129397746-fb8038c2-885e-43bc-af76-fcdd3cace2d2.png)

Example of invalid URL: https://steamcdn-a.akamaihd.net/steam/apps/582010/page_bg_generated.jpg

**Comment by JosefNemec** [comment]
Fixed in master.
