### ISSUE TITLE
Launch DRM-Free Steam and Epic Games without the launcher app

### ISSUE THREAD

**Issue by OsoaGitHub** [JosefNemec/PlayniteExtensions#47]
**Describe the solution you'd like**
I would like an option to disable opening the launcher of Steam and Epic Games for games that do not have DRM. A list of these games can be found here: [Steam](https://steam.fandom.com/wiki/List_of_DRM-free_games), [Epic](https://www.pcgamingwiki.com/wiki/List_of_DRM-free_games_on_Epic_Games_Store)
Maybe just launching the game through the detected .exe file will work.

**Comment by JosefNemec** [comment]
We used to have this for Epic, but it's basically impossible to reliably detect if a game is DRM-free or not, so I removed it. For that reason it's not going to be implemented. You can always manually edit game's play action to launch executable directly.
