### ISSUE TITLE
Installation tracking blocks UI thread

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/PlayniteExtensions#48]
**Description/Reproduction**
When initializing a game installation using Playnite, via the Xbox integration for example, the ui freezes every few seconds until the installation is finished. It shows, for example, when scrolling through the games list. Also happens with other integrations, but it is especially noticable with Xbox games.
I also tried it in safemode to rule out this being an issue with some extension.

**Diagnostics ID**
1fa74f83-526b-4ee0-adf7-25603fe9adc3

**Screenshots**
![bug](https://user-images.githubusercontent.com/24227002/130766142-e8e4ffc6-fda2-4768-b6ea-7aae5e7ca0fd.gif)

**Comment by JosefNemec** [comment]
Moved to a different repository, this has to be fixed in each integration separately.

**Comment by JosefNemec** [comment]
Fixed in master.
