### ISSUE TITLE
Playnite can't connect to a Epic Games account on 9.0 Beta

### ISSUE THREAD

**Issue by Fancy2209** [JosefNemec/PlayniteExtensions#57]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**
To be fast and clear, the problem is the following: I login to my Epic Games account and playnite fails with an generic "Authentication Failed" error

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.
Login to a Epic Games Store account

**Screenshots**
![image](https://user-images.githubusercontent.com/64917206/132045926-3c69912f-c7c9-48c6-9863-96f7313faa99.png)

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
9c835245-4904-49a7-969a-a01cc3930fc0

**Comment by JosefNemec** [comment]
Fixed in master.
