### ISSUE TITLE
Fail on Download Metadata for the game Time Clickers

### ISSUE THREAD

**Issue by Fancy2209** [JosefNemec/PlayniteExtensions#58]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**
If you try to download Metadata on a game trough the official store it doesn't work
This doesn't work on the free steam game Time Clickers

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.
Try to download metadata from Official Store on the game time clickers

**Screenshots**
https://media.discordapp.net/attachments/864521430070722560/883407123969622016/unknown.png?width=883&height=498

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
278cde2e-52d0-46f0-ba61-6b24f791f10d

**Comment by JosefNemec** [comment]
Fixed in master.
