### ISSUE TITLE
GOG import issue "Object reference not set to an instance of an object" in Playnite 9

### ISSUE THREAD

**Issue by dfirsht** [JosefNemec/PlayniteExtensions#59]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**
When trying to update GOG, seeing an error with the message: "Failed to import games from GOG. Object reference not set to an instance of an object."

**To Reproduce**
Add GOG library integration, attempt to update game library. Integration says I'm authenticated and I tried authenticating again with no difference in behvaior.

**Screenshots**

**Diagnostics ID**
b7149e64-bd7e-476e-b25c-6934fa80e9fa

**Comment by JosefNemec** [comment]
Fixed in master.
