### ISSUE TITLE
SteamStoreMetadata: Get additional play actions from the game manifest

### ISSUE THREAD

**Issue by Bluscream** [JosefNemec/PlayniteExtensions#6]
- https://steamdb.info/app/438100/config/
- `steamcmd.exe app_info_print 438100`
- `C:\Program Files (x86)\Steam\appcache\appinfo.vdf` -> https://github.com/shravan2x/Gameloop.Vdf or https://github.com/SteamDatabase/SteamAppInfo

**Comment by JosefNemec** [comment]
Closing since we wouldn't be able to start these, depending on a game. It's related to #74. Steam doesn't have a proper way how to launch different executable externally.

**Comment by Bluscream** [comment]
> Closing since we wouldn't be able to start these, depending on a game. It's related to #74. Steam doesn't have a proper way how to launch different executable externally.

wait what? shouldn't it be possible to just give the parameters through? That works for me when i do it manually

**Comment by JosefNemec** [comment]
This only works if different launch action launches the original exe with different arguments. It doesn't work if different executable needs to be launched, there is no way how to reliably do it, we've looked into it a lot on Discord.

**Comment by Bluscream** [comment]
Where can i upvote that request? 

If its not good enough as a standard feature maybe it can be done as a plugin?

**Comment by JosefNemec** [comment]
It should be already possible to do it as a separate plugin if you want to try it.
