### ISSUE TITLE
[P9] Playnite is having problems with the bulk import of metadata from IGDB for games from Origin and Uplay, at least

### ISSUE THREAD

**Issue by ferrazpedro** [JosefNemec/PlayniteExtensions#60]
**Describe the bug**
Whenever I bulk import metadata for games from Origin or Uplay, it just doesn't get anything from IGDB. When I search for each game individually, directly from the edit menu, it does finds the game entry in IGDB.

Since I had already corrected manually the games I had with issues, I just imported the metadata from the game "Anthem" with CTRL + D before sending the diagnostics package.

**To Reproduce**
You just need to bulk import metadata from IGDB, if the game is from Origin or Uplay, the problem occurs.

**Diagnostics ID**
2ef55708-76c8-409a-b129-a5150c6dfa3b

EDIT: Forgot to include, but games imported from Amazon, Steam, itch.io and manually seems to work alright.

**Comment by JosefNemec** [comment]
Fixed in master.
