### ISSUE TITLE
Xbox integration not adding games.

### ISSUE THREAD

**Issue by Creatiw89** [JosefNemec/PlayniteExtensions#61]
Playnite is not importing games from the Xbox app for some reason. I have to manually add them from Microsoft store.

**Comment by Creatiw89** [comment]
Nevermind, it's working now. Must have been a temporary issue.

**Comment by AhmedPro2013** [comment]
After adding the Microsoft store account many of it's games appear except Fallout 76 - PC. Note that i redeemed it using VPN on a different region then changed back the region, but I can still install it in the store.
