### ISSUE TITLE
[P9 Beta] Xbox Gamepass fails to fetch cover images

### ISSUE THREAD

**Issue by scampson** [JosefNemec/PlayniteExtensions#62]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

None found

**Describe the bug**

Xbox GamePass games don't have any cover images. A manual update of the Xbox game library also fails to fetch the cover images.

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

![playnite 9 beta bug image](https://user-images.githubusercontent.com/46944628/132311818-6561f7ef-cf36-4209-957d-edb0db51c6e7.PNG)

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

0a89b2b5-327b-490b-b695-cd728328e161

**Comment by JosefNemec** [comment]
Xbox integration doesn't support getting covers from Xbox store, you have to use other sources like IGDB for that. This didn't work in P8  either btw.

**Comment by scampson** [comment]
I believe I am using IGDB as a source for my metadata. 

If I do each game individually it works, but I can't do them in bulk.

Attached are some screenshots of my settings used.

![playnite 9 beta bug image](https://user-images.githubusercontent.com/46944628/132327292-49fb2c37-0ab6-4e35-bc81-d09fb83e26e4.PNG)

Note that Hades was done manually using edit game details.

I also found that the game details section of each game is very light on info compared to non-xbox games.

See here Xbox Game

![playnite 9 beta bug image 2](https://user-images.githubusercontent.com/46944628/132327794-c6a9f05e-6061-4dc1-82b0-ec9d7bd7bdff.PNG)

Vs

![playnite 9 beta bug image 1](https://user-images.githubusercontent.com/46944628/132327768-b394eadc-4d45-4558-88ac-1c1e8c5791ad.PNG)

I looks like using the bulk metadata import function doesn't work properly on xbox gamepass games.

If there is a setting i've missed then that's fine, but I had no problems doing this on Playnite 8, it just worked.

**Comment by JosefNemec** [comment]
Probably the same issue as #60
