### ISSUE TITLE
Nintendo Library Importer

### ISSUE THREAD

**Issue by j-marcon** [JosefNemec/PlayniteExtensions#64]
Hi,

Amazing work by the way, I really love this piece of software. I was wondering if anyone had considered adding a Nintendo library importer. I have been using Playnite to track my Nintendo Switch games and it's been quite useful. I've also noticed that the Xbox library importer allows you to import Xbox 360 and Xbox One games. So I figured that something similar might be achievable for the Nintendo digital library.

Has anyone ever considered this? I might start looking into this at some point if there is interest. Any help greatly appreciated once I get started.

Cheers!

**Comment by JosefNemec** [comment]
I'm have no plans for creating and maintaining any other integrations (I have too many to take care of already) and this repository is only of extensions I've made. I recommend raising this on our Discord, maybe people will show interest. Anyways, it should be definitely handled in somebody else's repository.
