### ISSUE TITLE
GOG: only currently installed games are updated

### ISSUE THREAD

**Issue by TheBlaiddDrwg** [JosefNemec/PlayniteExtensions#66]
**Describe the bug**
When launching Playnite it only updates the data for currently installed GOG games. The installation path is definetly updated, I don't know what else is.
The other games are not updated, which I only noticed, because I have the same library on multiple deviced synchronised via Nextcloud. I don't run Playnite more then once and always wait for the library files to be synchronised via said Nextcloud
The GOG update is stopped with the following error:

> Failed to import games from GOG.
> Failed to obtain library stats data.

**To Reproduce**
Launch Playnite and wait for the library update to work on the GOG games. The switching of machines is not necessary for this error to occure.

**Diagnostics ID**
126800a1-8af9-421b-ae57-65389ad28f4a

**Attachments**
[extensions.log](https://github.com/JosefNemec/PlayniteExtensions/files/7269068/extensions.log) (Steam's API key and account ID were removed)

**Comment by JosefNemec** [comment]
Fixed in 2.3
