### ISSUE TITLE
Rockstar: GTA V keeps getting detected as running after closing.

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/PlayniteExtensions#7]
![imagen](https://user-images.githubusercontent.com/1389286/83335766-a5d00180-a274-11ea-84da-24b5cf075f22.png)

According to the GOG Galaxy implementation [here](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/blob/master/src/game_cache.py) while `PlayGTAV.exe` should be used to launch the game, `GTA5.exe` should be used for play time tracking.

**Comment by JosefNemec** [comment]
Closing since I don't own a game on that launcher so I can't debug this. Pull requests are welcome.
