### ISSUE TITLE
Epic - Uninstalled Games Import to Wrong Library

### ISSUE THREAD

**Issue by TheRealFlamepanther** [JosefNemec/PlayniteExtensions#71]
After updating the Epic library plug-in from inside Playnite 9 today, new games in my Epic Games library were imported as Steam games. I tried a fresh install of Playnite, but still encountered the issue. Installed games are correctly imported to my Epic library and not my Steam library. Only uninstalled games are affected.

**Comment by JosefNemec** [comment]
Please restart Playnite in safe mode to see if it still occurs, this looks to me like some 3rd part extensions messing with newly added games.

**Comment by TheRealFlamepanther** [comment]
> I just tried it with my install and games are properly added under Epic library and source, so it is most likely some 3rd party changing it.

Alright. I'll check more carefully and report back.

**Comment by TheRealFlamepanther** [comment]
On a totally clean install with no add-ons other than Epic library, Steam library, and IGDB metadata, and all Playnite settings at default, importing my Epic library works as expected. I'll add stuff back one by one and notify the author of whichever add-on reintroduces the issue, if any.
