### ISSUE TITLE
Crysis Remastered 2 and 3 Not updating from Epic Library

### ISSUE THREAD

**Issue by dstansberry** [JosefNemec/PlayniteExtensions#72]
**Before creating bug report**
- Please use issue search in the repository first. If the bug is something really obvious there's a high change it was already reported.
- Make sure that the issue is not caused by custom theme or extension. You can restart Playnite in "safe mode" from help menu to quickly test it.
- Check list of known issues https://github.com/JosefNemec/Playnite/wiki/Known-Issues

**Integration issues**
If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
I don't own those games so I can test it myself. Please attach all information that was requested in the issue template.

**Comment by dstansberry** [comment]
And here is the diagnostics ID: 1572b3bf-8fab-4f64-8fd7-f4cd4de5a3bc

**Comment by darklinkpower** [comment]
The template is all the text that is there when you start creating the issue. You are meant to replace that information.

It mentions there that if it's an issue with extensions, then that one was not the correct repository.

![image](https://user-images.githubusercontent.com/1389286/137603114-8a958bfd-ec87-4e4a-87b6-de041babb139.png)
