### ISSUE TITLE
Cannot authenticate Amazon Games account (CAPTCHA loop)

### ISSUE THREAD

**Issue by Jessidhia** [JosefNemec/PlayniteExtensions#75]
Attempting to log in to the Amazon Games library integration gets me stuck on a CAPTCHA loop, where every attempt to log in just circles back to "log in again but with a CAPTCHA":

![image](https://user-images.githubusercontent.com/73085/138013291-c807a3e3-7414-4c8b-b1bc-47a5e8fb01bd.png)

This repeats no matter how often the login is attempted.

I suspect this is because my Amazon account is an amazon.co.jp account, and not an amazon.com account; but this login page doesn't allow you to choose the Amazon region.

**Comment by JosefNemec** [comment]
I can't reproduce it :( We just open that login page and wait for signin process to finish, we don't interact with it in any way. I'll see if I can figure why this is happening, but I'm not optimistic right now.

I'm guessing that login in Amazon Games client it self works just fine for your right?

**Comment by Myskat** [comment]
Hello, can you indicate the source, where did you get the information on the constructor of this URL? In particular, I can't figure out where..signin comes from? .. Found either ..oauth2 .. in Cognito, or ..oa? .. in LWA. I also can't find info on ... client_id = device: 4145 ... Found either ..client_id = amzn1.application-oa2-client.b4d6 .. in LWA, or ..opn6m304vbavurl9 .. in Cognito. 
Thank you in advance!
Hello, can you indicate the source, where did you get the information on the constructor of this URL? In particular, I can't figure out where..signin comes from? .. Found either ..oauth2 .. in Cognito, or ..oa? .. in LWA. I also can't find info on ... client_id = device: 4145 ... Found either ..client_id = amzn1.application-oa2-client.b4d6 .. in LWA, or ..opn6m304vbavurl9 .. in Cognito. 
Thank you in advance!

**Comment by Myskat** [comment]
> i have the same problem. i cant authenticate my amazon games with playnite, because the authentificate button leads to the following amazon.COM link.. https://www.amazon.com/ap/signin?openid.ns=http://specs.openid.net/auth/2.0&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.oa2.scope=device_auth_access&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.response_type=token&openid.oa2.client_id=device:6330386435633439383366623032393938313066303133343139383335313266234132554D56484F58375550345637&language=en_US&marketPlaceId=ATVPDKIKX0DER&openid.return_to=https://www.amazon.com&openid.pape.max_auth_age=0&openid.assoc_handle=amzn_sonic_games_launcher&pageId=amzn_sonic_games_launcher
> 
> problem is now, im german and i cant login there with my german amazon account... so no chance to get all my "twitch" games to playnite.

Hello, can you indicate the source, where did you get the information on the constructor of this URL? In particular, I can't figure out where..signin comes from? .. Found either ..oauth2 .. in Cognito, or ..oa? .. in LWA. I also can't find info on ... client_id = device: 4145 ... Found either ..client_id = amzn1.application-oa2-client.b4d6 .. in LWA, or ..opn6m304vbavurl9 .. in Cognito. 
Thank you in advance!
Hello, can you indicate the source, where did you get the information on the constructor of this URL? In particular, I can't figure out where..signin comes from? .. Found either ..oauth2 .. in Cognito, or ..oa? .. in LWA. I also can't find info on ... client_id = device: 4145 ... Found either ..client_id = amzn1.application-oa2-client.b4d6 .. in LWA, or ..opn6m304vbavurl9 .. in Cognito. 
Thank you in advance!

**Comment by Myskat** [comment]
Gentlemen, who can help with the answer to the question I posted above?
