### ISSUE TITLE
[Xbox library addon] - missing ms store games on xbox sync

### ISSUE THREAD

**Issue by spineduke** [JosefNemec/PlayniteExtensions#81]
**Describe the bug**
User is unable to add games that are connected to their MS Store library via the Xbox integration. They have both options checked "import installed games" "import uninstalled games".

The only games that appear are two games which were previously installed, one from GP and the other from the MS Store.

The games are added successfully to playnite when they've been installed at least once on that PC.

**To Reproduce**
Consistent issue.

**Comment by JosefNemec** [comment]
This is the limitation of API we use to import Xbox games currently. We are able to import only games that have been started at least once.

**Comment by Medrantol** [comment]
> This is the limitation of API we use to import Xbox games currently. We are able to import only games that have been started at least once.

sorry for the revive. Is there no fix for this yet? Thanks in advance.
