### ISSUE TITLE
Playnite fails to authenticate Epic library after successful login

### ISSUE THREAD

**Issue by Sighery** [JosefNemec/PlayniteExtensions#85]
**Describe the bug**
When configuring the Epic library and trying to login, I'm able to go through the Epic login window, and log in just fine, then the window closes after logging in, Playnite seems to lock up for a minute or so (whole window is completely unresponsive) and eventually fails with a generic "Failed to authenticate" error. From the `extensions.log` file all that seems related to this is the following:

```
23-10 18:10:00.825|ERROR|EpicLibrary#EpicLibrarySettingsViewModel:Failed to authenticate user.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EpicLibrary.Services.EpicAccountClient.getExcahngeToken(String sid) in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\Services\EpicAccountClient.cs:line 318
   at EpicLibrary.Services.EpicAccountClient.Login() in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\Services\EpicAccountClient.cs:line 120
   at EpicLibrary.EpicLibrarySettingsViewModel.Login() in E:\Devel\PlayniteExtensions\source\Libraries\EpicLibrary\EpicLibrarySettingsViewModel.cs:line 73
```

**To Reproduce**
I'm not sure how to replicate it. I tried deleting the program/user data and reinstalling Playnite and running on safe mode and I still have this issue. My Epic account uses an email/password and 2FA.

**Screenshots**
Playnite locking up and being unresponsive:
![locking_up](https://user-images.githubusercontent.com/11218602/138564652-abdf80e8-2f31-4ae6-820e-768179336dbc.PNG)
Failing after a while with generic error:
![generic_error](https://user-images.githubusercontent.com/11218602/138564656-68103e05-76d3-4e50-aac6-f30b78ba4f89.PNG)

**Diagnostics ID**
`a3b95450-2cc4-42ae-aafd-fb85f457206b`

**Comment by zero617** [comment]
> 看来你是对的。我刚刚在Windows VM上尝试过，没有超时。日志正常，Playnite识别登录并获取游戏。这很奇怪，因为我在同一台计算机上运行该VM，然后有超时问题，所以我怀疑这是由于某些防火墙/网络配置（我也不记得除了更改DNS之外配置有关网络或防火墙的任何内容）。
> 
> 所以我想我只需要在某个时候重新安装Windows，就可以解决它的任何问题。感谢您帮助找到问题。

it's same for me, and i don't know if it's because in China?
but i can login in brower or client

**Comment by zero617** [comment]
> It looks like it's timing out when getting tokens from `https://www.epicgames.com/id/api/`, so either some network issue (try restarting router or something) or FW/AV blocking Playnite process from accessing it.

it's same for me, and i don't know if it's because in China?
but i can login in brower or client

**Comment by Jakoers** [comment]
I have the same problem, is there any solution?

**Comment by Byron1c** [comment]
+1
No solution found so far. My client works fine, but Playnite fails with the same error "Failed to Authenticate User" after entering the Authentication code successfully.
