### ISSUE TITLE
GOG descriptions not being downloaded in English

### ISSUE THREAD

**Issue by XploitOcelot** [JosefNemec/PlayniteExtensions#86]
It would be great to be able to choose in wich language I want to have the downloaded details. I'm a spaniard, but live in Switzerland.
My option would be to have the details in either spanish or english. BUT for Steam and Origin games the details are downloaded only in english, from GOG everything is in german... it's quite a mess.

It's a suggestion that sooner or later would come.
I'm totally in love with Playnite and only use it from yesterday. THANK YOU!!!

**Comment by JosefNemec** [comment]
Done in the latest update.
