### ISSUE TITLE
Metadata for user-defined tags (Steam)

### ISSUE THREAD

**Issue by mascherone108** [JosefNemec/PlayniteExtensions#88]
Currently the tags for Steam games are taken from the "features" part of the Steam store which usually contains information such as Partial controller support, Steam Cloud, Steam Trading Cards, etc. My suggestion is to also add user-defined tags into the metadata. It would improve the functionality when trying to filter library for tags such as Story rich, Great Soundtrack or Open World.

**Comment by JosefNemec** [comment]
Was added couple months ago.
