### ISSUE TITLE
Download official metadata for Uplay games

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/PlayniteExtensions#91]
So this is actually the problem I had in my last post, I'll try to be more clear this time: For example, I have Splinter Cell Conviction installed through Uplay, it shows up in the library with only the usual "Platform: PC" description. But when I download the metadata with the default settings it doesn't change anything, it's still a blank description. This happens for a number of Uplay games. Downloading the metadata manually through the edit panel works, but don't know why I have a feeling the description is not how it used to be. My memory might be wrong, though, but I'm certain of the first issue.

**Comment by JosefNemec** [comment]
The way Uplay store and client work make this really hard to reliably implement. I'm closing it for that reason. I recommend using other metadata sources (like IGDB) to fill missing data.
